### ISSUE TITLE
support for <path>:<line>:<column>

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1025]
It would be really great if `<path>:<line>:<column>` was supported from using `System.out.println`. If it already is, then please provide a working example, cause I can't get it to work.

**Comment by fbricon** [comment]
I'm sorry I don't understand what you're asking. Is it about formatting the output (in which case that'd be something to ask at https://github.com/microsoft/vscode-java-debug/issues )? Is that feature available in other IDEs?

**Comment by akaroml** [comment]
Is it to have some special symbols to reference the position info of current source file at compile time? Something like the `__FILE__` and `__LINE__` macros in C.

**Comment by clankill3r** [comment]
Just like we have clickable links now when having an exception:

<img width="736" alt="Screen Shot 2019-08-27 at 13 13 16" src="https://user-images.githubusercontent.com/738650/63766922-87e00580-c8cc-11e9-9a76-c389dc7d979e.png">

I would like to be able to make those links as well.

**Comment by akaroml** [comment]
> Just like we have clickable links now when having an exception:
> 
> <img alt="Screen Shot 2019-08-27 at 13 13 16" width="736" src="https://user-images.githubusercontent.com/738650/63766922-87e00580-c8cc-11e9-9a76-c389dc7d979e.png">
> 
> I would like to be able to make those links as well.

This should be supported by Debugger for Java already. @testforstephen to confirm.

**Comment by testforstephen** [comment]
I believe the screenshot above is from Java Debugger's DEBUG CONSOLE. The debugger only provides the source info for the call stack message, because the call back itself contains the basic source info such as the file name and line number. 

For a normal message printed by `System.out.println`, it's just a text in the output. It's not easy for the debugger to guess where the source is.

**Comment by akaroml** [comment]
If you print the call stack by calling e.printStackTrace(), then you can already jump to the definition today.

But for the case of println, we need to have a protocol because the mechanism here is just using some regular expression and highlight the matches in the output. @testforstephen @clankill3r could you work on the protocol first?

**Comment by fbricon** [comment]
@akaroml can you transfer the issue over to  https://github.com/microsoft/vscode-java-debug/issues? If not close it here and create a new one there

**Comment by akaroml** [comment]
> @akaroml can you transfer the issue over to https://github.com/microsoft/vscode-java-debug/issues? If not close it here and create a new one there

No problem. Do you think you can lift my access level of this repo then I can move this issue directly to the debugger repo?

**Comment by akaroml** [comment]
Or @testforstephen can you do that?

**Comment by testforstephen** [comment]
Github doesn't support transfer issue across different orgs. Need manual do that.

**Comment by fbricon** [comment]
right you have right access to both repos but cross-org transfer is not supported. lame.
Anyways, closing for https://github.com/microsoft/vscode-java-debug/issues/723
