### ISSUE TITLE
Sometimes the syntax highlighting is not correct

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#1048]
So far I have no idea when this will happen, but it occurs sometimes in my project.

##### Environment
- Operating System: Win 10
- JDK version: 1.8.0_221
- Visual Studio Code version: 1.37.1
- Java extension version: 0.47.0

##### Current Result
![image](https://user-images.githubusercontent.com/6193897/63988056-0aef9e80-cb0d-11e9-9cc4-5a5aef9ac695.png)

##### Expected Result

The modifier `public static` should show in blue instead of white

**Comment by fbricon** [comment]
As usual, these syntax highlighting issues are caused by the upstream [textmate grammar](https://github.com/atom/language-java/blob/master/grammars/java.cson), consumed by [vscode](https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json) itself.
@jdneo we have a bunch of [them already](https://github.com/redhat-developer/vscode-java/issues?q=is%3Aissue+is%3Aopen+label%3Ahighlighting), if you wanna take a look, please be my guest ;-)

**Comment by Eskibear** [comment]
It's actually duplicate with https://github.com/redhat-developer/vscode-java/issues/728 
See https://github.com/microsoft/vscode-java-test/blob/611b16a9882f4316c07ee7b43c8d8e6ba5dec428/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java#L269

And the root cause is https://github.com/atom/language-java/issues/172

**Comment by jdneo** [comment]
@Eskibear Yes you are right. I'm closing this issue and let's track it in #728.
