### ISSUE TITLE
On paste handle wrong package and class name

### ISSUE THREAD

**Issue by NikolasKomonen** [redhat-developer/vscode-java#1088]
After the customized paste feature, #1075, is implemented, look into also adding functionality to

1) Change the old package name to match the new package structure
    eg: `The declared package "foo.bar" does not match the expected package "org.acme"Java(536871240) -> change package declaration to org.acme
`

2) Change the old class name to match the new file name
    eg: `The public type Foo must be defined in its own file Java(16777541)-> Rename type to Something (i.e if the code was copied into a file named Something.java)`

**Comment by NikolasKomonen** [comment]
@fbricon As of now this looks like this issue would require custom commands to be able to receive/access the code action edit. Currently, it doesn't seem possible to access the code actions from code and can only be done through the UI.

I'm waiting on a response from the vscode gitter, maybe they will have a solution.

**Comment by rgrunber** [comment]
I'm going to close this because when there is a package mismatch (folder vs. package declaration), or a compilation unit mismatch (type root declaration vs. file name), there are 2 quick-fixes proposed in each case, and so we shouldn't favour one over the other.

for package mismatch, one quick-fix would create a new folder structure for the package, or rename the package declaration based on the existing folder structure. For a compilation unit mismatch one quick-fix could rename the file, or the type root declaration. That seems to be enough help.

Also, I think Fred pointed out a while ago that only Eclipse (ECJ?) enforces this requirement but the JLS doesn't :

https://docs.oracle.com/javase/specs/jls/se17/html/jls-7.html

> Modules and packages may be stored in a file system or in a database ([§7.2](https://docs.oracle.com/javase/specs/jls/se17/html/jls-7.html#jls-7.2)). Modules and packages that are stored in a file system **may** have certain constraints on the organization of their compilation units to allow a simple implementation to find module, class, and interface declarations easily.
