### ISSUE TITLE
command 'java.project.create' not found

### ISSUE THREAD

**Issue by singhalrbl** [redhat-developer/vscode-java#1141]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_91
- Visual Studio Code version: 1.36
- Java extension version:

##### Steps To Reproduce
1. install plugin java Extension Pack
2. ctrl+shift+p choose java:create java project

will get error as command 'java.project.create' not found

what to do i am stuck???

**Comment by fbricon** [comment]
I'm sorry vscode-java doesn't provide such command. You should open a ticket in https://github.com/microsoft/vscode-java-pack/issues

cc @akaroml

**Comment by Vigilans** [comment]
This issue is tracked in microsoft/vscode-java-dependency#179 now. 

The `command not found` behavior is generally caused by an extension not starting correctly. Could you reinstall `java-dependency-viewer` extension and try one more time, and if it fails, provide following logs to [linked issue](https://github.com/microsoft/vscode-java-dependency/issues/179)? 
* From Menu bar -> Help -> Toggle developer tools, copy any exception log in Console channel
* Press Ctrl + ` and switch to output, copy any exception log in these channels:
  - Language support for Java
  - Log (Extension Host)

**Comment by aditya-shrivastavv** [comment]
I think i Solved it, I was Facing this Problem too.
On Clicking create data project nothing happend for 2 sec and then a error poped up saying - 'java.project.create' not found.
Solution - (At least worked for me😅)
YOU HAVE TO ADD JAVA TO PATH.

Here are the steps to do that -

Find Java Folder in you C drive and then inside JDK folder, copy the path of bin folder (it will look like this - C:\Program Files\Java\jdk-15.0.1\bin)
Search Environment Variables in settings.
A system Properties tab will open.
Click on environment variables button.
Inside System variables Group search for the varible named 'Path'.
Click on it and then on the edit button.
A Edit Environment Varible tab will open.
Click on New and Paste the path of the Bin folder copied Eariler.
Click OK.
All Done !
Now Close all the Opened tabs one by one.

IMPORTANT -

You MUST restart vs code. (it should work now)
Still not working try restarting your PC
THANKS 😁

**Comment by aditya-shrivastavv** [comment]
Solved Follow on -
[https://github.com/microsoft/vscode-java-dependency/issues/179](url)

**Comment by aditya-shrivastavv** [comment]
Issue Solved - Follow On --->
[https://github.com/microsoft/vscode-java-dependency/issues/179#issuecomment-1328975852](url)

**Comment by aditya-shrivastavv** [comment]
Issue Solved - Follow On --->
https://github.com/microsoft/vscode-java-dependency/issues/179#issuecomment-1328975852
