### ISSUE TITLE
Organize Imports doesn't work

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1142]
In the latest 0.53.0, "Organize Imports" doesn't work any more. It should be a regression bug.

**Comment by fbricon** [comment]
Yeah that's a pretty big regression. Can you provide a fix so that we can release a new version ASAP?

**Comment by testforstephen** [comment]
@Eskibear is working on it.

**Comment by Eskibear** [comment]
Investigated. Part of the entries are blocked:
- Not Working: trigger "organize imports" from command palette / keyboard shortcut
- Working: trigger from right click -> "Source Action..." -> organize imports

I'm providing a fix for it. 

### Root cause
When you trigger "organize imports" from command palette, or keyboard shortcut, the client sends request, thus the `SourceActionProcessor` is not working accoring to current logic. 
```
[Trace - 下午4:38:44] Sending request 'textDocument/codeAction - (24)'.
Params: {
... 
    "context": {
        "diagnostics": [],
        "only": [
            "source.organizeImports"
        ]
    }
}
```

When you right click and "Source Action..." 
```
[Trace - 下午4:38:53] Sending request 'textDocument/codeAction - (25)'.
Params: {
...
    "context": {
        "diagnostics": [],
        "only": [
            "source"
        ]
    }
}
```

I used `codeActionKinds.contains(baseKind)` as the condition to call each processor. Should match the prefix.
