### ISSUE TITLE
better handling of error caused by manipulating jvmargs

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1158]
I was using latest vscode java and quarkus and had no error/content assist.

Turned out I had some edits in `java.jdt.ls.vmargs` that somehow caused LSP not to start. 
unfortunately I didn't take a copy of the values as i was getting desperate to just get something working ;)

Error logs just said:

```
 message: 'Failed to initialize Language Support ' +
    'for Java due to Error: Internal error.',
  level: 'error',
  timestamp: '2019-11-24 18:00:41.160'
```

which gives about zero info for a user to know where to look.

I only realized it could be the jvmargs settings as I seen same  error before.

Could we not:
a) have actual output of the failing process -  assume java would complain about bad flags or you would see a OutOfMemory msg or similar.
b) have a visual indication that the java lsp was not loading properly (vscode is able to detect things are out of date and warn me it needs torestart - can't it also warn me something exceptionally bad happened trying to launch >

**Comment by fbricon** [comment]
What did the server log contain?

**Comment by maxandersen** [comment]
lots of those errors - repeated ad infitum.

**Comment by fbricon** [comment]
I believe that was the client log. Have you tried opening the server log? Command Palette > `Java: Open Java Language server log file` (there's also an `Open all log files` command)

**Comment by snjeza** [comment]
@maxandersen You can also try to add -Dlog.level=ALL to the default "java.jdt.ls.vmargs" value.

**Comment by maxandersen** [comment]
I used open all log files and one was basically a json version of what was in the other. same "internal error" message.

unfortunately the logs seem to roll over so i don't have the past logs ?

**Comment by rgrunber** [comment]
We've made it a lot easier to debug such cases with commands like `Java: Open All Log Files`. If some option to `java.jdt.ls.vmargs` failed today, as long as `java.trace.server` is set to `verbose`, they would see exactly what was used since that setting would get sent to the language server like any other setting.

Another consideration is to perhaps use something like `-XX:+IgnoreUnrecognizedVMOptions` by default which should prevent unrecognized options from bringing down JDT-LS (provided they're from -XX:). On the other hand perhaps knowing the option won't actually do anything is valuable to know immediately.
