### ISSUE TITLE
Class file is updated when source is saved, causing build to think it's up to date

### ISSUE THREAD

**Issue by nobody-famous** [redhat-developer/vscode-java#1192]
[provide a description of the issue]
When a java file is saved, the class file is updated to have the same timestamp which causes maven to think the class file is up to date even though it's not.

##### Environment
- Operating System: Ubuntu 18.04
- JDK version: OpenJDK 11.0.4
- Visual Studio Code version: 1.40.2
- Java extension version: 0.54.2

##### Steps To Reproduce
1. [step 1] Create a maven project, mvn archetype:generate -DgroupId=foo -DartifactId=bar -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
2. [step 2] Compile with "mvn compile"
3. [step 3] Edit src/main/java/foo/App.java and change "println" to "printl" to introduce an error. Save the file
4. [step 4] ls -l src/main/java/foo/App.java target/classes/foo/App.class
==> Both have the same timestamp
5. [step 5] Try to compile again with mvn compile, it says all classes are up to date
6. [step 6] Disable Language Support For Java extension
7. [step 7] Edit and save the file again, do ls -l again, timestamps are different.
8. [step 8] mvn compile recompiles and gives the correct compilation error.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
You can uncheck the user setting `java.autobuild.enabled` to disable the auto build introduced by Java Language Server extension.

**Comment by fbricon** [comment]
This is working as designed. Class files are compiled in the target/classes directory used by Maven, so that they can be picked up by any running/debugging process launched by Maven.

Setting `"java.autobuild.enabled":false` is one way to disable automatic compilation, but another alternative would be to create a Maven profile that sets a different output directory for the vscode-java/eclipse/m2e builds:

```
<profiles>
  <profile>
    <id>m2e</id>
    <!-- This profile is only activated when building in Eclipse with m2e -->
    <activation>
      <property>
        <name>m2e.version</name>
      </property>
    </activation>
    <build>
      <directory>m2e-target/</directory>
    </build>
  </profile>
</profiles>
```
On the plus side, you never get build conflicts between CLI and vscode-java/eclipse, competing to write to the same files, on the downside this requires extra configuration to either clean the extra m2e-target folder or add it to your SCM's ignore list.
