### ISSUE TITLE
Keep Java Language Server running between window reloads

### ISSUE THREAD

**Issue by ViniciusAtaide** [redhat-developer/vscode-java#127]
I have a gigantic project in my work that expands 10k+ files, everything that needs window reload becomes a pain.

##### Environment
- Operating System: Windows
- JDK version: 8
- Visual Studio Code version: 1.9 Insiders
- Java extension version: v.0.0.8

##### Steps To Reproduce
1. Install a Plugin
2. Reload Window

##### Current Result
Java Language Server restarts
##### Expected Result
Keep server running so I keep all my project information

**Comment by ViniciusAtaide** [comment]
Woah, godspeed! Do you think this is possible? The java server seems to be a child spawn proccess of the vscode window, that could be a simple matter if the proccess could be detached, I think there would be a few gotchas for cases where the user really wants to restart the JLS. Thanks for the support, it's my first issue/enhancement report on Github.

**Comment by fbricon** [comment]
since vscode-java 0.13.0, starting the java server on existing workspaces is [**very** fast](https://github.com/eclipse/eclipse.jdt.ls/pull/410#issue-268867880). Is this issue still relevant?

**Comment by rgrunber** [comment]
Closing as I think this has since been addressed. We should be much better at loading a project that has already loaded before. I think in the past we even had issues of unnecessary builds being performed which we have since fixed. Feel free to re-open if this is still an issue.

My guess is window reloads affect the extensions themselves, so I doubt we can keep the language server around when the underlying extension has been restarted.
