### ISSUE TITLE
syntax highlighting detects regex as comment

### ISSUE THREAD

**Issue by Meir017** [redhat-developer/vscode-java#1343]
typing `//*` causes the rest of the line to be recognized as a comment event it's inside a literal string

![image](https://user-images.githubusercontent.com/9786571/77647121-8663e200-6f6e-11ea-82ff-1ec654ab4296.png)

the compiler works fine, it's only the highlighting that isn't right

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by rafaelrenanpacheco** [comment]
Syntax highlight is not done by vscode-java. It is a combination of token identification and the color theme you are using. In you case looks like the token identification is wrong, and you could open an issue upstream (https://github.com/atom/language-java). After upstream fix the issue, vscode team will pull those fixes and the problem will be gone on a new release.

On the other hand, I'm using VS Code 1.43.2, which may have new fixes from `atom/language-java` grammar, because I don't see this bug anymore:

![image](https://user-images.githubusercontent.com/12160864/78363637-795c7980-7592-11ea-9e18-bcfd1ed927e8.png)

The token identification is just fine, take a look:

![image](https://user-images.githubusercontent.com/12160864/78363719-a3ae3700-7592-11ea-8c84-681610aadece.png)

It's a `entity.name.function.java`, and not a comment block.

Try to update your VS Code to see if this bug is fixed.

**Comment by fbricon** [comment]
Can't reproduce with 1.43.2 either. I tested all themes I have (a lot), nothing unusual. So either this was fixed upstream or a 3rd party extension is messing up with the syntax. In any case, there's nothing we can do here.
