### ISSUE TITLE
Semantic highlighting sometimes looks bad

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1396]
When "java.semanticHighlighting.enabled": true, even without any particular token settings, this causes bad highlighting of existing code using static imports:
When enabled:
<img width="756" alt="Screen Shot 2020-04-16 at 12 11 57 PM" src="https://user-images.githubusercontent.com/148698/79444669-c5201180-7fdb-11ea-8b02-5762a8880597.png">

When disabled:
<img width="749" alt="Screen Shot 2020-04-16 at 12 12 30 PM" src="https://user-images.githubusercontent.com/148698/79444675-c6e9d500-7fdb-11ea-85a3-da124d24b6b1.png">

**Comment by rafaelrenanpacheco** [comment]
Isn't this a specific color theme bug? I'm using this [beautiful theme](https://marketplace.visualstudio.com/items?itemName=rafaelrenanpacheco.darcula-theme) and the semantic highlight for fields inside methods are working as expected:

![image](https://user-images.githubusercontent.com/12160864/79574121-14c31380-8096-11ea-8313-59ac045fa3fa.png)

Before semantic token it was not possible to set the fields color inside a method. Only fields with `this.` prefix got coloring.

**Comment by Eskibear** [comment]
The bug is caused by caclulating semantic tokens of wrong AST nodes. And it should be fixed by https://github.com/eclipse/eclipse.jdt.ls/pull/1416/commits/53f8c96bbc80aa3e1d3834389010575c039f3666 and https://github.com/eclipse/eclipse.jdt.ls/pull/1418 .

Below are steps to stably reproduce it. 
* Open an empty folder.
* Create 2 .java files (A.java, B.java) directly under the folder.
* Open A.java and close all the other files.
* Do some editing in A.java, e.g. type some whitespaces
* Now open B.java, you'll see wired highlighting. 

A.java
```java
public class A {
    String aString = "";
}
```

B.java
```java
public class B {
    final static int constantInteger = 1;
}
```

![image](https://user-images.githubusercontent.com/2351748/80297631-73377280-87b7-11ea-9d8b-632cd6fcae23.png)

**Comment by fbricon** [comment]
Fixed in 0.61.0

**Comment by JoeyRxy** [comment]
Hi, I think this problem didn't solved, I've encountered this situation in `0.66.0` version!

![img](https://github.com/JoeyRxy/tmp/blob/master/vscode%20issue%20report.png)

![img](https://github.com/JoeyRxy/tmp/blob/master/vscode%20color%20rendering%20report.png)

**Comment by Eskibear** [comment]
@JoeyRxy Can you figure out a way to stably reproduce it? That would be a great help for us to understand the cause and provide a fix.

**Comment by JoeyRxy** [comment]
> @JoeyRxy Can you figure out a way to stably reproduce it? That would be a great help for us to understand the cause and provide a fix.

I think this problem occurs randomly. When you open a java file in a project (maven project most time in my situation), sometimes this problem occurs after you edit something. 

in the pictures above, I just input an `Enter`, then it was broken, until reopening the file or do more editing. I think that's because those action trigger the refreshing or re-rendering action.

[issue-in-vscode](https://github.com/microsoft/vscode/issues/106375)

**Comment by 0dinD** [comment]
@Eskibear I'm pretty sure this is related to #1597, and I don't think it's caused by any of my changes since I've seen it happen occasionally before, in version 0.64 or earlier. I've tried to reproduce it, but it was hard to find any consistent way to do it. See [my comment](https://github.com/redhat-developer/vscode-java/issues/1597#issuecomment-687605420) for what I've been able to find out so far. I'll try to find some steps to reproduce it if I have time next week.

**Comment by lucsoft** [comment]
Semantic highlighting often still goes bad when doing larger refactors in larger files (500 LoC)
![image](https://github.com/redhat-developer/vscode-java/assets/11093382/5b0a99c7-5ee9-4988-bee7-0c88a7118439)

Can't really show code. But i can tell that its a maven eclipse mono repo project with java 17, java module system.

**Comment by 0dinD** [comment]
@lucsoft It turns out that there is a different issue which can still cause the semantic tokens to become desynced (this is probably what you've run into). This is being tracked by #2176.
