### ISSUE TITLE
Highlighting is incorrect after imports are automatically inserted

### ISSUE THREAD

**Issue by EricZhangzf** [redhat-developer/vscode-java#1423]
##### Environment
- Operating System: WIN & MAC
- JDK version: 14 & 11.0.6
- Visual Studio Code version: 1.44.2
- Java extension version: 0.61.0

##### Steps To Reproduce
1.  Create a empty folder and new a .java file in this folder
2.  Type class and type main to generate class and main method
3. Type` File f = new File("Demo.txt");` in main method
4. F1 -> Organize Import will generate `import java.io.File`
5. After import click a whitespace.

##### Current Result
**The string color is incorrect.**
![image](https://user-images.githubusercontent.com/44559777/80694988-d43cae80-8b07-11ea-92cc-39e8e6d0382a.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/44559777/80695028-e3236100-8b07-11ea-8be1-08313abb5fce.png)

**Comment by fbricon** [comment]
Same thing happens if new imports are inserted when selecting a completion proposal that updates imports, eg, typing `Fil` then selecting `File - java.io`

**Comment by alexdima** [comment]
FYI, every other request for semantic tokens fails currently because the java extension returns the semantic tokens as a `number[]` and not as a `Uint32Array`. This heals itself after another edit, then fails again, and so on...

I have pushed https://github.com/microsoft/vscode/commit/468706e8e2e5fd5ccf51ffe58a551e41bd021442 on VSCode's side to now accept also a `number[]` in the implementation, but the best would be to implement the API correctly and give a `Uint32Array`.

**Comment by fbricon** [comment]
@Eskibear can you look into this issue on the server side please?

**Comment by Eskibear** [comment]
Here are two issues. 
1. "java" is not highlighted in `java.*` packages, dup with #1434

2. after pasting code/applying code actions, color of semantic highlighting is not correctly rendered. related to #1421 #1424 . Root cause was just as @alexdima mentioned. The response from language server was deserialized as `number[]` on client side, but vscode's API was requiring a `Uint32Array`. A possible solution is to give a Uint32Array, see PR #1435 .
