### ISSUE TITLE
Semantic highlighting doesn't work after comment or uncomment some codes

### ISSUE THREAD

**Issue by ZhengJun003** [redhat-developer/vscode-java#1424]
Semantic highlighting does not compute after comment or uncomment some codes, but when you enter white space in java file or edited some codes, it will compute and working well.

##### Environment
- Operating System: Win10/Mac 10.15.2/Ubuntu 16.04
- JDK version: 1.8.0_181/11.0.6/14
- Visual Studio Code version: 1.44.2
- Java extension version: 0.61.0

##### Current Result
Comment:
![image](https://user-images.githubusercontent.com/41051257/80695335-5927c800-8b08-11ea-8b55-e2be9bc81ddb.png)

Uncomment:
![image](https://user-images.githubusercontent.com/41051257/80695778-f7b42900-8b08-11ea-87f2-1b125fe9825b.png)

##### Expected Result
Comment:
![image](https://user-images.githubusercontent.com/41051257/80695383-6b096b00-8b08-11ea-93a8-63f639bdadd4.png)

Uncomment:
![image](https://user-images.githubusercontent.com/41051257/80695926-35b14d00-8b09-11ea-92b7-9ea1a6123190.png)

**Comment by alexdima** [comment]
FYI, every other request for semantic tokens fails currently because the java extension returns the semantic tokens as a `number[]` and not as a `Uint32Array`. This heals itself after another edit, then fails again, and so on...

I have pushed https://github.com/microsoft/vscode/commit/468706e8e2e5fd5ccf51ffe58a551e41bd021442 on VSCode's side to now accept also a `number[]` in the implementation, but the best would be to implement the API correctly and give a `Uint32Array`.
