### ISSUE TITLE
Autoclose multiline strings (JEP 368)

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1428]
Typing `"""` should automatically insert a new line, indent the cursor position to below the opening quotes, and finally autoclose with a triple quote
eg:
```java
String foo = """|
```
autocloses/completes to (displaying spaces):
```java
String foo = """
.............|
............."""
```

See https://openjdk.java.net/jeps/368 for more details.

@aeschli any pointers on the best way to achieve that?

**Comment by tommai78101** [comment]
While you're at it, can I request that you enclose the center region of text in a C-style indentation?

```
String foo = """ |
```
will turn into:

```
String foo = """
....|
"""
```
Where the center region's indentation is based on the user-configured indentation size (1, 2, 4, or custom sized indents).

**Comment by rgrunber** [comment]
Maybe something similar to the auto-tag closing in XML ? https://github.com/redhat-developer/vscode-xml/blob/master/src/client/tagClosing.ts#L43

**Comment by snjeza** [comment]
> Maybe something similar to the auto-tag closing in XML ? https://github.com/redhat-developer/vscode-xml/blob/master/src/client/tagClosing.ts#L43

@rgrunber Thanks. I will check it. I'm trying to make a patch for https://github.com/atom/language-java

Related issue - https://github.com/redhat-developer/vscode-java/issues/1264

**Comment by rgrunber** [comment]
The text block feature was finalized in Java 15 (previewed in Java 13). However, we currently have no code to verify that the project JDK meets that minimum requirement. It would certainly complicate the feature a bit since we'd have to get JDT-LS to notify the client of the source compliance (we do something like this for Gradle/Java compatibility) and not only unregister the `handleTextBlockClosing` logic, but also make the `language-configuration.json` dynamic.

Might not be worth going through all of that.

**Comment by snjeza** [comment]
A workspace can contain more projects with a different source compliance.

**Comment by fbricon** [comment]
@rgrunber not worth doing imo
