### ISSUE TITLE
Semantic highlighting doesn't like java.* packages

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1434]
Given 
```java
package foo.bar;

import java.util.List;

public class Test {
    List foo;
}
```
The `java.util.List` has a weird rendering.

<img width="828" alt="Screen Shot 2020-05-05 at 5 50 12 PM" src="https://user-images.githubusercontent.com/148698/81086528-e730f380-8ef8-11ea-8446-8be6d9afba89.png">

**Comment by fbricon** [comment]
@Eskibear can you please look into this one?

**Comment by Eskibear** [comment]
#### Root cause
```
QualifiedName(java.util) 
SimpleName(java) + SimpleName(util)
```
Binding of SimpleName(java) is null, thus the visitor returned early without any token. See [SemanticTokensVisitor.java#L120-L123](https://github.com/eclipse/eclipse.jdt.ls/blob/82b9b2165ab489420010920ae46311e3426c5967/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java#L120-L123) 


A posible solution is to highlight the whole QualifiedName instead of each SimpleName.
