### ISSUE TITLE
Link in javadoc causes an error

### ISSUE THREAD

**Issue by lyh8577** [redhat-developer/vscode-java#1437]
1.  Code comments:  if {@link xxx} has error, the project cannot be started.
2. If dependency:  org.apache.tika:tika-parsers,  import org.xml.sax.SAXException will cause an error. 

##### Environment
- Operating System: Windows 10
- JDK version: Amazon Corretto jdk11.0.6_10
- Visual Studio Code version: 1.45.0
- Java extension version: 0.61.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[demo.zip](https://github.com/redhat-developer/vscode-java/files/4597007/demo.zip)

##### Current Result
![Current Result](https://user-images.githubusercontent.com/16410503/81369341-bd5c1480-9124-11ea-9946-2445c562fbd1.png)

**Comment by fbricon** [comment]
So those are actually 2 bugs from 2 different compilers.

1 - `The "package org.xml.sax" is accessible from more than one module`: this is error is raised by the Eclipse ECJ compiler (https://bugs.eclipse.org/bugs/show_bug.cgi?id=536928), used within vscode-java. The fact it works with javac (and all tools using javac for compiling), is a bug! See https://bugs.openjdk.java.net/browse/JDK-8215739. So eventually, when that's fixed in javac, you'll see the same issue:

One easy fix is to exclude the xml-api dependency, since its classes are now provided by Java 11:
```xml
<dependency>
  <groupId>org.apache.tika</groupId>
  <artifactId>tika-parsers</artifactId>
  <version>1.24</version>
  <exclusions>
    <exclusion>
      <groupId>xml-apis</groupId>
      <artifactId>xml-apis</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

2 - `Missing code implementation in the compiler` is definitely an ECJ bug. I have no workaround for that one, but to not reference this class in the Javadoc

**Comment by fbricon** [comment]
Upstream https://bugs.eclipse.org/bugs/show_bug.cgi?id=562960 was fixed. We should be able to pick up the JDT 2020-06 M3 bits at the end of the month, once it's released

**Comment by fbricon** [comment]
This is now fixed with the latest JDT bits embedded in vscode-java
