### ISSUE TITLE
Extension disables bracket autocomplete

### ISSUE THREAD

**Issue by yizzlez** [redhat-developer/vscode-java#144]
After installing the extension, the auto-insert for "(", or "{" is disabled (previously, if I hit '{', VS Code would automatically insert the corresponding '}'). However, disabling the extension reenables the auto-insert.

##### Environment
- Operating System: OSX 10.12
- Visual Studio Code version: 1.8.1
- Java extension version: 0.0.9

##### Steps To Reproduce
1. Enable extension
2. Type '{', notice that '}' is not automatically inserted

**Comment by fbricon** [comment]
This is a side effect of https://github.com/redhat-developer/vscode-java/commit/1c3a5c25d382c1cbcac0f8038d8b1b5231454784.

It turns out it completely overrides (instead of augmenting) vscode's default java settings.

You can temporarily fix the issue by replacing `/Users/username/.vscode/extensions/redhat.java-0.0.9/language-configuration.json` with:

```json
{
	"comments": {
		"lineComment": "//",
		"blockComment": [ "/*", "*/" ]
	},
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"]
	],
	"autoClosingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""],
		["'", "'"],
		{ "open": "/**", "close": " */", "notIn": ["string"] }
	],
	"surroundingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""],
		["'", "'"],
		["<", ">"]
	]
}
```

I'll open a PR in upstream vscode to add javadoc autoclosing instead.

**Comment by fbricon** [comment]
Commit 199c2bd9e8 restores the proper behavior. 

This is a temporary fix though. Language-configuration.json is expected to be removed once  https://github.com/Microsoft/vscode/pull/19076 is applied and released upstream.
