### ISSUE TITLE
Prompt to switch to standard mode when debugging in Lightweight mode

### ISSUE THREAD

**Issue by quoctruong** [redhat-developer/vscode-java#1516]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version:
- Visual Studio Code version: 1.46.1
- Java extension version: 0.9.1

##### Steps To Reproduce
I was trying to start a remote attach debug session but I got a warning that `Failed to start Debug Server`. Turns out I need to switch to Standard Mode to Lightweight Mode. I think the error message here is confusing. There should be a prompt or an instruction on how to switch to Lightweight Mode.

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Sorry, but debugging is out-of-scope of vscode-java, you need to open a ticket in https://github.com/microsoft/vscode-java-debug/issues. I'm pretty sure the vscode-java-debug team is already aware of this issue, since they were the ones introducing the lightweight mode switch here.
Poke @jdneo, @Eskibear, @testforstephen

**Comment by jdneo** [comment]
It will be available in next release for vscode java debugger: https://github.com/microsoft/vscode-java-debug/pull/838
