### ISSUE TITLE
Intellisense stops working as soon as service is ready

### ISSUE THREAD

**Issue by cranticumar** [redhat-developer/vscode-java#1547]
Intellisense works until Java service is ready. As soon as it is ready Java intellisense stops working

4a87939d Importing root project [Done]
2ed1fa8d Updating Maven Dependencies [Done]
91ca09f2 Repository registry initialization [Done]
fcd77619 Updating indexes [Done]
4fc658f9 Importing root project [Done]
3d229b26 Register Watchers [Done]

Once all above steps are done, it stops working

##### Environment
- Operating System: Windows 10
- JDK version: jdk-11.0.8
- Visual Studio Code version: 1.47.2
- Java extension version: v0.65.0

##### Steps To Reproduce
1. Just open any android based java project (with build.gradle)
2. Intellisense works for first few seconds
3.  Java service starts running,  
4. Once java build completes and says ready, intellisense stops working

6d94f83f Importing root project [Done] 
fe00971a Importing root project [Done]
fb4e62e9 Updating Maven Dependencies [Done]
5227c71d Repository registry initialization [Done]
f30b3509 Updating indexes [Done]
c35d233b Register Watchers [Done]

##### Current Result
Intellisense stops working

##### Expected Result
Intellisense should continue to work

**Comment by snjeza** [comment]
@cranticumar  Could you, please, provide a project example and the [server logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server)?

**Comment by testforstephen** [comment]
See https://github.com/redhat-developer/vscode-java/issues/1390#issuecomment-652302766, android project is not supported at the moment. But you could change the user setting `java.server.launchMode` to `LightWeight` mode to keep partial features available such as `Go to definition`, `Outline`, `Intellisense`, `Hover for Javadoc`.

The Intellisense feature you observed at the first seconds is provided by the LightWeight server, but that server will be shutdown when the Standard server is ready. However, the Standard server won't succeed when importing your android project because of [buildship limitation](https://github.com/redhat-developer/vscode-java/issues/10#issuecomment-268834749).

**Comment by jdneo** [comment]
With the help of https://github.com/eclipse/eclipse.jdt.ls/pull/2197. Android project can be imported now (partially).

Does your problem still exist?
