### ISSUE TITLE
Add java.projectConfiguration.update command to explorer menu, on build files

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#159]
When right clicking on a pom.xml or gradle file, there should be a menu to run the Project Configuration Update command (java.projectConfiguration.update)

**Comment by fbricon** [comment]
Turns out when putting Gradle files into a new gradle language id, syntax coloring is lost, as Gradle files are already associated with the Groovy language. So we definitely need a better way to match files

**Comment by fbricon** [comment]
@jrieken @egamma any advice on how to better handle that one (as opposed to ef178d2)?

**Comment by egamma** [comment]
@fbricon agreed, you should not introduce a new language Id for gradle otherwise you loose the coloring which is defined for the groovy language Id.

There is also a resourceFilename context , e.g.,`"when": "resourceFilename == 'package.json'"`, but I assume you want to contribute the command to `*.groovy`, but wildcards are not supported for the resourceFilename context.

Another option is to optimistically contribute the command to the language Id for groovy
`"when": "resourceLangId == groovy"` and then check in the inside the command for the `gradle` suffix and inform the user that the command only applies to gradle files when it is not a gradle file. Obviously this is not perfect.

**Comment by jrieken** [comment]
Yeah, hard to get this right without making `when`-clauses support some sort of glob pattern matching

**Comment by fbricon** [comment]
@jrieken is there an issue already to get `when` clauses support glob pattern matching? Or I can open one :-)

**Comment by jrieken** [comment]
Go ahead - I was just searching for it but couldn't find anything... Should be pretty straight forward to implement

**Comment by fbricon** [comment]
Issue fixed upstream, so now targeting the mid february release
