### ISSUE TITLE
Spelling error: Update project configuration

### ISSUE THREAD

**Issue by liatbor** [redhat-developer/vscode-java#1649]
Hi,
I'm working on a Java maven project. When opening the context menu on the pom.xml, I get the option 'Update project configuration'. Both 'project' and 'configuration' should start with a capital letter so the command should be: 'Update Project Configuration'
![Screen Shot 2020-10-11 at 8 14 38](https://user-images.githubusercontent.com/1785337/95670915-06b00480-0b9a-11eb-9677-c5dd340c1265.png)

Thanks

**Comment by jdneo** [comment]
😄 Actually this name somehow makes me a little bit confused when I saw it for the first time. IMO, naming it as `Reload Project` or `Refresh Project` conveys the idea more directly.

@rgrunber @fbricon @snjeza @testforstephen @akaroml @Eskibear @CsCherrYY  Do you have any preferences here?

**Comment by rgrunber** [comment]
I think this changed some time ago in [m2e](https://git.eclipse.org/c/m2e/m2e-core.git/commit/?id=03f3b21e013835193841a7f9aae0efaecfae5802). They're basically using `Update Project...` . How do you feel about `Update Project` vs. Refresh/Reload ?

**Comment by jdneo** [comment]
😃  `Update Project` sounds much better! But if must choose one, I guess I'm still a fan of `Reload/Refresh`.

I also found that, in Eclipse, it's called `Update project` for Maven, and `Refresh Gradle Project` for Gradle.

In IntelliJ, it's called `Reload Project` for Maven and Gradle.

**Comment by rgrunber** [comment]
Yes that's fine. FWIW I'm not against Refresh/Reload. I just thought that in a lot of cases, a "Refresh" is simply checking that the contents are synchronized with the filesystem, rather than performing additional steps (eg. Maven goals).

A few other things I noticed (aside from capitalization), though maybe not really needing immediate action :

- `Java: Clean the Java language server workspace` -> `Java: Clean Java language server workspace` . In some cases you can remove some articles/adjectives without losing the meaning.

- `Java: Import Java projects in workspace` -> `Java: Import Java projects into workspace` . 'In' implies the project is located in the workspace, but since we're referring to an action that will move the project so that it will reside in the workspace, we use 'into'.

**Comment by jdneo** [comment]
> a "Refresh" is simply checking that the contents are synchronized with the filesystem, rather than performing additional steps (eg. Maven goals).

I see. That makes sense.

> Java: Clean the Java language server workspace -> Java: Clean Java language server workspace .
> Java: Import Java projects in workspace -> Java: Import Java projects into workspace

Ok
