### ISSUE TITLE
Gradle support not triggered if the gradle wrapper is missing

### ISSUE THREAD

**Issue by sebastian-heinz** [redhat-developer/vscode-java#165]
Installing the plugin, navigating to a build.gradle-file and pressing Cmd+Alt+U on MacOS triggers following warning: "command 'java.projectConfiguration.update' not found"

If a .java-file is opened a message "Classpath is incomplete. Only syntax errors will be reported" appears. But dependencies are downloaded and the thumbs-up appears.

After the thumbs-up appears, going to a build.grade-file and pressing Cmd+Alt+U on MacOS triggers no warning, but has no effect as it seems.

I was hoping it would generate the files necessary to support the project. ( .classpath, .project, .settings )

Am I missing something?

##### Environment
- Operating System: OSX Sierra
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.10.2
- Java extension version:

**Comment by fbricon** [comment]
I'm assuming the command is not available until the java extension finishes loading, since you have no warning after the thumb up shows up.

Do you have the gradle wrapper at the root of your project?

Can you set the `java.trace.server` setting to verbose and see the vscode logs?
Can you look at the java server logs, under ~/Library/Application Support/Code/User/workspaceStorage/${hash}\redhat.java\jdt_ws\.metadata\.log?

**Comment by sebastian-heinz** [comment]
Hello,

Thank you for the fast response.
I'm sorry, I did not have the gradle wrapper in version control, and a fresh clone did not include it.
After ensuring the gradle wrapper is present, everything seems to be working.

**Comment by fbricon** [comment]
Ok, I need to make sure plain gradle works then

**Comment by ItachiSan** [comment]
Having the same issue.

**Comment by fbricon** [comment]
so I checked the java extension already supports wrapper-less projects. Could you share a sample project that reproduces the problem?

**Comment by sebastian-heinz** [comment]
Hello,

I'm sorry I haven't been able to create a sample project yet, but the issue only appears to happen if you open a folder which contains multiple projects. (and not a build.gradle at top level?)

the following structure caused the issue of my report:
/MyProject
/MyProject/A/ (build.gradle & settings.gradle)
/MyProject/B/ (build.gradle & settings.gradle)

I opened the folder 'MyProject' in VsCode and then open the subfolders to get to the 'build.gradle'-file, this would cause the problem described in the initial report. If I open the folder 'A' in VsCode, it will generate all the necessary files.

**Comment by fbricon** [comment]
Ah right, that rings a bell :-) Indeed, the Gradle integration currently only looks at the root folder, as opposed to the Maven integration. The reason behind that is m2e (responsible for the Maven support) requires explicit discovery of all the pom.xml in the folder hierarchy, in order to import those projects. On the other hand, Buildship (responsible for the Gradle integration), can discover all child modules from build/settings.gradle files at the root of a directory, so it wouldn't make sense to try to search for more build files. 

Maybe defining a [composite build](https://blog.gradle.org/announcing-buildship-2.0) at the root of MyProject would be helpful.

**Comment by ItachiSan** [comment]
I did have the issue even without the multiple project build.
Unluckily I am really busy, so I will report in a good way my situation ASAP
