### ISSUE TITLE
search for enum reference without source

### ISSUE THREAD

**Issue by clembo590** [redhat-developer/vscode-java#1665]
Vscode does not find references on Enum when it does not have the source.

##### Environment
- Operating System: mac os 10.14.6 (18G103)
- JDK version: jdk-11.0.4.jdk
- Visual Studio Code version: Version: 1.50.1
- Java extension version: v0.69.0

##### Steps To Reproduce
0.  clone my repo [https://github.com/clembou590/vscodeissue](https://github.com/clembou590/vscodeissue)
1. then in terminal go to folder named 'first' and run 'mvn clean install'
2. open a "vscode workspace" that contains ONLY folder named second. (THIS IS IMPORTANT OTHERWISE THERE IS NO BUG)
3. open file SecondApplication.java then on `MySharedEnum.VSCODE;` do F12 _(go to definition)

--> FIRST ISSUE:
When trying to search references for VSCODE(0) nothing is found (even though the enum VSCODE is used in SecondApplication.java ) 

--> SECOND ISSUE:
the values are incorrect 
on the left vscode should not show VSCODE(0) but VSCODE(2)
<img width="1920" alt="Screenshot 2020-10-21 at 17 29 58" src="https://user-images.githubusercontent.com/10899818/96743445-4cec3b80-13c4-11eb-9acf-70af62f8ab23.png">

**Comment by clembo590** [comment]
anyone ... ?

**Comment by clembo590** [comment]
Hello @snjeza any update on this ?

**Comment by snjeza** [comment]
> --> SECOND ISSUE:
the values are incorrect
on the left vscode should not show VSCODE(0) but VSCODE(2)

This issue is an upstream Eclipse/Java decompiler issue. You can try https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler

> :--> FIRST ISSUE:
When trying to search references for VSCODE(0) nothing is found (even though the enum VSCODE is used in SecondApplication.java )

This is a Java LS issue. I will try to fix it.
