### ISSUE TITLE
Preview features enabled at an invalid source release level 14, preview can be enabled only at source level 15

### ISSUE THREAD

**Issue by mojo2012** [redhat-developer/vscode-java#1685]
[provide a description of the issue]

##### Environment
- Operating System: 10.15.7 (19H2)
- JDK version: openjdk version "14.0.2" 2020-07-14
- Visual Studio Code version: 1.50.1
- Java extension version: v0.69.0

##### Steps To Reproduce
1. Checkout https://github.com/mojo2012/java15_preview_features_demo.
2. set java 14 as your default
3. run `mvn clean install` -> it works
4. open in vscode
5. clean language server workspace
6. force java compilation

##### Current Result
error message in problems tab is shown:
```
Preview features enabled at an invalid source release level 14, preview can be enabled only at source level 15
```
And file is marked red.

##### Expected Result
No problems are shown

##### Additional Informations
As soon as one of the classes containing problems is opened, the error message goes away and it not marked red anymore!

[language_server.log](https://github.com/redhat-developer/vscode-java/files/5458838/language_server.log)
[syntax_server.log](https://github.com/redhat-developer/vscode-java/files/5458839/syntax_server.log)
![Bildschirmfoto 2020-10-29 um 14 49 04](https://user-images.githubusercontent.com/1330361/97590123-965d0c00-19fe-11eb-84e0-68502c4b03c5.png)

**Comment by testforstephen** [comment]
This is a fair concern, but due to the limitation of the upstream jdt, this is not supported. The reason is vscode-java@0.69.0 is using the latest Eclipse Compiler for Java (ECJ), which is a Java 15 compiler, to compile your project.  It doesn't allow to enable preview when compiling 14 project. See more discussion at the upstream issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=549258.

You have to remove enable-preview flag in your pom.xml, or migrate the compiler version to 15.
