### ISSUE TITLE
[Question] Default Java formatter line length 

### ISSUE THREAD

**Issue by StelFoog** [redhat-developer/vscode-java#1709]
I've noticed that the default Java formatter (JSON "java.format.enabled": true) forces lines to be no longer than 80 characters. I can't seem to find any setting to change this to my own preferred length.

settings.json
```
{
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terminal.integrated.shell.osx": "/bin/bash",
    "editor.rulers": [
        100
    ],
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 100,
}
```

##### Environment
- Operating System: macOS 10.14.1
- JDK version: openJDK 15.0.1
- Visual Studio Code version: 1.51.1
- Java extension version: 0.70.0

##### Steps To Reproduce
1. Enable Default Java formatting
2. Format file

##### Current Result
Formats all lines in file to be no longer than 80 characters.

##### Wanted Result
For lines to be formatted to my preferred length

**Comment by alinnert** [comment]
Has the default length been changed? I wish it was 80 characters but it seems it's 121 for me. Maybe the semicolon doesn't count. Then it would make sense. I'd also appreciate a setting for this.

**Comment by alinnert** [comment]
Okay, I found out that this is already possible. There are two commands (I don't know where exactly they are coming from, but I have the "Java Extension Pack" from Microsoft installed):

- Java: Open Java Formatter Settings
- Java: Open Java Formatter Settings with Preview

I've used the "with Preview" one which provides a settings GUI. When first using it you get asked to create a file called `eclipse-formatter.xml`. Choose "yes" and you can change some settings.

There's a settings group called "Wrapping" where you can change the "Maximum line width". This actually changed how the formatting command formats my Java code.

![image](https://user-images.githubusercontent.com/2638971/123546738-2b66ff00-d75e-11eb-8884-d854d2707e5c.png)

**Comment by jdneo** [comment]
douira, you need to install this extension:https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

**Comment by rgrunber** [comment]
I'm not sure if all formatter options are included, and since it can be tricky to create a custom formatter file, you can always use a formatter option key-value pair and place it directly in the `java.settings.url` (normally used for compiler options). I've documented this at https://github.com/eclipse/eclipse.jdt.ls/wiki/Language-Server-Settings-&-Capabilities#java-formatter-options . All formatter options can be found at https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html .

As an example : 

**.vscode/settings.json**
```
{
	"java.settings.url": ".vscode/settings.prefs"
}
```

**.vscode/settings.prefs**
```
org.eclipse.jdt.core.formatter.lineSplit=80
org.eclipse.jdt.core.formatter.comment.line_length=80
```
(Note that for lineSplit the default is 120, and for comment.line_length, it is 80, so just included for awareness)

As we do have support, I'll close this, and just make the documentation a bit more visible.
