### ISSUE TITLE
semantic tokens: use 'method' instead of 'member'

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#1713]
After requests in https://github.com/microsoft/language-server-protocol/issues/1087 we decided to deprecate the 'member' token type in favor of a new 'method' token type.

The 'method' token type stands for all types of member functions (also if the language calls it differently)

**Comment by aeschli** [comment]
VSCode issue: https://github.com/microsoft/vscode/issues/111172

**Comment by 0dinD** [comment]
The semantic token for methods was never even renamed to `member` (from `function`), since I was waiting for your response to microsoft/language-server-protocol#1087. But now that everything is cleared up, I think it's time for a rename.

**Comment by 0dinD** [comment]
BTW, merging eclipse/eclipse.jdt.ls#1608 will break styling of `method` tokens (unless explicitly styled) until microsoft/vscode@07d680b makes it into a release, since they currently are not mapped to any TextMate scope. This could be fixed by contributing more scope mappings like in #1636, for `method` tokens. But I'm not sure if it's a good idea since the scope mapping will eventually be provided by microsoft/vscode@07d680b. We could wait until we can specify the version dependency in the package.json of vscode-java, but I'm not sure if it matters for a small syntax highlighting fix like this. I'll let whoever reviews/merges eclipse/eclipse.jdt.ls#1608 decide which route to take.

**Comment by aeschli** [comment]
Yes, you better wait until 1.52 is out (or restrict the extension to 1.52)

**Comment by fbricon** [comment]
@testforstephen what's the status on this one?

**Comment by testforstephen** [comment]
Since 1.52 is out for a while, we can move forward with pull request https://github.com/eclipse/eclipse.jdt.ls/pull/1608 to address this issue.

**Comment by testforstephen** [comment]
thanks @0dinD, this has been fixed by https://github.com/eclipse/eclipse.jdt.ls/pull/1608
