### ISSUE TITLE
Feature request: add setting of disable error Squiggles

### ISSUE THREAD

**Issue by hongguifeng** [redhat-developer/vscode-java#1733]
Just like C_Cpp, add a setting to disable error Squiggles.

**Comment by testforstephen** [comment]
There is a user setting `java.autobuild.enabled` to turn off auto build. Would that help you?

**Comment by hongguifeng** [comment]
> There is a user setting `java.autobuild.enabled` to turn off auto build. Would that help you?

@testforstephen Thanks, but it doesn't seem to work. I have some Android code, vscode indicates "xxx cannot be resolved to a type" on Android API, I want to ignore them.

**Comment by testforstephen** [comment]
The Java tooling cannot resolve some android dependencies well due to [a known limitation](https://github.com/redhat-developer/vscode-java/issues/10#issuecomment-268834749). If what you want is just to get rid of these unresolved type errors, you may have a try at LightWeight mode through user setting `"java.server.launchMode": "LightWeight"`. Lightweight mode won't report the semantic errors such as unresolved type. [👉Click me](https://code.visualstudio.com/docs/java/java-project#_lightweight-mode) to learn more about LightWeight mode.

**Comment by hongguifeng** [comment]
@testforstephen Thanks, it works. But LightWeight mode seems too light, I can't even use the "Go to definition" ...

**Comment by testforstephen** [comment]
The LightWeight mode will support partial "Go to definition" such as definitions from your sources and JDKs. It will skip all third party dependencies.

**Comment by hongguifeng** [comment]
Found a temporary solution that change the squiggles color.
```
"workbench.colorCustomizations": {
	"editorError.foreground":   "#00000000",
},
```
