### ISSUE TITLE
.classpath file is not updated with new JDK version

### ISSUE THREAD

**Issue by mojo2012** [redhat-developer/vscode-java#1748]
I just updated to java 15 and increased the version from 14 to 15:
```xml
<java.version>15</java.version>
<maven.compiler.target>15</maven.compiler.target>
<maven.compiler.source>15</maven.compiler.source>
```

The eclipse .classpath file was not properly updated though. It still contained this:

```xml
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-14">
```

The java version stays on the old value.

##### Environment
- Operating System: macOS 11.1
- JDK version: JDK 15
- Visual Studio Code version: 1.52.1
- Java extension version: 0.73.0

##### Steps To Reproduce
1. setup a maven project with JDK level 14 in eclipse
2. open the workspace in vscode
3. update the pom.xml to a newer java version

##### Current Result
The .classpath file is not updated (only when at least once run in eclipse again).

##### Expected Result
The .classpath file is updated the same way eclipse would do it.

**Comment by fbricon** [comment]
Normally, when you change your pom.xml, you should see:
<img width="652" alt="Screenshot 2020-12-27 at 18 45 21" src="https://user-images.githubusercontent.com/148698/103176636-b3358480-4873-11eb-8c02-2a307b7caa25.png">

If you selected "Never", it won't update the JDT configuration automatically. You need to choose "Always", so that updates can be performed automatically.

This translates to "java.configuration.updateBuildConfiguration": "automatic" in your settings.json

**Comment by fbricon** [comment]
Anyways, you can always manually trigger a configuration update with the "Update Configuration" command. Either ran from the command palette, or when right-clicking on a pom.xml:
<img width="678" alt="Screenshot 2020-12-27 at 18 54 45" src="https://user-images.githubusercontent.com/148698/103176795-268bc600-4875-11eb-98a3-cea4da241377.png">

**Comment by mojo2012** [comment]
My setting is set to "automatic". But I didn't try the "update project" command - thanks for that.

**Comment by mojo2012** [comment]
Worked!
