### ISSUE TITLE
Java formatter is not working.

### ISSUE THREAD

**Issue by Abhiraj3112000** [redhat-developer/vscode-java#1794]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Care to elaborate?

**Comment by phillip-urioste-chs** [comment]
It suddenly stopped working for me too. It was pointing to the eclipse formatter.xml and was working fine, but after the latest update no longer formats as per the rules in my formatter.xml

**Comment by JesseBrault0709** [comment]
I am having the same issue as @phillip-urioste-chs. My eclipse formatter.xml file was working great, then stopped working after the most recent update (either of VSCode or the java extension, I am not sure which update caused the issue).

Operating system: Mac os 10.12.6
JDK: openjdk 15 2020-09-15
VSCode version: Version: 1.54.1
Redhat java extension: 0.76.0

**Comment by snjeza** [comment]
@Abhiraj3112000 @JesseBrault0709 @phillip-urioste-chs could you show your java.format.settings.url property?

**Comment by JesseBrault0709** [comment]
I figured it out. I previously had something like: `/some/path/to/formatterProfile.xml`

Switching it to a proper URL syntax such as: `file:///some/path/to/formatterProfile.xml` seems to be solving the issue. Since the description in the settings panel currently reads 'Specifies the url _or file path_' (emphasis mine), I had assumed that just a plain old file path would work (and I believe it previously did work that way).

**Comment by snjeza** [comment]
Related issue - https://github.com/eclipse/eclipse.jdt.ls/issues/1685

**Comment by jonathanklingberg** [comment]
Sorry but this issue wasn't resolved by adding the file:// prefix to the file URI.
I had to downgrade to v0.69.0 in order to get the formatting back to a working state.

Environment
Operating System: MacOS 11.2.3
JDK version: adoptOpenJDK openjdk64-11.0.11
Visual Studio Code version: 1.55.2
Java extension version: 0.79.1
Steps To Reproduce
- Connected to this documentation; https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings
- Download the Google formatter; https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml
- Add the following settings;
`"java.format.settings.url":` "file:///some/path/to/eclipse-java-google-style.xml",`
`"java.format.settings.profile": "GoogleStyle",`
- Restart VS Code
- Format java code
- Make some adjustments to the formatter xml configuration and format the code again
- Note how the changes aren't applied

**Comment by snjeza** [comment]
@jonathanklingberg Please check https://github.com/redhat-developer/vscode-java/issues/1917#issuecomment-830652380
