### ISSUE TITLE
Can we import IntelliJ java projects into VS Code???

### ISSUE THREAD

**Issue by raghav-kranthi** [redhat-developer/vscode-java#191]
I am trying to import one of my IntelliJ java projects into my VS Code, every time it is displaying same error
"**classpath is incomplete. only syntax errors will be reported visual studio code**"
I have opened complete project which contains .iml file, not a single java file.
It is not a gradle, maven, ant build project plain old java project developed in IntelliJ
I am using Mac Sierra with JDK 1.8
My JAVA_HOME is already set
I have tried almost every solution provided in google. unfortunately, there is no proper support for VS Code issues.

I would really appreciate if someone could help me in coming out of this rabbit hole!!!!!

**Comment by gorkem** [comment]
We have not yet implemented importing IntelliJ projects. I think the workaround is to import/convert the IntelliJ project to one of the supported formats and continue form there.

**Comment by raghav-kranthi** [comment]
Thanks for the quick response, I will try creating a new project and copying the content.

**Comment by rustyx** [comment]
@gorkem is this feature on a to-do list? It would help immensely to have `.iml` files recognized and imported, at least the parts related to the classpath.
A good example project to try is [Selenium](https://github.com/SeleniumHQ/selenium).

**Comment by justas2481** [comment]
I wonder does this problem still persists? I'm planning to take Java as another programming language to add it as another skill, but since I'm blind, my consideration is whether I'll have any problems to load projects which are used / written by other co-workers in IntelliJ which is lacking in case of accessibility behind by far incomparison to VSCode which does amazing job there.
VSCode has really accessible tools for Java as well as for other programming languages, but if I'll have problems to load projects to be able to code with my co-workers, then that I'd love to know because it is a risk.
