### ISSUE TITLE
How to set limit-modules in vmargs?

### ISSUE THREAD

**Issue by borko-rajkovic** [redhat-developer/vscode-java#1972]
When I set `--limit-modules=java.base` in `java.jdt.ls.vmargs` I get error message:

`Language Support for Java crashed 5 times in the last 3 minutes`

##### Environment
- Operating System: Ubuntu 20.04
- JDK version: OpenJDK 11
- Visual Studio Code version: 1.56.2
- Java extension version: 0.79.2
- Java Debugger extension version: 0.34.0

##### Steps To Reproduce
1. In settings.json add new entry `"java.jdt.ls.vmargs": "--limit-modules java.base",`
2. Restart VS Code

Sample project:

https://github.com/borko-rajkovic/limit-modules-vmargs-issue

##### Current Result

Language Support for Java server crashes

##### Expected Result

Language Support for Java server should not crash

##### Additional Informations

I need to pass `limit-modules` option to vmargs in order to resolve this issue:

https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/53824670#53824670

In a sample project I have dependency to:

https://mvnrepository.com/artifact/org.cassandraunit/cassandra-unit-spring/3.11.2.0

Since I need to use Java 11 for other project and this dependency, I get error:

```
java.util
The package java.util is accessible from more than one module: <unnamed>, java.base Java(8390063)
```

So, I wanted to resolve this problem using `--limit-modules=java.base` on vmargs in settings

**Comment by fbricon** [comment]
vmargs are options set to run the Java Language Server providing Java support in vscode-java. You definitely don't want to prevent it from using the java.base module.

What you're facing is caused by the high-scale-lib library (an unnamed module in the JPMS sense) reimplementing java.util classes. Having several modules contributing the same package is forbidden by JPMS. Your best bet is to exclude high-scale-lib from cassandra-unit-spring's transitive dependencies in your build.gradle: 
```groovy
    compile('org.cassandraunit:cassandra-unit-spring:3.11.2.0') {
		exclude module: 'high-scale-lib'
	}
```

See https://stackoverflow.com/questions/59118223/problem-with-eclipse-when-using-java-11-and-cassandra-spring-unit-possibly-along
