### ISSUE TITLE
Improve semantic highlighting

### ISSUE THREAD

**Issue by BlueStaggo** [redhat-developer/vscode-java#2006]
I would like it if these two things were changed (based off Dark+):
1. Constructors should be the colour of classes (sea green). *Currently: Colour of methods (light yellow).*
2. Primitive types (and `var`) should be the colour of keywords (dark blue). *Currently: Colour of classes (sea green).*
3. The `new` keyword should be the colour of keywords (dark blue). *Currently: Colour of control keywords (pink).*
4. Ternary operators should be the colour of operators (white). *Currently: Colour of control keywords (pink).*
    - Same applies with colons on cases in `switch` statements.

My goal with Java's semantic highlighting is to make it look like C# and make things look cleaner. Here's a comparison between the two programming languages:

Token|C#|Java
-|:-:|:-:
Primitive type|![image](https://user-images.githubusercontent.com/71090710/123549471-1b9cea00-d761-11eb-901d-06c0c76ce13c.png)|![image](https://user-images.githubusercontent.com/71090710/123549474-2192cb00-d761-11eb-800b-5ffced3384b2.png)
Constructor|![image](https://user-images.githubusercontent.com/71090710/123549503-45eea780-d761-11eb-89ef-c32587698229.png)|![image](https://user-images.githubusercontent.com/71090710/123549532-69b1ed80-d761-11eb-871d-06788326ae1f.png)
`new` & constructor|![image](https://user-images.githubusercontent.com/71090710/123549576-9f56d680-d761-11eb-8513-b40f8e77a882.png)|![image](https://user-images.githubusercontent.com/71090710/123549558-949c4180-d761-11eb-938c-dc70993bbcc4.png)
Ternary operators|![image](https://user-images.githubusercontent.com/71090710/123549747-358afc80-d762-11eb-8606-1466bb8526a3.png)|![image](https://user-images.githubusercontent.com/71090710/123549733-273ce080-d762-11eb-828f-150fb296fded.png)
Colons after cases|![image](https://user-images.githubusercontent.com/71090710/123549909-e6919700-d762-11eb-8192-a6932e91163d.png)|![image](https://user-images.githubusercontent.com/71090710/123549919-edb8a500-d762-11eb-9b64-8cf572d2dc1c.png)

I don't know how to add in grammars, so I'll rely on existing contributors to do this. I'll add to this list if I find anything else.

**Comment by Eskibear** [comment]
Thank you for your feedback. Here to clarify two sources of highlighting:
**semantic** highlighting provided by [JDT language server](https://github.com/eclipse/eclipse.jdt.ls), semantic tokens like variables, types, names are highlighted based on AST.
**syntax** highlighting is the fallback, provided by https://github.com/atom/language-java/blob/master/grammars/java.cson , keywords, punctuations are also highlighted based on regular expression.

About above issues you mentioned, you can inspect tokens via below command:
![image](https://user-images.githubusercontent.com/2351748/123571795-93205700-d7fd-11eb-8fb9-85dd8da12066.png)

- [**syntax**] primitives are correctly highlighted, using `storage.type.primitive.java` scope
- [**semantics**] constructors are correctly highlighted as `method` token, using `entity.name.function.member` scope
- [**syntax**] `new` is a keyword, precisely highlighted, using `keyword.control.new.java` scope.
- [**syntax**] ternary operators. `?` and `:` are keywords of the operator, precisely highlighted, using `keyword.control.ternary.java` scope.
- [**syntax**] colons after cases are also treated as keywords.


> My goal with Java's semantic highlighting is to make it look like C# and make things look cleaner

Our goal is to provide first-class language support for all kinds of Java developers. What we are doing it to make sure tokens are correctly mapped to textmate scopes, so that theme authors can correctly colorize them. It doesn't have to look like C#. 
If you prefer to have fewer colors, you can either look for another theme, or override current theme via setting  `editor.tokenColorCustomizations` by your own.

**Comment by BlueStaggo** [comment]
I already knew about `editor.tokenColorCustomizations`, but I didn't manage to change `var` and constructors. Are those impossible to change? You can leave this closed if you feel like it.

**Comment by Eskibear** [comment]
For `var`, semantics and syntax hightlighting have different result. In syntax highlighting it's a "local type". In semantic highlighting it's a "class". Personally I regard it more as a "keyword", and we can discuss on it.

![image](https://user-images.githubusercontent.com/2351748/123836923-d46b5080-d93c-11eb-9818-cab1c981bc7c.png)

For constructors, both semantics and syntax highlight them as `function`, which we think is correct. And yes, for the moment semantic highlighting cannot distinguish contructors from other member methods, as they have the same token type and modifiers.

For others you mentioned above, themes are responsible for colorization. LS already provides correct tokens, and I don't find any mistakes in there.
