### ISSUE TITLE
support inlay hints

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2099]
It's available in IntelliJ IDEA,
https://www.jetbrains.com/help/idea/inlay-hints.html

Supported in TS/JS since vscode v1.60 
![image](https://user-images.githubusercontent.com/2351748/132154259-4d47251d-3945-4fec-9ca7-3c8715d150de.png)
See: https://code.visualstudio.com/updates/v1_60#_inlay-hints-for-javascript-and-typescript

Proposed API in VS Code:
https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/src/vs/vscode.proposed.d.ts#L1773-L1793

LSP proposal: 
https://github.com/microsoft/language-server-protocol/issues/956

**Comment by rgrunber** [comment]
It's also supported in Eclipse since 4.12 (2019-06) https://www.eclipse.org/eclipse/news/4.12/jdt.php#parameter-name-codemining.

https://git.eclipse.org/c/gerrit/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/CalleeJavaMethodParameterVisitor.java

I don't think we can use the class since it's in UI and ICodeMining is tied to some UI rendering elements. However the AST logic is pretty straightforward.

**Comment by jayy2kok** [comment]
I have adopted VS Code for full time java IDE, I love it, just this one feature I am missing.

**Comment by rgrunber** [comment]
I think we should watch out for things like https://bugs.eclipse.org/bugs/show_bug.cgi?id=568844 , and maybe look at possible solution. The jumpiness is caused when a method temporarily can't be resolved to a proper signature (due to syntax error?) and then switches to resolved. The effect is annotations flickering which affect the user's ability to type.

**Comment by jdneo** [comment]
Update: inlay hint is available as client side API in VS Code 1.65.0.

Maybe we can first make a client side implementation. I can volunteer for that. :)
