### ISSUE TITLE
Option to disable highlighting of TODO comments

### ISSUE THREAD

**Issue by MiguelGuthridge** [redhat-developer/vscode-java#2145]
When I put a TODO in a comment in a Java file, the Java extension highlights it with a squiggly underline.
As I have a dedicated todo-highlighter extension which suits my needs far better, I'd like to disable the underlining of these comments.
I've looked, but I can't find anything in the settings to disable this. Could a setting for it be added?

##### Environment
- Operating System: Windows 10
- JDK version: 11.0.12
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0

##### Steps To Reproduce
1. Add a comment in a Java file, such as `// TODO: Something` or `// FIXME: Something else`
2. Observe that a blue underline appears on the comment.

##### Current Result
See above

##### Expected Result
See above

**Comment by 0dinD** [comment]
There's no VS Code setting for it, but it can be tweaked via [Eclipse preferences](https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences), using the [task tags preference](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2FJavaCore.html&anchor=COMPILER_TASK_TAGS). If you don't want any task tags, insert the following into your `.prefs` file:
```
org.eclipse.jdt.core.compiler.taskTags=
```

**Comment by MiguelGuthridge** [comment]
That did work, but it is quite convoluted. A dedicated setting for it would honestly be nice.

**Comment by 0dinD** [comment]
Agreed, but the same could be said for many other Eclipse preferences, and it's tedious work to manually create dedicated settings for them.

I think an alternative solution might be added via eclipse/eclipse.jdt.ls#1765, but @rgrunber would have to confirm whether or not task tags can be ignored.

**Comment by rgrunber** [comment]
The task tags show an information marker (blue squiggles) so that they're visible in the problems view, as well as from the scrollbar of an opened file. The nice part is being able to view a list of all "TODO" items in a project. I also notice our listing of options in the preference wiki doesn't list it, so I'll look into fixing that.

The PR you mention is the more general issue that we need to provide a more discoverable way to disable such warnings (https://github.com/redhat-developer/vscode-java/issues/1791). I'll have a look again at what you've proposed on the PR.

**Comment by 0dinD** [comment]
> The task tags show an information marker (blue squiggles) so that they're visible in the problems view, as well as from the scrollbar of an opened file. The nice part is being able to view a list of all "TODO" items in a project.

Right, but the point of this issue is that some users have dedicated TODO extensions like [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), so they would like to disable the task tag highlighting from this extension (in order to avoid the clutter of duplicate TODO highlights). And since task tags are diagnostics just like errors and warnings, I was thinking maybe eclipse/eclipse.jdt.ls#1765 would provide a code action to disable the task tags.

**Comment by rgrunber** [comment]
> > The task tags show an information marker (blue squiggles) so that they're visible in the problems view, as well as from the scrollbar of an opened file. The nice part is being able to view a list of all "TODO" items in a project.
> 
> Right, but the point of this issue is that some users have dedicated TODO extensions like [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), so they would like to disable the task tag highlighting from this extension (in order to avoid the clutter of duplicate TODO highlights). And since task tags are diagnostics just like errors and warnings, I was thinking maybe [eclipse/eclipse.jdt.ls#1765](https://github.com/eclipse/eclipse.jdt.ls/pull/1765) would provide a code action to disable the task tags.

Agreed. If we can figure out that the property accepts a set of values (as opposed to enabled/disabled), then we can certainly define our "Ignore this option" code action to set it empty.

**Comment by rgrunber** [comment]
Given that there is a workaround, and that we'll make progress on this in https://github.com/eclipse/eclipse.jdt.ls/pull/1765 , I'll mark this as a duplicate.
