### ISSUE TITLE
Java language Server fails to start when some other Java applications are starting

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-java#2158]
[provide a description of the issue]

##### Environment
- Operating System: Fedora 34
- JDK version: Java 16
- Visual Studio Code version: 1.60
- Java extension version: 0.82

##### Steps To Reproduce
1. Install vscode-java and [VS Code AtlasMap](https://marketplace.visualstudio.com/items?itemName=redhat.atlasmap-viewer) (built from this [branch](https://github.com/apupier/vscode-atlasmap/tree/50-UseEditorInsteadOfSeparateWebview-reproducerBranch) for now, provided the vsix [here](https://drive.google.com/file/d/12In7cXRbWPQvOb51BIU3jpR7LAP-5QE5/view?usp=sharing))
2. Open a folder with some Java files and a .adm file, for instance https://github.com/atlasmap/atlasmap/tree/master/examples/camel-example-atlasmap
3. Open the .adm file
4. Close VS Code
5. Start VS Code
6. The Java language server fails to start

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

client log extract:
```
{
  message: 'ERROR: transport error 202: bind failed: Address already in use\n' +
    'ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)\n' +
    'JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]\n',
  level: 'info',
  timestamp: '2021-10-11 13:10:14.053'
}
{
  message: 'The Language Support for Java (Syntax Server) server crashed 5 times in the last 3 minutes. The server will not be restarted.',
  level: 'error',
  timestamp: '2021-10-11 13:10:14.056'
}
{
  message: '[Error - 1:10:14 PM] Connection to server got closed. Server will not be restarted.',
  level: 'info',
  timestamp: '2021-10-11 13:10:14.058'
}
```

##### Current Result

java Laguage Serve fails to start

##### Expected Result

Java language Server can start.

##### Additional Informations

VS Code Atlasmap is starting a SpringBoot Java application. it is configured to use whatever port is available. During development, a specific port was provided and both Java Language Server and AtlasMap Server were failing to start with adress already in use despite different http port provide.

**Comment by rgrunber** [comment]
I tried reproducing as you listed above, but am not able to. When you install the vscode-java extension as a visx, it shouldn't attempt to bind to any ports. If you try to provide a port to bind through `java.jdt.ls.vmargs` it is going to fail because hybrid-mode is the default so it'll launch both syntax+standard servers passing the vmargs to both processes (attempting to bind to same port) :rofl: . Did you launch vscode-java in a child instance when the sources were loaded ? That method can be very prone to the error you listed above because it binds to ports by default (for convenience).

Another thing you can do to test is use something like `jps -lv` to see which processes are bound to certain ports (if we're talking debug ports). Might also be worth monitoring the atlasmap extension (and other Java processes) with `watch -n1 -d 'jps -lv | grep -v jps'` to see if they persist beyond what's expected.
