### ISSUE TITLE
Auto-escaping of the text after copy-pasting in String literal

### ISSUE THREAD

**Issue by sogawa-sps** [redhat-developer/vscode-java#2169]
Many modern IDEs provide an auto-escaping functionality. I.e. when one pastes a text into a String literal escape symbols are being placed where necessary, newlines are being transformed into "\n" etc. It seems vscode-java doesn't have this functionality what is a pretty big disadvantage.

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.61.1
- Java extension version: 0.82.0

##### Steps To Reproduce
1. Write a line:
`String path = "";`
2. Paste the following text inside the double quotes: 
`C:\Temp\Test\`

##### Current Result
`String path = "C:\Temp\Test\";`

##### Expected Result
`String path = "C:\\Temp\\Test\\";`

**Comment by rgrunber** [comment]
Agreed. I think we could easily do this in https://github.com/redhat-developer/vscode-java/blob/master/src/pasteAction.ts for now. It would of course only work for VS Code since it's not in the language server itself. I don't think the LSP spec has a way to detect whether a text change is occurring due to a paste.

With that said, I also noticed https://github.com/microsoft/language-server-protocol/issues/767 which would be nice in the future.
