### ISSUE TITLE
Mac os, It takes 5 minutes when i open a java project to build it

### ISSUE THREAD

**Issue by WhiteSte** [redhat-developer/vscode-java#2191]
[provide a description of the issue]
Hi, when i open a java project, it takes 5 minutes to load it into visual studio in the left corner. It's like every time I re open the same project, it re build again
##### Environment
- Operating System: last mac os 
- JDK version:11
- Visual Studio Code version:last
- Java extension version: last

##### Steps To Reproduce
1. [step 1] Open a java project

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by 0dinD** [comment]
@WhiteSte overall it sounds like it would be a better idea to include these files separately (given how large they are), or put them in the JAR file after you've compiled the code (I assume a JAR file is what you mean when you say you want something "shareable"). What if you want to share a new version of your program, but the data files haven't changed? Sitting through a 40-50 GB download when only a small part of the program has actually been updated might be annoying.

With that said, you could exclude the files from your workspace by setting an exclusion filter with the `java.project.resourceFilters` setting, which should solve your issue.

**Comment by 0dinD** [comment]
Right, I see now. If you exclude the files with `java.project.resourceFilters`, they will not be copied to the output folder where the compiled `.class` files are stored, which means you can't access them via the class loader. But as long as they are still somewhere on your disk you could still access them using normal file I/O APIs. At that point though I would probably just put them outside of your `src` folder instead of using `java.project.resourceFilters`. 

> I need a setting that doesn't load everytime the same data into the java language server, but if they change it notice that and load new data into visual studio.

I see what you mean now, but I don't think this is possible without big changes to the upstream Eclipse libraries (unless you know this feature exists in the Eclipse IDE). Any files you want on your classpath have to be in the output folder. Java source files get compiled there, resources (like your files) get copied there. The question is whether you really need these files to be on your classpath? They could still be in the same repository/project as your source files, and then you can use relative paths to reference the files when you run the program.

If this doesn't work for you, I'm curious how you expect it to work when building a project?

**Comment by WhiteSte** [comment]
so if I drag them out from src folder I should not get this problem again? I will try tomorrow

**Comment by 0dinD** [comment]
Yes, that should work as long as the folder you drag them into is not also a source folder. If you have the Project Manager for Java extension installed you can see the source folders [in the projects view](https://code.visualstudio.com/docs/java/java-project#_project-view).
