### ISSUE TITLE
We need suport for OSGi and Equinox

### ISSUE THREAD

**Issue by jiangyubao** [redhat-developer/vscode-java#2194]
[provide a description of the issue]

##### Environment
- Operating System: Macos
- JDK version: jdk 1.8
- Visual Studio Code version: 1.61.2
- Java extension version: 1.0.0

VSCode is very convenient to write JAVA code based on Maven or Gradle. I like it very much. However, I have many OSGi  projects , which are written based on eclipse and run upon Equinox. Can VSCode support OSGi and Equinox? We need!

**Comment by snjeza** [comment]
You may want to take a look at
- https://github.com/eclipse/eclipse.jdt.ls/pull/305
- https://github.com/eclipse/eclipse.jdt.ls/pull/396
- https://github.com/gorkem/jdt.ls.pde/
- https://github.com/testforstephen/vscode-pde

**Comment by testforstephen** [comment]
Yes, it's supported by an additional extension https://marketplace.visualstudio.com/items?itemName=yaozheng.vscode-pde. Currently we ourselves leverage this extension to dogfood https://github.com/eclipse/eclipse.jdt.ls project in VS Code, since eclipse.jdt.ls is an OSGI based projects as well.

vscode-pde extension will use a **javaConfig.json** file to resolve your directory structure and eclipse target platform dependencies. You can refer to https://github.com/eclipse/eclipse.jdt.ls/blob/master/javaConfig.json about how to configure it.

**Comment by jiangyubao** [comment]
thank you
