### ISSUE TITLE
trust settings for the gradle wrapper in my vscode settings are added, but seem to be ignored (always get the trust popup)

### ISSUE THREAD

**Issue by thelaoshi** [redhat-developer/vscode-java#2218]
The trust settings for the gradle wrapper in my local settings file seem to be ignored, because I always get the popup where I get asked, if I trust the gradle wrapper.
The problem is, this way the project gradle wrapper will never be used. vscode always uses the "default" wrapper with a too new gradle version for my "old" projects.

##### Environment
- Operating System: Windows 10 (using ubuntu in wsl)
- JDK version: 11.0.11
- Visual Studio Code version: 1.62.2
- Java extension version: v1.0.0

##### Steps To Reproduce
1. open a gradle project with a gradle version different the "default" version of 7.0-rc-1 (5.4 for example)

##### Current Result
I get asked if i trust the wrapper every time I open the project

##### Expected Result
I should only get asked once

##### Additional Informations
The checksum is added to my local settings. json, but still everytime I open the project I get asked to trust the wrapper.

**Comment by rgrunber** [comment]
The allowed wrappers, under `java.imports.gradle.wrapper.checksums`, only get added to the list of allowed wrappers [when the property changes](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradlePreferenceChangeListener.java#L122), but not on imports, so even if someone permits their own wrapper, it won't get recognized. The default wrapper always seems to get used.

CC'ing @snjeza for comment, since I'm not too sure how this is expected to work.
