### ISSUE TITLE
Syntax highlighting stops working with Stream of strings as class static member

### ISSUE THREAD

**Issue by mattwelke** [redhat-developer/vscode-java#2235]
I noticed that when I arranged my code a certain away, the Java syntax highlighting stops working for a portion of the code, even though the code compiles and runs fine.

The code in question is in the file `src/test/java/com/javavscodestarter/CreditCardNumberRedactorTest.java` (see link below). Lines 14-40 lose the syntax highlighting. The "format document" command also doesn't affect those lines.

In VS Code, it looks like this:

![image](https://user-images.githubusercontent.com/7719209/143923668-482c27ce-7791-45fb-9deb-b871f3372d8e.png)

Note how the other code isn't affected, and that there are no problems reported in the PROBLEMS tab at the bottom.

##### Environment
- Operating System:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
- JDK version:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```
- Visual Studio Code version:
```
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
- Java extension version: `v1.1.0`

##### Steps To Reproduce
1. Create class with static member whose value is the return value of `Stream.of`.
Example reproduction:
![image](https://user-images.githubusercontent.com/7719209/143924205-92518690-4646-47c5-a91a-d87712bea46b.png)
2. Observe syntax highlighting.

[Please attach a sample project reproducing the error]
https://github.com/mattwelke/pii-regex-test-java/tree/bug-report-nov-29
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
https://gist.github.com/mattwelke/114d61cf37bb1413d063d38d2b6f724e

##### Current Result

Syntax highlighting doesn't work for static member.

##### Expected Result

Syntax highlighting works for all Java code.

**Comment by mattwelke** [comment]
This is actually the second instance of this problem happening in my code base. I noticed it earlier when I was using a regex expression string for the value of a different class's static member:

![image](https://user-images.githubusercontent.com/7719209/143924691-c76a0ec0-2f9a-4977-8600-b9d4d492589d.png)

I can create a separate issue for that instance of the problem, or I can keep it contained to this issue since it's the same problem just with two different contexts.

**Comment by 0dinD** [comment]
I assume you're using the default color theme, not some modified version?

The syntax highlighting does look a bit strange, but I'm not able to reproduce it when cloning your project (I'm also using version `1.1.0` of the extension). Can you run the **Developer: Inspect Editor Tokens and Scopes** command from the command palette (`Ctrl` + `Shift` + `P`) after putting your caret inside the incorrectly highlighted strings? Some screenshots of the token information would be useful.

**Comment by mattwelke** [comment]
> I assume you're using the default color theme, not some modified version?

That's right. All default theme settings, as far as I know.

![image](https://user-images.githubusercontent.com/7719209/143936002-055e045c-111f-4d42-bdb0-19cee16e7eff.png)

> Can you run the Developer: Inspect Editor Tokens and Scopes command from the command palette (Ctrl + Shift + P) after putting your caret inside the incorrectly highlighted strings? Some screenshots of the token information would be useful (or just paste the text).

Here you go:

![image](https://user-images.githubusercontent.com/7719209/143936128-6f2eff76-8302-4fcd-a86b-e4be680830b6.png)
(copy pasting the text didn't work well)

**Comment by mattwelke** [comment]
I tried making a field using `String[]` instead of `Stream<String>` to see if it would affect that, and it didn't:

![image](https://user-images.githubusercontent.com/7719209/143936408-df66c1ff-c1e1-42d7-b5ca-b4353af58032.png)

Here's that info for this field too:

![image](https://user-images.githubusercontent.com/7719209/143936451-30a8148b-acba-4929-974d-c28783bd027c.png)

**Comment by mattwelke** [comment]
Multi line also appears to have nothing to do with it. Single line has the problem too. I'm wondering if it could be related to the `String...` parameter of `Stream.of`:

![image](https://user-images.githubusercontent.com/7719209/143937451-1f79a445-8cce-4395-be24-6b00a43dabf0.png)

**Comment by 0dinD** [comment]
Yup, that's the default theme.

The tokens are definitely incorrect (which is why the syntax colors are wrong), as you can see the string in the first screenshot has the `variable.parameter.java` scope when it should be `string.quoted.double.java`.

For context, basic tokenization (for strings, brackets, operators etc.) is provided by [a TextMate grammar from Atom](https://github.com/atom/language-java/). There have been lots of problems with it, and TextMate is limited in what it can provide anyways, so I've been progressively enhancing the tokenization using a feature called "semantic tokens" (which are provided by the Java language server). I've not prioritized adding semantic tokens for strings as I assumed they would be highlighted just fine by the TextMate grammar. But you have an example where the TextMate grammar is once again not working very well.

I'm really not sure why that would be, especially since I can't reproduce it myself using the same code and the same version of VS Code and this extension. Another place where the syntax highlighting looks strange is `Stream<String>`, where the angle brackets should not be colored the same as the type names. Can you provide some more token information from placing the cursor at `Stream`, `<` and `String`?

> I'm wondering if it could be related to the `String...` parameter of `Stream.of`

It can't be as far as I'm aware, the TextMate grammar has no knowledge of other Java files (that's the main reason why semantic tokenization is superior). What if you make a similar method in one of your own classes (without varargs)?

---

Also, can you provide a list of all the other extensions you've installed? And for starters, try disabling all of them except the Java extension, to see if it helps. I found it quite unlikely, but another extension could be overriding the Java TextMate grammar with an even more buggy version.

**Comment by mattwelke** [comment]
Ah thanks for the context.

Here's the information:

![image](https://user-images.githubusercontent.com/7719209/143973670-9acdc994-c153-4ee5-892d-0bfb65b6b467.png)
![image](https://user-images.githubusercontent.com/7719209/143973730-d9ab1f71-31bd-4c5d-8bc5-7f2895acb0c6.png)

![image](https://user-images.githubusercontent.com/7719209/143973756-4f32207f-2642-462d-82ec-fe133cc30820.png)

I can't actually get it to target just the `<` character. If I move my cursor one character to the right, it goes from `Stream<` to `String`:

![image](https://user-images.githubusercontent.com/7719209/143973818-bb69f00f-8dd5-435c-8509-c630fe50da5b.png)
![image](https://user-images.githubusercontent.com/7719209/143973837-27750664-436f-48c8-9ab1-e6f71aff4f63.png)

> What if you make a similar method in one of your own classes (without varargs)?

Same problem, so I agree it's not related to var args.

![image](https://user-images.githubusercontent.com/7719209/143973987-056e2c7b-960a-45f5-bdd3-3d63065da32d.png)

**Comment by mattwelke** [comment]
> Also, can you provide a list of all the other extensions you've installed? And for starters, try disabling all of them except the Java extension, to see if it helps. I find it quite unlikely, but another extension could be overriding the Java TextMate grammar with an even more buggy version.

Trying this now with Gitpod so I can get a fresh VS Code with no other extensions except the Java one installed. I'm just opening my repo in GitPod using the technique where you go to `gitpod.io/#<complete_repo_url>` in your browser.

Aha, we're good now:

![image](https://user-images.githubusercontent.com/7719209/143974406-c486289d-2ac9-415c-bc22-0dd7ffc6efbd.png)

So local configuration, probably extensions, is definitely the culprit.

I guess we can close this because we now know that it's not an issue with the extension when the extension is the only one used. But if you'd like to know what I have in my local config that's conflicting, I'm happy to keep this open and report back if I discover what that is.

**Comment by mattwelke** [comment]
Found the culprit: https://marketplace.visualstudio.com/items?itemName=joshuansu.Jshell

![jsh-problem](https://user-images.githubusercontent.com/7719209/143975118-7127cba1-20b2-44e8-bdc8-a4d9d95a0f80.gif)

Thanks for bearing with me. :)
