### ISSUE TITLE
Support publishing pre-release versions

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2285]
- The client UX for pre-release versions - https://code.visualstudio.com/updates/v1_63#_pre-release-extensions 
- How to publish pre-release versions - https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

**Comment by CsCherrYY** [comment]
We have some experimental features and whether to put them in the stable versions depends on the feedback from users. The pre-release channel is a good way to collect early feedback. Here is a proposal about how our extension can use the pre-release channel to release insider versions.

## Background
### Channels

- for VS Code insider users, the default channel is **insider** channel
![image](https://user-images.githubusercontent.com/45906942/150085624-10b489e6-ac08-4b32-9753-eee523d265e7.png)
- for VS Code stable users, the default channel is **stable** channel
![image](https://user-images.githubusercontent.com/45906942/150085672-bc17505d-a8b4-4982-9fbf-02eaaea21b62.png)
- user can manually switch to another channel easily
- for stable channel users, they can get auto-update for newest **stable** versions
- for insider channel users, they can get auto-update for newest **stable** and **pre-release** versions (always the newest one)

### Publishing
- directly pass an argument when `vsce publish`, see https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
> vsce publish --pre-release


## Versioning

### Schema
- for stable versions, the current versioning, **major.minor.patch**, e.g., `1.3.0`
- for pre-release versions, use **major.minor.YYYYMMDDHH**, e.g., `1.3.2022011915`

### Tips
- This can keep the pre-release versions greater than those stable versions in the same minor version.
- At runtime, if we want to distinctguish the two versions, we can just check the patch version.
- Limitation: Can't release 2 pre-release versions in the same hour.

## Repository engineering

Since it's possible to remove the experimental PRs and commits, in this proposal, I just use a specific branch for each kind of release.
### Branches
- **master**: the current master branch, for stable release
- **insider**: the branch for pre-release version
### Management
- Create nightly pre-release build for **insider** branch
  - The major/minor version in `package.json` should be consistent with that in **master** branch, we can just modify the version in pipeline
- For experimental commitments, only merge them into **insider** branch
- For other commitments
  - merge them into **master** branch
  - meantime, a script will automatically merge them into **insider** branch
    - The conflicts should be manually resolved if they exist
- When release a new stable version
  1. if we want to include some experimental commitments
     1. cherry-pick them from **insider** branch into **master** branch
     2. rebase **insider** branch with **master** branch
  2. upgrade the version in **master** branch
  3. if we want to release a new major/minor version
     1. upgrade the version in **insider** branch
     2. release a new pre-release version
  4. release a new stable version

**Comment by rgrunber** [comment]
I think the main annoyance we may introduce is for an experimental contribution that makes it into **insider** and causes merge conflicts on some/many contributions from **stable** branch (changes from **stable** may fail the auto cherry-pick into **insider**).

**Comment by CsCherrYY** [comment]
> I think the main annoyance we may introduce is for an experimental contribution that makes it into insider and causes merge conflicts on some/many contributions from stable branch (changes from stable may fail the auto cherry-pick into insider).

Yeah, this might cause merge conflicts since we are committing into **master** and **insider** at the same time. An alternative way is 

- All new commitments will be merged into **insider**
- when we want to release a new stable version, we cherry pick those commitments from **insider** into **master** manually

Actually, this way we will still encounter those conflicts between experimental commitments and common commitments, but we can avoid 
> changes from stable may fail the auto cherry-pick into insider

**Comment by CsCherrYY** [comment]
Gradle for Java extension has supported the pre-release channel. 

you can see the pre-release version is recommended in vscode-insiders
![image](https://user-images.githubusercontent.com/45906942/154208183-ba9936ad-7ca2-4393-9db1-2ebe16ecc8cc.png)

and the stable version is recommended in vscode stable
![image](https://user-images.githubusercontent.com/45906942/154208302-9a888dae-4084-4a60-b3ff-6d97bd71d440.png)

after installed, you can also switch to the other channel
![image](https://user-images.githubusercontent.com/45906942/154208803-dd8cf065-29df-4169-b8f1-b9688ec610c4.png)

For the branch management, the Gradle for Java extension uses `main` branch (master in the above proposal) to merge all commits and publish nightly build. When releasing, all needed commits should be cherry picked into `release` branch. You can check https://github.com/microsoft/vscode-gradle/blob/main/.azure-pipelines/vscode-gradle-nightly.yml for pipeline details.

**Comment by CsCherrYY** [comment]
Hi @rgrunber, currently the pre-release channel has two requirements:

- engine in `package.json` is greater than `1.63.0`, see: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
- vsce in our Jenkins file should have a greater version than `2.5.0`, see: https://github.com/microsoft/vscode-vsce/releases/tag/v2.5.0

For the engine part, do we have any other concerns about updating this version (about Theia support)? currently it's `1.61.0`.

For the vsce part, I just find we strict the vsce verison in https://github.com/redhat-developer/vscode-java/pull/2195, can we find a way to use the new vsce verison?

**Comment by rgrunber** [comment]
Ok, so we're publishing pre-releases now.

![vscode_java_prerelease](https://user-images.githubusercontent.com/1417342/168101321-79fa464a-fc5b-4570-ad78-76dade723eb3.png)

One thing worth noting, this could exacerbate issues surrounding excessive storage for heavy pre-release users. I'm assuming each new snapshot is getting its own folder :

```
$ pwd
/home/rgrunber/.vscode/extensions
[rgrunber@altrez extensions]$ ls -1 | grep redhat.java | xargs du -sh
138M	redhat.java-1.6.0-linux-x64
138M	redhat.java-1.7.2022051209-linux-x64
```

```
$ pwd
/home/rgrunber/.config/Code/User/globalStorage/redhat.java
[rgrunber@altrez redhat.java]$ 
[rgrunber@altrez redhat.java]$ 
[rgrunber@altrez redhat.java]$ du -sh * 
22M	1.5.0
22M	1.6.0
22M	1.7.2022051209
```

**Comment by CsCherrYY** [comment]
@rgrunber Great! As for the storage issues:

- `.vscode/extensions` might not be a problem since VS Code will automatically delete the old folder when auto-updating. 
- But the `globalStorage` will not be deleted automatically. IMO we need to discuss some mechanism to clean the old folders (~22MB for each in your sample)

**Comment by Eskibear** [comment]
> IMO we need to discuss some mechanism to clean the old folders

This problem exists for all extensions with pre-release. I suggest that we talk to vscode team first, it would be good if they can do the cleanup things.

**Comment by rgrunber** [comment]
We could always add the logic to https://github.com/redhat-developer/vscode-java/blob/72633ab76ea979fc43a7205adf5e2005a5af5388/src/extension.ts#L999 but having it done automatically would be nicer.

One reason for the globalStorage size, is that libraries (eg. jars) that are embedded in other jars (eg. org.eclipse.m2e.maven.indexer embeds a bunch of lucene jars), and need to be added to the classpath at runtime, are placed there. So if we just reduce the usage of that, it should help.

The good news is that M2E 2.0 (assuming we can update from 1.18.0) should eliminate those jars and maybe a few others https://github.com/eclipse/eclipse.jdt.ls/issues/2085

**Comment by CsCherrYY** [comment]
> The good news is that M2E 2.0 (assuming we can update from 1.18.0) should eliminate those jars and maybe a few others [eclipse/eclipse.jdt.ls#2085](https://github.com/eclipse/eclipse.jdt.ls/issues/2085)

In this way, will the updating to the M2E 2.0 eliminate all of them or just most of them?

**Comment by rgrunber** [comment]
It should eliminate some of the ones coming from the maven.indexer bundle. Here are the current contents I see for jars :

```
972K ./46/0/.cp/jdimodel.jar
 12K ./49/0/.cp/lib/launchingsupport.jar
408K ./50/0/.cp/lib/jsoup-1.14.2.jar
 64K ./50/0/.cp/lib/remark-1.2.0.jar
 20K ./54/0/.cp/jars/archetype-catalog-2.4.jar
172K ./54/0/.cp/jars/archetype-common-2.4.jar
 24K ./54/0/.cp/jars/archetype-descriptor-2.4.jar
 20K ./54/0/.cp/jars/archetype-registry-2.4.jar
576K ./54/0/.cp/jars/commons-collections-3.2.2.jar
172K ./54/0/.cp/jars/commons-io-2.2.jar
204K ./54/0/.cp/jars/commons-lang-2.1.jar
320K ./54/0/.cp/jars/dom4j-2.1.3.jar
 28K ./54/0/.cp/jars/jchardet-1.0.jar
152K ./54/0/.cp/jars/jdom-1.0.jar
 32K ./54/0/.cp/jars/maven-invoker-2.1.1.jar
 64K ./54/0/.cp/jars/oro-2.0.8.jar
8.0K ./54/0/.cp/jars/plexus-velocity-1.1.8.jar
384K ./54/0/.cp/jars/velocity-1.5.jar
260K ./59/0/.cp/jars/indexer-core-6.0.0.jar
1.6M ./59/0/.cp/jars/lucene-analyzers-common-5.5.5.jar
424K ./59/0/.cp/jars/lucene-backward-codecs-5.5.5.jar
2.3M ./59/0/.cp/jars/lucene-core-5.5.5.jar
144K ./59/0/.cp/jars/lucene-highlighter-5.5.5.jar
136K ./59/0/.cp/jars/lucene-join-5.5.5.jar
 36K ./59/0/.cp/jars/lucene-memory-5.5.5.jar
248K ./59/0/.cp/jars/lucene-queries-5.5.5.jar
396K ./59/0/.cp/jars/lucene-queryparser-5.5.5.jar
228K ./59/0/.cp/jars/lucene-sandbox-5.5.5.jar
 52K ./60/0/.cp/jars/aether-connector-okhttp-0.17.8.jar
 44K ./60/0/.cp/jars/cdi-api-1.0.jar
 56K ./60/0/.cp/jars/commons-cli-1.4.jar
204K ./60/0/.cp/jars/commons-io-2.5.jar
492K ./60/0/.cp/jars/commons-lang3-3.8.1.jar
512K ./60/0/.cp/jars/guice-4.2.1-no_aop.jar
280K ./60/0/.cp/jars/jansi-1.17.1.jar
8.0K ./60/0/.cp/jars/jsr250-api-1.0.jar
 60K ./60/0/.cp/jars/maven-artifact-3.8.1.jar
 16K ./60/0/.cp/jars/maven-builder-support-3.8.1.jar
284K ./60/0/.cp/jars/maven-compat-3.8.1.jar
620K ./60/0/.cp/jars/maven-core-3.8.1.jar
 96K ./60/0/.cp/jars/maven-embedder-3.8.1.jar
212K ./60/0/.cp/jars/maven-model-3.8.1.jar
188K ./60/0/.cp/jars/maven-model-builder-3.8.1.jar
 48K ./60/0/.cp/jars/maven-plugin-api-3.8.1.jar
 28K ./60/0/.cp/jars/maven-repository-metadata-3.8.1.jar
148K ./60/0/.cp/jars/maven-resolver-api-1.6.2.jar
 48K ./60/0/.cp/jars/maven-resolver-connector-basic-1.6.2.jar
176K ./60/0/.cp/jars/maven-resolver-impl-1.6.2.jar
 68K ./60/0/.cp/jars/maven-resolver-provider-3.8.1.jar
 40K ./60/0/.cp/jars/maven-resolver-spi-1.6.2.jar
 36K ./60/0/.cp/jars/maven-resolver-transport-wagon-1.6.2.jar
168K ./60/0/.cp/jars/maven-resolver-util-1.6.2.jar
 44K ./60/0/.cp/jars/maven-settings-3.8.1.jar
 44K ./60/0/.cp/jars/maven-settings-builder-3.8.1.jar
164K ./60/0/.cp/jars/maven-shared-utils-3.2.1.jar
416K ./60/0/.cp/jars/okhttp-3.14.1.jar
 92K ./60/0/.cp/jars/okio-1.17.3.jar
372K ./60/0/.cp/jars/org.eclipse.sisu.inject-0.3.4.jar
204K ./60/0/.cp/jars/org.eclipse.sisu.plexus-0.3.4.jar
 12K ./60/0/.cp/jars/plexus-build-api-0.0.7.jar
 16K ./60/0/.cp/jars/plexus-cipher-1.7.jar
 52K ./60/0/.cp/jars/plexus-classworlds-2.6.0.jar
8.0K ./60/0/.cp/jars/plexus-component-annotations-2.1.0.jar
 84K ./60/0/.cp/jars/plexus-interpolation-1.25.jar
 28K ./60/0/.cp/jars/plexus-sec-dispatcher-1.4.jar
256K ./60/0/.cp/jars/plexus-utils-3.2.1.jar
 12K ./60/0/.cp/jars/wagon-file-3.4.3.jar
 56K ./60/0/.cp/jars/wagon-provider-api-3.4.3.jar
300K ./75/0/.cp/lib/snakeyaml-1.25.jar
360K ./77/0/.cp/lib/com.microsoft.java.debug.core-0.36.0.jar
320K ./77/0/.cp/lib/commons-io-2.11.0.jar
 12K ./77/0/.cp/lib/reactive-streams-1.0.3.jar
2.3M ./77/0/.cp/lib/rxjava-2.2.21.jar
```

They're grouped by plugin that embeds the jars.

77 (3.0MB) - com.microsoft.java.debug.plugin (extension to JDT-LS)
75 - com.redhat.microprofile.jdt.quarkus (extension to JDT-LS
60 (5.7MB) - org.eclipse.m2e.maven.runtime
59 (5.7MB) - org.eclipse.m2e.maven.indexer
54 (2.2MB) - org.eclipse.m2e.archetype.common
50 - org.eclipse.jdt.ls.core
49 - org.eclipse.jdt.launching
46 - org.eclipse.jdt.debug
