### ISSUE TITLE
m2e logs

### ISSUE THREAD

**Issue by karlvr** [redhat-developer/vscode-java#2367]
I have a Maven build process getting into an infinite loop state, where it's constantly building (I can see it repeatedly spawning processes that should be started once during the build). I would like to see the m2e log, like I did in Eclipse, to try to get a handle on what's going on, but I don't seem to be able to see any output from m2e. Am I missing something or is this something that we could add?

**Comment by rgrunber** [comment]
Closing this out for now as the main issue should be fixed in our next release. There's also https://github.com/redhat-developer/vscode-java/issues/2360#issuecomment-1071083346 where we publish snapshot builds, and in the future we'll be publishing "insider" builds making it easier for consumers to try builds under development.

**Comment by karlvr** [comment]
@rgrunber firstly just a massive thank you for the tip about the regression. I don't know why we didn't think to downgrade; I assumed it was an issue we'd introduced in our code. Our small team thanks you. Meanwhile I'll follow up on the rest, and if you haven't already, I'll try adding your notes to the Wiki.

**Comment by karlvr** [comment]
@rgrunber what do you think about adding commands to this project to open the `.out-jdt.ls...` and `.error-jdt.ls...` log files? I'll tinker with it and produce a PR in case it's useful.
