### ISSUE TITLE
Auto completion crashes suddently

### ISSUE THREAD

**Issue by starklord** [redhat-developer/vscode-java#2425]
In vscode with my java maven projects,the text autocompletion fails and i have to restart vscode to fix the isue. The problem is that it happens almost every 10 minutes i guess so its very annoying
Operative system: Windows 10 64 bits and Windows 11 64 bits
version of vscode: latest: 1.66.2
type of program: any maven project: quarkus, spring-boot, gluonfx
##### Steps To Reproduce
1. Open vscode
2. Open a java maven project
3.  Work for 10 minutes, then use some other application
4.  Go back to vscode and the autocompletion crashes

**Comment by jdneo** [comment]
Is there any errors in log file?  (https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by baincd** [comment]
I was experiencing this frustrating behavior as well.  I believe it was actually this issue in the spring-boot-tools extension: https://github.com/spring-projects/sts4/issues/750.  That issue was resolved two weeks ago in spring-boot-tools 1.33.0, and I haven't experienced this issue since :crossed_fingers:.

**Comment by jdneo** [comment]
Thank you @baincd.

@starklord, could you confirm that the problem is resolved after updating the STS extensions to the latest?
