### ISSUE TITLE
Project keeps using the wrong jdk

### ISSUE THREAD

**Issue by StephaneAdeso** [redhat-developer/vscode-java#2435]
##### Environment
- Operating System: Windows 10 X64
- JDK version: 8, 11 and 17
- Visual Studio Code version: 1.66.2        dfd34e8260c270da74b5c2d86d61aee4b6d56977    x64
- Java extension version: v1.5.0

##### Issue
I have 3 jdks installed on my computer ( 8, 11 and 17). they are on the System path correctly:
![image](https://user-images.githubusercontent.com/55595063/165319122-fd22e715-97ad-4171-835f-3487c1d53a28.png)
And i have my JDKs configured on the `settings.json`: 
```json
{
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\smb\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
    "terminal.integrated.profiles.windows": {
        "cmder": {
            "path": "C:\\WINDOWS\\System32\\cmd.exe",
            "args": ["/K", "C:\\portables\\cmder\\vendor\\bin\\vscode_init.cmd"]
        }
    },
    "terminal.integrated.defaultProfile.windows": "cmder",
    "redhat.telemetry.enabled": true,
    "workbench.iconTheme": "material-icon-theme",
    "java.settings.url": "C:\\libs\\vscode-java.prefs",
    "java.format.settings.url": "C:\\libs\\envira_java_formatter_rules.xml",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "C:\\libs\\jdk8"
        },
        {
            "name": "JavaSE-11",
            "path": "C:\\libs\\jdk-11"
        },
        {
            "name": "JavaSE-17",
            "path": "C:\\libs\\jdk-17"
        }
    ],
    "markdown.extension.preview.autoShowPreviewToSide": true,
    "git.autofetch": true,
    "git.confirmSync": false,
    "explorer.confirmDragAndDrop": false,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.tabWidth": 4,
    "security.workspace.trust.untrustedFiles": "open",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "java.import.gradle.java.home": "C:\\libs\\jdk-11",
    "sonarlint.connectedMode.connections.sonarqube": [
        {
            "serverUrl": "http://172.23.255.212:9000",
            "token": "0c994cd0cdcc651d0c906431eb25c8312d572bc6"
        }
    ],
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "angular.enable-strict-mode-prompt": false
}

```
The `POM` of my project is correctly configured and Runtime configuration is correctly detected: 

![image](https://user-images.githubusercontent.com/55595063/165321943-e127f40a-0bb1-4a44-8c0c-564ecc0ba1b3.png)

But he problem is that when i compile / install my project i got the following error message: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-javaVersion) on project xxxxxx-web: Some Enforcer rules have failed. Look above 
for specific messages explaining why the rule failed. -> [Help 1]

...

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 17.0.2 is not in the allowed range [1.8,1.9).

```
¿ How can i work with diferent jdk withou changing JAVA_HOME each time ?
¿ Isn't VScode supposed to grab the proper jdk if you have everything set up right ?

##### Steps To Reproduce
1. Open a terminal and write `mvn clean compile`

**Comment by fbricon** [comment]
take a look a maven's toolchain mechanism: https://maven.apache.org/guides/mini/guide-using-toolchains.html
You can configure different jdks and have your project use the specific one

**Comment by Osolemio44** [comment]
> > How can i work with diferent jdk withou changing JAVA_HOME each time ?
> > Open a terminal and write `mvn clean compile`
> 
> AFAIK it's out of this extension's scope. You opened a terminal and run `mvn` commands, which is out of vscode's control. It should have the same behavior if you do it without opening vscode.

i have used the Maven panel on VScode this time, and i still have the same problem.

**Comment by Osolemio44** [comment]
> take a look a maven's toolchain mechanism: https://maven.apache.org/guides/mini/guide-using-toolchains.html You can configure different jdks and have your project use the specific one

It is a very old project and I am not allowed to modify it. Therefore I can't include the toolchain plugin. Is there any other way? All my colleagues use Eclipse to launch the project with a specific version of the jdk configuring from the IDE itself. Is that not possible to do from VSCode? I don't want to have to use Eclipse again as I am very satisfied with VSCode.

**Comment by Osolemio44** [comment]
I have been doing tests and from what I see is that both the Maven and Java plugins use the JAVA_HOME variable.
If I set JAVA_HOME with jdk 8, the Java plugin doesn't work because it needs java 11.
If I set JAVA_HOME to jdk 11, my project doesn't compile because it needs Java 8.
And even if it worked, you can't be changing the JAVA_HOME every time you change projects.
From what I see, setting the jdks in the settings.json is of no use.
In Eclipse everything works perfectly without having to modify the pom, or anything in the project or Maven. You can set from the project itself the version of the jdk that should be used. Can't something similar be done in VSCode?

**Comment by rgrunber** [comment]
With the latest vscode-java on windows 64 bit, we provide our own JDK 17, and it gets used as long as you don't set `java.jdt.ls.java.home`. Looking at your settings, you aren't setting this so it should be used and there should be no issue setting `JAVA_HOME`. Did you get the vscode-java extension from the VS Code Marketplace or from somewhere else ?

I did test with a Maven project and it all seems to be working for me. If i define a `JavaSE-1.8` runtime with `java.configuration.runtimes`, it is detected by the import. If I don't, the Java 11 runtime (set as `JAVA_HOME`) is used and appears to compile to Java 8 bytecode (since my pomfile specifies `<maven.compiler.release>8</maven.compiler.release>`). In your case, I guess you'd want to set `JAVA_HOME` to point to your Java 8 path so the enforcer plugin doesn't fail.
