### ISSUE TITLE
Add completion support for multiline comment blocks

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#2464]
When typing following in a java file

```
/*
```
and pressing enter, I would expect it to be completed as follows.

```
/*
*
*/
```
which happens in Eclipse.

##### Environment
- Operating System: Any
- JDK version: Any
- Visual Studio Code version: 1.67.2
- Java extension version: 1.6.0

**Comment by rgrunber** [comment]
It does partially work for both `/*` and `/**`, but for the former it fails because we don't auto-close. I'm not sure where the code is that handles this, but seems it would be on the client side as I'm not seeing any help from the language server to get this working.

![comment-bug](https://user-images.githubusercontent.com/1417342/170086574-222ce8d8-5c23-4278-bee0-d1b5ec7e5262.gif)

**Comment by snjeza** [comment]
>  I'm not sure where the code is that handles this

@rgrunber you may want to take a look at https://github.com/redhat-developer/vscode-java/blob/master/language-configuration.json#L49

**Comment by rgrunber** [comment]
Oops, should have been more specific. @snjeza, yes, I'm aware of just adding to the language-configuration.json (and we can probably do that for this) to get the auto-close behaviour. What I'm not sure about is the behaviour of generating `*` on every `enter` key pressed. Do you know where that logic happens ?

**Comment by snjeza** [comment]
>  What I'm not sure about is the behaviour of generating * on every enter key pressed. Do you know where that logic happens ?

It happens on every enter key pressed. We could try to use /* not *.
```
{
			"open": "/*",
			"close": " */",
			"notIn": [
				"string"
			]
		},
```

**Comment by rgrunber** [comment]
@snjeza has pointed me to https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L671 . That's the one :)
