### ISSUE TITLE
Show Type Hierarchy breaks in vscode-insiders

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2524]
```
Version: 1.69.0-insider (user setup)
Commit: f361c5b71d6676cfc6de97cdb1cc40b08bf7d994
Date: 2022-06-22T05:17:09.661Z
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```

Root cause is renaming of ref-viewlet's publisher. On our side, we can ask both old/new extension ids for compatibility, by PR https://github.com/redhat-developer/vscode-java/pull/2517 . VS Code team will also take action to keep some backward compatibility. More details in see https://github.com/microsoft/vscode/pull/152213#issuecomment-1161912486

**Comment by jdneo** [comment]
I saw the upstream name has been changed back to `vscode.xxx`. Is `ms-vscode.xxx` already released?

**Comment by CsCherrYY** [comment]
> Is `ms-vscode.xxx` already released?

The extension name is always `ms-vscode.xxx` since it's available as an API, and we also use the `ms-vscode.xxx` to fetch the extension API. 

Currently we should track https://github.com/microsoft/vscode/issues/152834, the milestone is June so that there might be a solution before the new release of VS Code stable?
