### ISSUE TITLE
make guess method arguments default enabled

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#2621]
having method arguments guessing on results in much less typing. any reason to not have it default on?

**Comment by jdneo** [comment]
I guess one reason is that sometimes the behavior is unexpected.

for example:

```
long[] a = new long[]{};
Arrays.stream(|)
```

In order to make the argument guessing works, user needs to select the item that have the `long[]` type as the argument, otherwise, the guessing result will be `null`.

If the argument guessing is turned off, a place holder `array` will be filled, which at least providing some context information to users.

**Comment by maxandersen** [comment]
Hmm..shouldn't  guessing result null be used to then do the fallback result?

**Comment by rgrunber** [comment]
This has been the default in Eclipse JDT since 4.18 (2020-12).
https://bugs.eclipse.org/bugs/show_bug.cgi?id=433121

FWIW, I set `"java.completion.guessMethodArguments": true` because I also enabled `"java.inlayHints.parameterNames.enabled": "all"` & `"java.signatureHelp.enabled": true`. So even though I get `null` as a suggestion, I also get the `array` hint from inlay hints and the signature help.

![guess-parameters-and-inlay-hints](https://user-images.githubusercontent.com/1417342/185226570-328bb047-b67c-4108-ae96-5e5237079ecd.gif)

**Comment by jdneo** [comment]
@rgrunber 

Will we consider turning on signature help and method argument guessing in VS Code as well?

**Comment by rgrunber** [comment]
For signatureHelp, if there are no remaining issues with it, maybe we can ? It was discussed at https://github.com/redhat-developer/vscode-java/issues/2063 .

**Comment by jdneo** [comment]
How about:

- We keep it disabled in the August release
- Enable it after the August release

Then we have a long-time window to collect feedbacks from the pre-release channel and take actions if anything unexpected happens.
