### ISSUE TITLE
Disable/Modify inlay hints in Red Hat's vscode-java

### ISSUE THREAD

**Issue by JustJinxed** [redhat-developer/vscode-java#2693]
> ### Discussed in https://github.com/redhat-developer/vscode-java/discussions/2668
> 
> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **Vampyrr85** September  8, 2022</sup>
> Using red hat adds this extra thing in and I cannot figure out how to disable it heres an example from a basic exercise
> 
>  System.out.printf("%.1f C = %.1f F", celsius, farenheit); is what I want it to look like 
>  System.out.printf(format: "%.1f C = %.1f F", celsius, farenheit); is what it adds and it bothers me but I do not know where this feature is to turn it off</div>

 
 Sorry to tag onto this, but I feel it's related-- my inlay in dark+ sets a background color (which makes it look selected), is there a semanticTokenColorCustomizations rule I can use to remove the background color?

**Comment by jdneo** [comment]
The style of the inlay hints is controlled by the client(VS Code). The extension can only provide text of the hints.

If you want to specify the background color of those hints, please file issues at VS Code repo: https://github.com/microsoft/vscode/issues.

I'm closing this issue since it's out of the extension's scope. But feel free to ask questions here if you have any.

Thanks.

**Comment by JustJinxed** [comment]
oh! I made a false presumption it was extension related, due to it turning the option on - thank you jdneo, I was indeed confused. I found the TypeScript section for inlays in vscode and understand this better now.

**Comment by jdneo** [comment]
@JustJinxed You are welcome 😀
