### ISSUE TITLE
Variable definition information should be displayed when the mouse hovers over the variable. This feature works great in Interllij!

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2825]
[provide a description of the issue]

Hello! Found a bug, the document information of the mouse hover variable is displayed incorrectly, please fix it promptly, thanks!
Red Hat Engine: 1.13.0
jdk version: 11~17
vscode: 1.73.1

##### Environment
- Operating System: Windows 10 22H2
- JDK version: 11~17
- Visual Studio Code version: 1.73.1
- Java extension version: 1.13.0

![2022-12-02_164710-2](https://user-images.githubusercontent.com/54253524/205254094-afe7bb89-00d1-4b93-a0f4-c550a8edbf64.png)
![2022-12-02_164241-1](https://user-images.githubusercontent.com/54253524/205254148-1196351d-5a33-4385-aee5-e4dcb2910250.png)

If you do not understand the information described above, you can try it in interllij idea to see how it works?

**Comment by fbricon** [comment]
This is not a bug, hover displays the variable type, its name, then where it was declared. This is the same behavior in Eclipse IDE.

**Comment by zhouxinghong** [comment]
> This is not a bug, hover displays the variable type, its name, then where it was declared. This is the same behavior in Eclipse IDE.

Hello! Because I have not been able to understand that variable what it expresses or what it means? It is very difficult to understand? Can you see how it behaves in the same code in integllij idea?
Even if you think it's not a bug, you should continue to improve it and refine it.
![2022-12-03_083952-3](https://user-images.githubusercontent.com/54253524/205414073-0d21248c-6238-478d-b84b-96800176b27e.png)

**Comment by zhouxinghong** [comment]
Hello! Because I have not been able to understand that variable what it expresses or what it means? It is very difficult to understand? Can you see how it behaves in the same code in integllij idea?
Even if you think it's not a bug, you should continue to improve it and refine it.
![2022-12-03_083952-3](https://user-images.githubusercontent.com/54253524/205414140-8987395c-28a8-4a30-a052-4adb08cc56fc.png)

**Comment by jdneo** [comment]
I changed the title to `Show variable definition information in hover tooltip`, please correct me if I didn't understand your request correctly.

The code point is here: https://github.com/eclipse/eclipse.jdt.ls/blob/35045a66d0f464a3f6d2e1ba59e46f206a4578df/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandler.java#L37.

Contributions are welcome.

**Comment by zhouxinghong** [comment]
Variable definition information should be displayed when the mouse hovers over the variable. This feature works great in Interllij! Hopefully it will be fixed in 1.18, thanks a lot!

**Comment by jdneo** [comment]
@zhouxinghong Would be great if you are interested in contributing this feature.

**Comment by Eskibear** [comment]
@zhouxinghong I would like to say something, just on behalf of myself, as an open-source contributor. 

> This feature works great in Interllij!

This is an open-source project, free of charge. Anyone is welcome to use it and contribute new features. We have been and will be trying hard to improve it, providing Java developers better experience on VS Code. 
IntelliJ is IntelliJ, VS Code is VS Code. It makes no sense to make it the same as IntelliJ. We add something because it's right, not because IntelliJ does.
Anyway, you are also free to use IntelliJ IDEA, which is also a good product.

> please fix it promptly,
> It is very difficult to understand? Can you see how it behaves in the same code in integllij idea?
> Even if you think it's not a bug, you should continue to improve it and refine it.

From your comments I just feel that you are not polite and friendly at all. Again, it's an open-source project. If you would like to push your ideas forward, any discussion, suggestion or findings are welcome. After browsing some other threads of yours, I feel maybe you don't respect other people's effort. You just take all for granted. So I hope you stop being rude, but providing useful information.

**Comment by zhouxinghong** [comment]
terribly sorry! My tone is not good! But I don't mean to disrespect all contributors. If I knew the JavaScript language, I would have perfected this function a long time ago. . .
