### ISSUE TITLE
Surround with if / for / while

### ISSUE THREAD

**Issue by kgoedert** [redhat-developer/vscode-java#2923]
It would be interesting to have a surround with option like the try/catch option, for if / while / for

**Comment by rgrunber** [comment]
Since we have snippets for try/catch, if / while / for, the surround with behaviour exists simply by selecting the text and immediately typing out the desired snippet. At first it looks like you've just overwritten the content, but once a snippet is elected, it is placed within it :

[Screencast from 2024-06-18 10-19-02.webm](https://github.com/redhat-developer/vscode-java/assets/1417342/6ddb5f3d-4fde-453a-9d43-3de70053fc10)

Would this be enough ? I guess it could be made smarter if the snippet could switch between if expression / body depending on whether the selected element returns a boolean.

**Comment by hopehadfield** [comment]
Unfortunately the snippet can't be made smarter in the way that @rgrunber suggested. Right now, a placeholder (`TM_SELECTED_TEXT`) is used by the language server to represent the selected text that is overwritten by the user's snippet prompt. This placeholder is then resolved by the client when the snippet is sent back. The language server does not have access to the selected text in order to evaluate whether or not it's a boolean, nor does the VS Code API support accessing this selected text from the client to send directly to the language server in the completion request.

Alternatively, I looked into adding a choice for the condition to be the selected text, but variables such as `TM_SELECTED_TEXT` are not considered a valid option for VS Code snippet choices.

As stated above, the surround with functionality for if / while / for is supported with snippets for body text. Postfix snippets can also be used to surround a boolean with `if` / `while`, or an array / collection type with `for`, specifically in the condition parentheses (see below).
 
![postfix-if](https://github.com/redhat-developer/vscode-java/assets/115827695/47ca92a7-17ba-43d8-8e78-daaaae25cd36)

Closing this, as I think these snippets serve the purpose outlined in the issue.

**Comment by rgrunber** [comment]
> ... nor does the VS Code API support accessing this selected text from the client to send directly to the language server in the completion request.

I'm not entirely sure if there's no API/hack to access it. It's just becoming a very complicated feature to get working correctly, when longer term, it would be better if upstream just did it correctly for us.

In fact, if you look at the "Surround With" menu in Eclipse :

![image](https://github.com/redhat-developer/vscode-java/assets/1417342/e3bea78c-448a-456a-a3c3-41f184d040c1)

The "Configure Templates" is a giveaway on how they do it, but basically, Eclipse has its own snippet (template) language that defines :

```
if (${condition:var(boolean)}) {
	${line_selection}${cursor}
}
```

So our approach is not that different. The interesting part is that `${condition:var(boolean)}` correctly inserts a field from a parent class! :open_mouth: That might be a bug, or something we never correctly brought over into JDT-LS.
