### ISSUE TITLE
Generate the code repeatedly in new java file

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2939]
##### Environment
- Operating System: Mac
- JDK version: 17.0.6
- Visual Studio Code version: 1.75.1
- Java extension version: 1.15.0

##### Steps To Reproduce
1. Open a java project, like https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/eclipse/simple-app
1. Type the code `File f = new File("demo.txt");` in a main method > Code Actions > Select `Create class xxx`, or `Create interface xxx`, or `Create enum xxx`

![double-showing-code](https://user-images.githubusercontent.com/31497677/219295139-2c837514-cd83-4797-9abe-c15e705958cd.gif)

##### Current Result
Show the code repeatedly in the new java file.

##### Expected Result
Only show the code one time

**Comment by fbricon** [comment]
The bug already exists in 1.14

**Comment by fbricon** [comment]
Probably relates to #2938

**Comment by testforstephen** [comment]
It seems all file creation related refactorings probably have this issue.

For example, it can also be reproduced with "extract interface". The reason is that the client file event listener will inject duplicated snippet when the file is created by a WorkspaceEdit.


https://github.com/redhat-developer/vscode-java/issues/2938 is a different bug, where the server side searching code generated duplicated results.
