### ISSUE TITLE
Unable to run multiple Java projects/files

### ISSUE THREAD

**Issue by GregoryLi360** [redhat-developer/vscode-java#2977]
VS Code Version: 1.76.0
OS Version: MacOS 13.1

Steps to Reproduce:
1. Install Red Hat Java extension
2. Click the run button in the top right
3. Select which Java file to run
4. Click the run button again

Current Behavior:
The same selected file runs over and over again, even when running in a file with a main method.

Expected Behavior (pre-update):
You are allowed to select which file to run again, or if the current file has a main method, it is ran instead.

**Comment by testforstephen** [comment]
@GregoryLi360 Could you share a sample project (including launch.json if it exists) to help us reproduce the issue?

**Comment by GregoryLi360** [comment]
@testforstephen Just having 2 java files with main methods and a third java file without a main method can recreate the issue.

**Comment by testforstephen** [comment]
> Expected Behavior (pre-update):
You are allowed to select which file to run again, or if the current file has a main method, it is ran instead.

We tuned the run behavior in [latest debugger version](https://github.com/microsoft/vscode-java-debug/pull/1301). If the current file has a main method, it still ran directly. However, if it does not have a main method, then the last run of the main class will be automatically selected. this is by design.

**Comment by GregoryLi360** [comment]
Sad :( wish there was an option to turn it back
