### ISSUE TITLE
.class files

### ISSUE THREAD

**Issue by zalcorshark** [redhat-developer/vscode-java#304]
Does this extension open .class files?  

I am getting the following error when I try to open a .class file: "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding."  

The file opens perfectly in Intellij Community.

##### Environment
- Operating System: Windows 10
- JDK version: jdk 1.8.0_144
- Visual Studio Code version: 1.16.1
- Java extension version: 0.10.0

##### Steps To Reproduce
1. Download a .class file.
2. Try to open it in VS Code.

**Comment by fbricon** [comment]
No, this extension doesn't help to decompile class files

**Comment by luebken** [comment]
Why not?

**Comment by fbricon** [comment]
Because we're a very tiny team and we're trying to focus on the Java editing experience. 

Decompiler support can be (actually is) provided by 3rd party extensions. See the [vscode java decompiler extension](https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler) and https://github.com/dgileadi/vscode-java-decompiler/issues/3
