### ISSUE TITLE
Hello! Can the following problem be optimized? This question should not be very complicated for users familiar with JavaScript. Can this issue be brought up on the agenda? This issue has been reported for a long time and has been ignored...

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#3073]
Hello! Can the following problem be optimized? This question should not be very complicated for users familiar with JavaScript. Can this issue be brought up on the agenda? This issue has been reported for a long time and has been ignored...
https://github.com/redhat-developer/vscode-java/issues/2705

**Comment by Eskibear** [comment]
> Can the following problem be optimized?

I don't see any problem in #2705 . And no anyone else is complaining about the same issue, or even thumb-up. Only you.

> This question **should not be very complicated** for users familiar with JavaScript.

How do you know that? Are you familiar with JS? If so, please open a PR directly, and it would be very helpful.

> Can this issue be brought up on the agenda? 

It depends on whether it's important and everyone's schedule. Please respect contributors' effort as I already told you in https://github.com/redhat-developer/vscode-java/issues/2825#issuecomment-1508094364 You are not paying me for doing this, right? If you want to push something forward, the most effective way is to open a PR directly, or provide related information like evidences instead of saying anything "you think should..".

> This issue has been reported for a long time and has been ignored...

This is a solid proof that no one else is following what you brought up, and it's not important or urgent at all.

**Comment by jdneo** [comment]
Please discuss the problem in https://github.com/redhat-developer/vscode-java/issues/2705
