### ISSUE TITLE
Multi Cursor Paste is broken

### ISSUE THREAD

**Issue by lucsoft** [redhat-developer/vscode-java#3153]
Multi Cursor Paste is not working under the Red Hat copy paste extensions. Works without the extensions (or on startup when the extenion is not ready yet)

##### Environment
- Operating System: macOS Ventura 13.4
- JDK version: temurin-17
- Visual Studio Code version: 1.79.1
- Java extension version: v1.19.0

##### Steps To Reproduce
1. Make sure to have the default Multi Cursor Paste spread enabled
2. Copy text with multi cursor in a java project
3. Paste it.

##### Current Result
Multi Cursor Paste Spread setting gets ignored 
##### Expected Result
Multi Cursor Paste Spread doesn't get ignored

**Comment by YYX-KISS** [comment]
请参考[此处](https://github.com/redhat-developer/vscode-java/issues/1115#issuecomment-545347626)，对我来说解决了问题。错误的原因在[这里](https://github.com/microsoft/vscode/issues/83063#issuecomment-545128428)。

**Comment by YYX-KISS** [comment]
java by red hat version 1.13.0 目前可以正常工作。(之后的版本无法正常工作)
使用cmd shift v --> 该拓展的粘贴。
使用cmd v --> vscode的粘贴。

> vscode:
版本: 1.79.2 (Universal)
日期: 2023-06-14T08:58:52.392Z
Chromium: 108.0.5359.215
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0()

**Comment by rgrunber** [comment]
I wasn't able to reproduce this issue . However, we recently fixed a few issues with the custom paste support provided in the Java extension. Instead of the extension contributing a (noop) regular paste when there's nothing to do, we delegate back to the client.

Are you able to reproduce this multi-cursor paste issue with vscode-java 1.26.0 ? The new release came out today.
