### ISSUE TITLE
Copy-paste takes too long in WSL 【1s ~ 5min】

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#3199]
[provide a description of the issue]
In the new class in WSL, i often need to wait 5 seconds to more than 5 minutes for copy-paste operations. Particularly affects work.

##### Environment
- Operating System: Win11
- Remote Operating System: Ubuntu22.04
- JDK version: 17
- Visual Studio Code version: 1.81.0
- Java extension version: 1.20.0 ~ 1.21.0

##### Steps To Reproduce
1. Create a new class and copy and paste it multiple times
![](https://user-images.githubusercontent.com/63572041/252551366-7a718cfb-ea97-4090-8110-dec8b98b8867.png)
![](https://user-images.githubusercontent.com/63572041/253219777-ec2b65b9-5f2d-4b56-b093-0340fb74c1df.png)

##### Current Result
copy and paste wait 1s ~ 5min
##### Expected Result
Copy and paste is done in 1 second

##### Additional Informations
The work plan for the past few days is not finished, SOS

**Comment by mozhuanzuojing** [comment]
Oddly enough, since updating vscode 1.80.1, the incidence of this issue has decreased.

**Comment by benzman81** [comment]
same here

**Comment by mozhuanzuojing** [comment]
`Quick Fix...` Sometimes it's slow.
> here is stack 

[Ctrl + 1 辅助stack1.txt](https://github.com/redhat-developer/vscode-java/files/12136015/Ctrl.%2B.1.stack1.txt)

**Comment by mozhuanzuojing** [comment]
[Copy and paste 堆栈 stack2.txt](https://github.com/redhat-developer/vscode-java/files/12142613/Copy.and.paste.stack2.txt)

**Comment by mozhuanzuojing** [comment]
do you need jfr？

**Comment by mozhuanzuojing** [comment]
[Ctrl + 1 [jfr] .zip](https://github.com/redhat-developer/vscode-java/files/12320163/Ctrl.%2B.1.jfr.zip)

**Comment by mozhuanzuojing** [comment]
[copy & paste [jfr] .zip](https://github.com/redhat-developer/vscode-java/files/12331334/copy.paste.jfr.zip)

**Comment by mozhuanzuojing** [comment]
[copy & paste 【jfr】【1min】.zip](https://github.com/redhat-developer/vscode-java/files/12333095/copy.paste.jfr.1min.zip)
[copy & paste 【jfr】 2min.zip](https://github.com/redhat-developer/vscode-java/files/12333099/copy.paste.jfr.2min.zip)

**Comment by nickzhums** [comment]
@testforstephen @jdneo any idea for this issue? @mozhuanzuojing  is one of our dedicated user from the past, and it seems like several users have ran into this problem.

**Comment by testforstephen** [comment]
> `Quick Fix...` Sometimes it's slow.
> 
> > here is stack
> 
> [Ctrl + 1 辅助stack1.txt](https://github.com/redhat-developer/vscode-java/files/12136015/Ctrl.%2B.1.stack1.txt)

After a look at the callstack, the code action of Introduce parameter uses up all the available threads from the common ThreadPool that is shared by delegate command. This causes the paste command `java.edit.handlePasteEvent` to be delayed and slow to respond. This seems to be the same issue as reported in eclipse-jdtls/eclipse.jdt.ls#2799.

To mitigate this issue, I can think of two possible solutions:

- Handle the paste event synchronously in the main thread, instead of asynchronously with a thread pool. This would avoid the competition for threads. (This is similar to how the code completion works.)
- Optimize the performance of the code action for Introduce parameter, so that it does not consume too many threads or take too long to execute.

**Comment by fbricon** [comment]
You can disable vscode-java's special paste handling with:
```
"[java]": {
   "editor.pasteAs.enabled": false
},
```

**Comment by mozhuanzuojing** [comment]
> You can disable vscode-java's special paste handling with:
> 
> ```
> "[java]": {
>    "editor.pasteAs.enabled": false
> },
> ```

thanks，i will try.
