### ISSUE TITLE
[java-gradle-plugin] Gradle API not resolved when developing Gradle plugins with Java

### ISSUE THREAD

**Issue by JoseLion** [redhat-developer/vscode-java#3260]
When developing Gradle plugins, the Gradle API is added by the `java-gradle-plugin`. Even though the project compiles with no problem, VSCode reports `The import org.gradle cannot be resolved Java(268435846)` on every import of the `org.gradle.*` package. Weird enough, it seems VSCode does have access to any class imported by this package because if we try to go to the definition of the class (e.g. with Ctrl + Click), a decompiled .class file opens.

![image](https://github.com/redhat-developer/vscode-java/assets/3087228/f393d85f-884c-4dd6-a0d5-5031e8246913)
![image](https://github.com/redhat-developer/vscode-java/assets/3087228/693ba579-2993-4c52-b143-ea0eb47bc0c4)
![image](https://github.com/redhat-developer/vscode-java/assets/3087228/c63d9c83-f414-44c0-8968-20d4a6bbe552)

##### Environment
- Operating System: **Windows 11 Home 22H2 | 22621.2215**
- JDK version: **v20.0.2**
- Visual Studio Code version: **v1.81.1**
- Java extension version: **v1.21.0**

##### Steps To Reproduce
1. Create a new Gradle Plugin using Gradle Init:
    - Run `gradle init` command
    - Make sure to select `4: Gradle plugin` in the first step
    - Name the plugin as desired (using Foo for these steps)
    - Complete the init steps
2. Open the file `plugin\src\main\java\foo\FooPlugin.java`
3. The issue will show on the imports of `org.gradle.*` package

- **vscode-java logs after clearing workspace and restarting:** [vscode-app-1693289021299.log](https://github.com/redhat-developer/vscode-java/files/12460855/vscode-app-1693289021299.log)
- **Java Language Server's workspace logs:** [.log](https://github.com/redhat-developer/vscode-java/files/12460874/default.log)

##### Current Result

VSCode shows `The import org.gradle cannot be resolved` on org.gradle.* imports

##### Expected Result

VSCode should resolve org.gradle.* imports when the `java-gradle-plugin` plugin is applied

##### Additional Informations

It seems this issue was already reported in the `vscode-gradle` repository more than a year ago, but was never moved here:
https://github.com/microsoft/vscode-gradle/issues/1257

**Comment by jdneo** [comment]
I didn't observe this with a fresh new created Gradle plugin project. Could you share your project?

![image](https://github.com/redhat-developer/vscode-java/assets/6193897/095a032e-1eaf-4337-810b-da0b36593bca)

BTW, have you installed other Java language support extension?

**Comment by JoseLion** [comment]
Thanks for the response, @jdneo! Okay, so as soon as I saw it worked for you, I cleaned as much as possible to isolate the problem. So I removed all other extensions related to Java, deleted all `.gradle` folders, deleted the VSCode workspace cache, etc.

In the end, I found the real issue 😅 it seems the problem appears only when using the new API. To be exact, when the following line is used:
![image](https://github.com/redhat-developer/vscode-java/assets/3087228/bc83396e-5eaf-4543-be78-650cfe763405)

As soon as line 54 is commented out, the problem disappears. To reproduce the issue, you need to be sure to answer `yes` when the question below is prompted:
```
Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no]
```

I'm also attaching a fresh newly generated project using the API: [new-api-plugin.zip](https://github.com/redhat-developer/vscode-java/files/12482572/new-api-plugin.zip)

**Comment by jdneo** [comment]
Thank you for sharing the project! Actually, I have some new findings with your attached project. And now it seems more like a bug of the extension, because of two reasons:

Even if we do not comment out `gradlePlugin.testSourceSets.add(sourceSets.functionalTest)`

- I can still build the project via `gradle build`
- The project can be successfully imported in IntelliJ, without any unresolved type error.

It's only our extension that is not working with that.

**Comment by jdneo** [comment]
Another update is that we are recently exploring a new way to support Gradle project. I tested it on my machine and it works. Maybe you can try it as well if you are interested in 😄. Below are the steps:

- install the latest pre-release of Gradle for Java extension
  ![Picture1](https://github.com/microsoft/java-debug/assets/6193897/3fcb6b41-5fed-4cfc-8b6a-3c82f057a889)
- (Optional) If you are using VS Code stable, set the setting `"java.gradle.buildServer.enabled"` to `"on"`. Skip this if you are using Insiders
- Run `Java: Clean Java Language Server Workspace` > `Reload and Delete`
- After reload, if you still see 
![image](https://github.com/microsoft/java-debug/assets/6193897/b5055501-845a-4191-9c5c-0b53a9d8a10c)
in the Java Projects explorer, it indicates that the project is still imported by Buildship, you need to clean and reload again. (This is caused by some issues that the bundle is not registered for the first time in a new workspace)
- You should see logs
![image](https://github.com/microsoft/java-debug/assets/6193897/447c5fb5-3117-4130-a7e5-a8af743b7a61)
 in those two output channel if the new importer is working.

**Comment by jdneo** [comment]
It's ok to keep using the pre-release to get the latest enhancement and bug fix.

If you meet any problem, you can file issue at https://github.com/microsoft/vscode-gradle/issues.

In short, the new approach will delegate the build job to Gradle. The java extension is not responsible to generate .class files anymore. Gradle build tool will be used to do the compilation. In other word, we can say bye to the 'bin' folders. 😄

**Comment by nickzhums** [comment]
@JoseLion please feel free to use this new feature in the insider version and let us know if there is any feedback. We aim to use this new feature and make Gradle experience as smooth as possible and love your feedback

**Comment by JoseLion** [comment]
Awesome! I think this new approach is great, much better dev experience, and getting rid of the  "bin" folders is big win too IMO. I'll keep using the pre-release with all my projects and I'll be more than happy to provide as much feedback as I can.

Thanks for the help and for the great insight on this new feature! 🙂🎉

**Comment by nickzhums** [comment]
> Awesome! I think this new approach is great, much better dev experience, and getting rid of the "bin" folders is big win too IMO. I'll keep using the pre-release with all my projects and I'll be more than happy to provide as much feedback as I can.
> 
> Thanks for the help and for the great insight on this new feature! 🙂🎉

Thanks! Feel free to let us any time
