### ISSUE TITLE
java.recommendations.dependency.analytics.show is being ignored

### ISSUE THREAD

**Issue by licam** [redhat-developer/vscode-java#3381]
The setting java.recommendations.dependency.analytics.show is being ignored and although we set it to false, the extension still recommend it on the first time we open pom.xml file.
We would like to turn it off complexly using this setting as was possible before 1.19.0

##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.82.2
- Java extension version: 1.24.0

##### Steps To Reproduce
1. Open a new workspace
2. Install the extension
3. Create a simple Java project
4. In the settings file set java.recommendations.dependency.analytics.show to false
5. Open pom.xml file

##### Current Result
The recommending popup appears

##### Expected Result
The popup to not appear

**Comment by rgrunber** [comment]
You're right. Looks like that setting shouldn't be there at all because it was removed in https://github.com/redhat-developer/vscode-java/commit/02deb55dd84f03d9e574b590c24876a66b0ffeb9#diff-557d2a7d63d5d487fbc01f8871085bc4c926e5bacdbd4e3f9abcc3d108b22419L18-L20 .

I just want to confirm that you want to have the popup not show up on a fresh workspace with a freshly installed vscode-java extension (ie. the first time). Because if you do click the `Never` option, the recommendation would not show up again for that instance of VS Code :

![image](https://github.com/redhat-developer/vscode-java/assets/1417342/88e62926-6627-40ca-b2c3-061be92917fa)

@robstryker is this the kind of thing we should support in the framework itself ? It's probably easy for us to just restore the old option in this case.

**Comment by licam** [comment]
@rgrunber Thanks for your reply.
We actually do not want the pop up to show up at all.
We integrate several tools (and this extension included) in our IDE (SAP Business Application Studio).
We are installing fixed versions which was verified end-to-end in our customers scenarios. We do not want to show recommended extensions popup. 
We were using java.recommendations.dependency.analytics.show up until now with an older version of vscode-java extension and now we want to update this extension but this setting is not working anymore.
We use Code OSS setting of "extensions.ignoreRecommendations": true but it seems that the way you implemented the recommendation ignores that.
Can you please add back the support in this setting?

**Comment by rgrunber** [comment]
I've pushed a PR that would ensure we respect `extensions.ignoreRecommendations`. @licam, would that be enough ? I'm tempted to get rid of the `java.recommendations.dependency.analytics.show` entirely, under the assumption that most users who want to provision vscode-java to disable that setting, would probably also want to disable all other recommendations as well.

**Comment by licam** [comment]
That's a perfect solution from our perspective. @rgrunber Thanks a lot for the quick resolution.

**Comment by rubensa** [comment]
@rgrunber I have a problem with this solution as, currently, looks like the only way to avoid **Language Support for Java(TM) by Red Hat** recommending **Dependency Analytics** is by disabling all recommendations (setting `extensions.ignoreRecommendations` to `true`).

I think that, if this extension is using VSCode "standard" settings to enable/disable recommendations (once the `java.recommendations.dependency.analytics.show` setting has been removed), it should also respect the `unwantedRecommendations` setting in _.vscode/extensions.json_.
