### ISSUE TITLE
Add support for externally provided "lifecycle-mapping-metadata.xml" file

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3393]
_Orginally created by @vitalyla on https://github.com/microsoft/vscode-maven/issues/998_

## Suggestion
Add support for external provided file "lifecycle-mapping-metadata.xml" per M2E recommendations that allows configuration of lifecycle of Maven's plugins outside of any certain project and have it at system/user/workspace level.

## Use Cases
While working on Maven projects it is common that not all plugins undergo changes related to their lifecycle configuration per M2E recommendations, which prohibits execution of those plugins by IDE and as a result required artifacts are not get generated (e.g., generated code) causing compilation and build problems.

Current way to overcome the problem is to manually add relevant m2e annotation (m2e execute onConfiguration) in each "pom.xml" file directly, which is very cumbersome, error prone and problematic approach when working on multiple projects. The impact is bigger when certain files cannot be submitted back to source control system that leads to keeping copies locally creating maintenance overhead.

**Comment by odrotbohm** [comment]
Can someone clarify the current behavior? Finding this ticket, I'm assuming that including build plugins in the IDE issued build would either not happen at all, or the build would trigger all build plugins, not matter what. Currently I am inclined to assume the latter as I have projects with the ByteBuddy plugin performing some (required) enhancements and they seem to actually be applied OOTB in VSCode? 🤔

**Comment by vitalyla** [comment]
Hi @odrotbohm ,
No, it is actually the former. If plugin is not covered by the lifecycle it won't be executed. An example can be swagger/openapi maven plugins that are used to generate artifacts from API specification - without proper configuration of lifecycle these plugins won't be executed that leads to compilation failures of the projects(s) that depend on generated artifacts.

**Comment by odrotbohm** [comment]
That's weird, as I see [my sample](https://github.com/xmolecules/jmolecules-examples/tree/main/jmolecules-spring-data-jdbc) project still running fine after a full rebuild in VSCode, which, in case the Maven Plugin does not run, it definitely shouldn't.

**Comment by vitalyla** [comment]
It depends on the Maven Plugin and how build process is executed. Several core Maven plugins, such as compilation, execution, don't have an issue because they are known to be covered. The impact is more on 3rd party plugins such as OpenAPI Swagger code generation as well as on some Maven core's such as "maven dependency". Not all plugins adopted recommended way of configuration provided by M2e, therefore the problem exists.
Depending on how build process gets executed - if explicitly through the terminal then it will run, however those are not get executed by M2e plugin when loading the project into the workspace.
The problem is noticeable in multi-module project where one project generates artifacts such as OpenAPI artifacts and the other one depends on those.
