### ISSUE TITLE
Renaming the primary type declaration should update the source file name

### ISSUE THREAD

**Issue by loralei28** [redhat-developer/vscode-java#3408]
##### Environment
- Operating System: win/mac
- JDK version: 17.0.8
- Visual Studio Code version:1.84.2
- Java extension version:1.25.0

##### Steps To Reproduce
1.Open an empty VS Code window 
2.Drag a Java file https://github.com/redhat-developer/vscode-java/blob/master/test/resources/projects/eclipse/simple-app/src/app/App.java to it.
3.Change the class name to "App2"

##### Current Result
![image](https://github.com/redhat-developer/vscode-java/assets/108506566/c91b6ecd-5106-44af-8938-b7a8f2545644)

**Comment by rgrunber** [comment]
I assume we are leaning towards updating the file on save because updating while the users is typing would be very annoying. However, with https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save , this could also make the feature just as annoying.

We might need to consider making some setting that automatically disables this functionality when auto-save is enabled.
