### ISSUE TITLE
Setting a keyboard shortcut for java.action.organizeImports breaks Organize Imports

### ISSUE THREAD

**Issue by internetafei** [redhat-developer/vscode-java#3435]
[provide a description of the issue]

##### Environment
- MacOS Monterey
- JDK version:  "17.0.9" 2023-10-17 LTS
- Visual Studio Code version: 版本: 1.85.1
- Java extension version:      Language Support for Java(TM) by Red Hat    v1.26.2023121908

##### Steps To Reproduce
1.Organize imports.  
 press  ’java.action.organizeImports‘ shortcut keys。

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
12月 19, 2023 10:37:36 下午 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
严重: Internal error: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null
	at org.eclipse.jdt.ls.core.internal.handlers.OrganizeImportsHandler.organizeImports(OrganizeImportsHandler.java:110)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$38(JDTLanguageServer.java:1079)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more

##### Expected Result
Organize imports   function is normal.

**Comment by rgrunber** [comment]
```
{
  message: 'Dec. 19, 2023 1:13:35 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError\n' +
    'SEVERE: Internal error: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null\n' +
    'java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)\n' +
    'Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.CodeActionParams.getTextDocument()" because "params" is null\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.OrganizeImportsHandler.organizeImports(OrganizeImportsHandler.java:110)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$38(JDTLanguageServer.java:1079)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)\n' +
    '\t... 7 more\n' +
    '\n',
  level: 'info',
  timestamp: '2023-12-19 13:13:35.619'
}
```

Yup, I'm able to reproduce by setting the `java.action.organizeImports` command to <kbd>ctrl+shift+o</kbd> . I don't know enough about the history but I suspect it was meant to be called by something else, because it takes a `CodeActionParam` as a parameter, which doesn't appear to be set at all when it's set to a command. Can you unset that the `java.action.organizeImports` command, leaving it empty. By default there should already be an "Organize Imports" command that works. The keybindings should look something like this :

![image](https://github.com/redhat-developer/vscode-java/assets/1417342/cd955e9d-d067-4317-90c4-0be165c2a631)

Can you check if such a configuration works for you ?

**Comment by rgrunber** [comment]
I still don't think this has anything to do with the JVM being used or the JAR package you're importing that is to be organized. The error is happening because `java.action.organizeImports` is being bound to a key. The problem is that command requires an argument (file uri) for it to execute, and the key activation does not provide that context. We probably should have made it a hidden command to prevent it being used.

Currently we use `java.action.organizeImports` with :

https://github.com/redhat-developer/vscode-java/blob/eaeedf791546fed4eaa9312b6252faa951ce1b5e/package.json#L1519-L1522

https://github.com/redhat-developer/vscode-java/blob/eaeedf791546fed4eaa9312b6252faa951ce1b5e/src/pasteAction.ts#L10-L53

So when <kbd>ctrl+shift+v</kbd> is used and an editor is present, we make a call to the language server to organize imports.

However, this has been almost entirely replaced by <kbd>ctrl+v</kbd> and the paste event handling API :

https://github.com/redhat-developer/vscode-java/blob/eaeedf791546fed4eaa9312b6252faa951ce1b5e/src/pasteEventHandler.ts#L46

@jdneo , could we completely remove the old "organize imports on ctrl+shift+v" capability ? It seems there isn't a need for it anymore. Doing so might also eliminate the need for those 2 delegate commands that are causing a bit of confusion.

**Comment by internetafei** [comment]
Thank you very much, my problem has been resolved. I upgraded macOS to sonoma, and the problem no longer exists.
