### ISSUE TITLE
Cannot use AltGr+u with U.S. International keyboard

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#348]
_From @GeorgeHernandez on October 26, 2017 19:9_

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
Bookmarks|ale|0.17.0
alignment|ann|0.3.0
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
ftp-sync|luk|0.3.3
mssql|ms-|1.2.0
csharp|ms-|1.12.1
java|red|0.12.0
code-spell-checker|str|1.4.10
json2yaml|tux|0.2.0
vscode-java-debug|vsc|0.2.0

---

Steps to Reproduce:

1. Turn on U.S. International keyboard in Windows.
2. Open file in Visual Studio Code.
3. Type `AltGr+u`

Reproduces without extensions: No

Issue does NOT occur without extensions. However searching keybindings for `Alt+u` does not find anything.

Issue does NOT occur for the other Spanish characters (`¡¿ÁáÉéÍíÑñÓóÚÜü`), just `ú` when entered as `AltGr+u`. 

Issue does NOT occur when entering `ú` via `'+u`.

_Copied from original issue: Microsoft/vscode#37002_

**Comment by aeschli** [comment]
_From @dbaeumer on October 26, 2017 19:39_

@alexandrudima do you have an idea why this could happen even if no extension defines the short cut.

@GeorgeHernandez can you check the contribution for each of your extensions to see whether they do define such a short cut. And can you selectively disable ( can be done in the extension viewlet) the extensions to see if we can find the extension that causes the problem

<img width="1481" alt="capture" src="https://user-images.githubusercontent.com/1931590/32073366-19deb59a-ba96-11e7-8feb-6e88d81ffa41.png">

<img width="545" alt="capture" src="https://user-images.githubusercontent.com/1931590/32073402-3328a024-ba96-11e7-819e-86f910c70377.png">

**Comment by aeschli** [comment]
_From @GeorgeHernandez on October 27, 2017 17:38_

TLDNR: I've isolated it to the "Language Support for Java(TM by Red Hat" extension, but cannot be sure about the "Debugger for Java" extension.

Given [all, debug, java] where:
- all: Enabled status of all extensions except for the Debug and Java extensions.
- debug: Enabled status of the "Debugger for Java" extension.
- java: Enabled status of the "Language Support for Java" extension.

I have tested the permutations for the issue:
- [0,0,0] -> No
- [0,0,1] -> Yes
- [0,1,0] -> N/A. The Debugger is dependent on the Java extension.
- [0,1,1] -> Y
- [1,0,0] -> N
- [1,0,1] -> Y
- [1,1,0] -> N/A. The Debugger is dependent on the Java extension.
- [1,1,1] -> Y

As you can see it only happens when the Java extension is on. Since the Debugger extension is dependent on the Java extension, I could not determine if the former would also cause the issue if the Java extension were fixed.

**Comment by aeschli** [comment]
_From @alexandrudima on October 30, 2017 10:8_

This is indeed caused by `redhat.java`. From their `package.json`:


```
 "keybindings": [
      {
        "command": "java.projectConfiguration.update",
        "key": "ctrl+alt+u",
        "mac": "cmd+alt+u",
        "when": "editorFocus"
      } 
```

---

@GeorgeHernandez  I wonder why `ctrl+alt+u` did not show up when you searched for `alt+u`. Did you use the keybindings UI for searching or did you open the `keybindings.json`. Both should have shown in this case the `ctrl+alt+u` binding when searching for `alt+u`.

> P.S. `AltGr` == `Ctrl+Alt+`

**Comment by aeschli** [comment]
_From @dbaeumer on October 30, 2017 10:8_

@aeschli do you have an idea. 

@GeorgeHernandez please file the issue against the vscode java extension GitHub repository.

**Comment by GeorgeHernandez** [comment]
@alexandrudima

I've searched both the keybinding UI and `keybindings.json`:

- A search for `alt+u` turned up nothing useful but several instances of `alt+up`.
- A search for `ctrl+alt+u` turned up nothing useful but 1 instance of `ctrl+alt+up`.

However, Red Hat's `package.json` does indeed have `"key": "ctrl+alt+u",`. I temporarily changed it to `"key": "ctrl+alt+b",`, enabled the Red Hat extension, and the issue DOES NOT occur!

To summarize, there are 2 parts to this issue:

1. Red Hat SHOULD NOT use `ctrl+alt+u` since it interferes with an `AltGr` shortcut. A search in the keybindings for `ctrl+alt` reveals no other shortcuts that would trigger an `AltGr` shortcut such as `ctrl+alt+u`.  There several letters available that do not trigger an `AltGr` shortcut: [b, f, g, h, j, k, v, x]. See https://en.wikipedia.org/wiki/AltGr_key. 

2. Why does Red Hat's keybinding NOT turn up in either the keybinding UI or JSON file?

**Comment by fbricon** [comment]
I was not aware of the `Ctrl+Alt`/ `Altgr` equivalence. Good to know :-)

PR #349 changes the offending shortcut to `Shift+Alt+u`

**Comment by GeorgeHernandez** [comment]
Part 1: The workarounds (of either using `'+u` instead of `AltGr+u` or modifying the `package.json` file) are tolerable, now that I understand why `AltGr+u` did not work. However, an uninformed user might find the the dysfunctional `AltGr+u` issue intolerable.

BTW: I see that the Bookmarks extension also has a shortcut with an AltGr trigger: `ctrl+alt+l`, so it's not just Red Hat.

Part 2: I had the Red Hat extension disabled, when I searched the keybindings. When enabled, the Red Hat shortcut shows on the list.

**Comment by GeorgeHernandez** [comment]
@fricon I see that you've changed it from `ctrl+alt+u` to `shift+alt+u`. What a nice community! Thanks!
