### ISSUE TITLE
Auto remove front-space after select auto complete

### ISSUE THREAD

**Issue by Chhunneng** [redhat-developer/vscode-java#3508]
After select auto-complete, the line will remove all front space

##### Environment
- Operating System: Mac 
- JDK version: 8
- Visual Studio Code version: 1.86.2
- Java extension version: v1.28.1

##### Steps To Reproduce
1. before writing code, there is `Tab or Space` on that line. after I try any code from auto-complete and select(Example `sout`).
2. I got the result `System.out.println();` but after a moment all `Tab or Space` is removed in that line

[problem's Screen Record]
https://github.com/redhat-developer/vscode-java/assets/47348453/35258531-2843-44c4-9655-e80d260381e6

##### Current Result
After selecting it remove all space on the line

##### Expected Result
Expect to not remove the front spaces

**Comment by rgrunber** [comment]
When you right click on the file and select `Format Document With ...`, are there any entries aside from `Language Support for Java(TM) By Red Hat (default)` ? What happens if you select the `Format Document` option from the context menu. Does it restore the indentation to the line ?

I tried playing with some of the options like `"editor.formatOnSave": true` , `"editor.formatOnType": true` , `"files.autoSave": "afterDelay"` since that could modify the lines about a second after they are input. However, I can't get the Java extension to wrongly remove the line's indentation.

Aside from the Java extension and Codeium, are there an other extensions you have installed ? Do you have the sample project available to share ?

**Comment by Chhunneng** [comment]
> When you right click on the file and select `Format Document With ...`, are there any entries aside from `Language Support for Java(TM) By Red Hat (default)` ? What happens if you select the `Format Document` option from the context menu. Does it restore the indentation to the line ?
> 
> I tried playing with some of the options like `"editor.formatOnSave": true` , `"editor.formatOnType": true` , `"files.autoSave": "afterDelay"` since that could modify the lines about a second after they are input. However, I can't get the Java extension to wrongly remove the line's indentation.
> 
> Aside from the Java extension and Codeium, are there an other extensions you have installed ? Do you have the sample project available to share ?

There is only one format is `Language Support for Java(TM) By Red Hat (default)`
After `Format Document` with restore the indentation to the line as normal. 
I do not use `"editor.formatOnSave": true` and `"editor.formatOnType": true`. 
For `"files.autoSave": "off"`
I try to write code on other language, it does not have any problem. also when I uninstall the extension, it works fine. I also have other extenstions but it's not relate to Java and formatting. The problem is only when I select the auto-complete.

**Comment by rgrunber** [comment]
@snjeza this seems like it's some kind of issue possibly related to our `document/onTypeFormatting` endpoint. I know there's some issue there where formatting behaves incorrectly, but never like this. Are you able to reproduce the behaviour at all ?

**Comment by snjeza** [comment]
@rgrunber I will try.

**Comment by Chhunneng** [comment]
thank for your help now I found the issue on my site.

**Comment by fbricon** [comment]
@Chhunneng car to share what the problem/solution was, in case other users stumble on a similar issue?

**Comment by Chhunneng** [comment]
This issue happened when we used an extension related to auto-complete code example "Codeium" or "Blackbox"
