### ISSUE TITLE
Unreferenced/Unused Method, Field highlight

### ISSUE THREAD

**Issue by mamilic** [redhat-developer/vscode-java#3532]
Type: <b>Feature Request</b>

When I write and develop in Java a lot of code is written and changed, due to nature of development. Someties is happens that some variables or even methods don't get used as initially thought, it would be beneficial if there is a way to provide unused method, field highlight via graying out the field name, or method name respectively.

Extension version: 1.28.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version:
Modes:

**Comment by fbricon** [comment]
This is what you get today:

<img width="1106" alt="Screenshot 2024-03-13 at 16 05 03" src="https://github.com/redhat-developer/vscode-java/assets/148698/ac8eed9d-e5d0-49ed-bcce-7c6d748c5344">

**Comment by mamilic** [comment]
Do apologies, didn't know that it works in some cases and in some it doesn't. It is not working 
- With Enums
- With public static final fields

Would it be possivle for example in case of Constants class, as it does have any references to be grayed out?
![image](https://github.com/redhat-developer/vscode-java/assets/104531795/9ce4253e-cec6-4a6f-bdfc-4e0b98114ed7)

**Comment by fbricon** [comment]
`public` modifier means a 3rd party consumer could actually use your code (eg. you're building a library), so would report false-positive "unused" diagnostics.

**Comment by mamilic** [comment]
Thank you for explanation. Just curious, what would be your approach finding and removing unused public methods, fields, enums from code?

**Comment by fbricon** [comment]
You can try using Intellij, but that feature seems pretty controversial, [so much so that people tend to disable it](https://stackoverflow.com/questions/6166334/disable-not-used-warning-for-public-methods-of-a-class).

It's unlikely such feature will land in vscode-java.

Now if you really **really** want to get that feature working in vscode-java, I'd suggest you write an extension for vscode-java, that would embed https://marketplace.eclipse.org/content/unnecessary-code-detector, stripped of all its UI dependencies. Then you may be get something working. maybe.

**Comment by mamilic** [comment]
Thnank you for suggestions.

**Comment by bigunyak** [comment]
@fbricon the feature of showing unused public methods in greyed out font is extremely useful in IntelliJ to spot dead code. It doesn't need to be treated as a problem or trigger a warning, but it's a nice hint that code might have been left behind. I hope this feature could be implemented in VSCode as well, I'm missing it a lot when coding in VSCode.
