### ISSUE TITLE
Editor Error Highlighting And Fix Suggestions Not works on v1.29.0

### ISSUE THREAD

**Issue by bgunduz55** [redhat-developer/vscode-java#3579]
When I update the extension 1.29.0 version, editor's error detection, highlight and suggestions not working.
Everything is fine after downgrade the version.

##### Environment
- Operating System: Linux Mint
- JDK version: 21
- Visual Studio Code version: 1.88.1
- Java extension version: 1.29.0

##### Additional Informations
I'm using vscode from flatpak. But looks that's not the case.

**Comment by rgrunber** [comment]
Is your project a Maven/Gradle project ? Does the project target Java 21 while having preview features enabled in the build configuration ? Any chance you'd be able to share the project ?

**Comment by bgunduz55** [comment]
Project is private. Maven project. 
Targets Java 21:
![image](https://github.com/redhat-developer/vscode-java/assets/8244985/d3b8e17b-8b76-4ffe-94c2-4d02893efc49)
Also current JAVA_HOME:
![image](https://github.com/redhat-developer/vscode-java/assets/8244985/9b43b6f7-668c-4bff-9e33-225efc51d8ae)
Preview Features enabled:
![image](https://github.com/redhat-developer/vscode-java/assets/8244985/ec04db73-2194-448a-ba75-ecb90df7d543)

**Comment by snjeza** [comment]
@bgunduz55 Could you try to set the project target to Java 22?

**Comment by rgrunber** [comment]
I think you're facing the same issue as https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3131 . In 1.29.0, we added support for Java 22, and the `--enable-preview` flag is only supported for the latest Java version.

As @snjeza just mentioned, if you change the compiler compliance to `22` or leave it as is and remove the `--enable-preview` flag, does the issue go away ?

**Comment by bgunduz55** [comment]
Looks, that's the issue. I just tried remove --enable-preview and it worked on latest version.
I'll try changing compiler target version as 22 too, when I'm available.
Thanks for help @rgrunber  @snjeza .
Is that normal to not use enable preview on 21 for this?

**Comment by snjeza** [comment]
> Is that normal to not use enable preview on 21 for this?

Yes, it is when using VS Code 1.29.0

**Comment by rgrunber** [comment]
It has always been the case that preview feature support can only be used against the latest supported Java version (ie. 22) by the extension. https://bugs.eclipse.org/bugs/show_bug.cgi?id=549258#c11 also gives an explanation of this (and that to follow the JEP, one cannot allow `--enable-preview` to work except for the latest supported Java version.

I'm guessing this is just a lot more visible now because Java 21 is LTS. While before, people had no issues with updating to the latest release level to continue the 2nd/3rd/.. preview of feature , or consume it after it graduates to a standard feature, now users might wish to stay on the Java 21 LTS.

**Comment by fbricon** [comment]
Also documented in https://github.com/redhat-developer/vscode-java/wiki/Enabling-Java-preview-features
