### ISSUE TITLE
Syntax highlighting changes

### ISSUE THREAD

**Issue by realqpat** [redhat-developer/vscode-java#3641]
Seems like the syntax highlighting has changed recently. I've noticed it with the constant variables
They are highlighted the same as a regular variable now
When opening a java file, the syntax highlight is correct and a few seconds later it changes

When checking the developer tools, I noticed the following that seems related but not sure
```
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///opt/visual-studio-code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///home/user/.vscode/extensions/redhat.java-1.30.0-linux-x64/language-support/java/java.tmLanguage.json
register @ TMScopeRegistry.ts:46
```

Is there a way to keep the old grammar file ?

##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.89.0
- Java extension version: 1.30
- Name: Language Support for Java(TM) by Red Hat

**Comment by rgrunber** [comment]
Our java.tmLanguage.json is directly copied into vscode. See https://github.com/microsoft/vscode/blob/facea7e2c298bc0e9fcb553464cd7fc7d4b519e0/extensions/java/syntaxes/java.tmLanguage.json#L2-L6 . Doing a quick comparison the only difference is in the `information_for_contributors` that explains the origin.

The difference probably comes from [semantic highlighting](https://github.com/redhat-developer/vscode-java/?tab=readme-ov-file#semantic-highlighting), which is an extra layer of highlighting done by the language server itself, since it collects even more information about the source file.

Are you using the dark theme ? I noticed a difference on the `Dark+` theme but not on the `Quiet Light` theme. We don't really control the colours, we just provide information on the tokens and it's up to the theme whether it chooses to use that info to distinguish certain tokens from each other (constant vs. variable) or treat them the same.

[Screencast from 2024-05-06 11-03-58.webm](https://github.com/redhat-developer/vscode-java/assets/1417342/bd4f4f0a-6a2f-471c-9771-e20b3b32f6a7)

[Screencast from 2024-05-06 11-04-57.webm](https://github.com/redhat-developer/vscode-java/assets/1417342/44a03b01-eeb6-4340-9686-c657d71fd815)

**Comment by realqpat** [comment]
I checked the token and scope and it's exactly the same for a variable and a constant variable which results in the syntax highlight being the same for both (I presume)
Not sure when this broke but it's fairly recent
I tried to disable some extensions that i thought would be responsible for this but to no avail
And yes, I'm using a light theme but noticed the same behavior no matter the theme I use (light or dark)

![image](https://github.com/redhat-developer/vscode-java/assets/92816716/49ece077-788f-45f1-82ab-96eded5de421)

**Comment by rgrunber** [comment]
Do you have a sample project / snippet of code you're able to share that produces this ? Is there anything in your error logs that indicate a failure to start the language server ?

The popup you're showing doesn't contain any information about the semantic tokens at all, which would indicate you don't have a language server started. Here's what it looks like when the language server is running :

(note the portion about semantic token type and modifiers)
![image](https://github.com/redhat-developer/vscode-java/assets/1417342/530798f5-0319-4556-85fe-33ee4f497183)

**Comment by rgrunber** [comment]
@realqpat is the project available somewhere public ? Are you able to share it ? I don't mind seeing if switching branches (effectively changing build configurations) causes some issues for the language server.
