### ISSUE TITLE
Cursor jumps when typing

### ISSUE THREAD

**Issue by DMJain** [redhat-developer/vscode-java#3665]
Type: <b>Bug</b>

Whenever I stop typing, VS Code gets refreshed and Typing indicator cursor moves away from current typing location. after which I have to manually point to position where I wanted to continue typing my code. 

Extension version: 1.31.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.35GB (5.30GB free)|
|Process Argv|--crash-reporter-id 1d7a7130-2107-4ad6-a068-9675237ba760|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31062275
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by rgrunber** [comment]
I could think of some cases where the cursor would jump, like typing out certain brackets (eg. `{`, `[`, `(` )  that are configured to be auto-closed, or even enabling `java.edit.smartSemicolonDetection.enabled` to have the cursor insert a semicolon at the end of a line. I've even seen it jump in certain cases due to formatting but never from just typing regularly.

Do you have auto-save (`files.autoSave`) enabled (`true`) ? Does this happen with a specific project you're able to share, or does this occur for any project you are editing ?
