### ISSUE TITLE
Favorite imports

### ISSUE THREAD

**Issue by nik9000** [redhat-developer/vscode-java#368]
I'd like something like Eclipse's "Favorites" features for imports. In particular I'd like to be able to say "I like these classes and these static methods so when I hit `ctrl-.` on an unimported class give me those options first if they match". This'd make imports a bit easier and static method imports much easier. I get that they are different things, but Eclipse sticks them together in its UI so I think of them as a single thing.

**Comment by ADTC** [comment]
I'd be happy if the menu is sorted in a more sensible manner. Right now it looks so random and messy. It doesn't even look like a lexicographic sort. **And it's hard to look for the correct import when the menu is very lengthy.** 😞 

![unsorted random list of import and change to suggestions](https://user-images.githubusercontent.com/6047296/34165285-d7ac2a18-e501-11e7-8b42-ef52beeeccba.png)

Can it be sorted so that all the "Import" suggestions appear on top? Followed by "Change to", because more often than not, the class name is correct and I don't need to change it, I just need to import it. And within each type of suggestion, sorting could be lexicographic by default _but_ also any recent/plausible imports or favorites could bubble to the top.

Related: #56

**Comment by fbricon** [comment]
@snjeza can you please see if we can add the equivalent of 
<img width="652" alt="screen shot 2018-01-24 at 11 38 06 am" src="https://user-images.githubusercontent.com/148698/35344421-1947ce54-00fb-11e8-8055-6f8d3b46cbcc.png">

via a server preference like:

```json
	"java.contentAssist.favoriteMembers": [
		"org.junit.Assert.*",
		"org.junit.Assume.*",
		"org.junit.jupiter.api.Assertions.*",
		"org.junit.jupiter.api.Assumptions.*",
		"org.junit.jupiter.api.DynamicContainer.*",
		"org.junit.jupiter.api.DynamicTest.*"		
	]
```

The .* suffix seems to be just for show in Eclipse UI, we could very well ignore it.

My main concern about this feature is if relies too much on jdt.ui, then it'll be harder to port to jdt.ls.

**Comment by fbricon** [comment]
@ADTC can you please open a separate bug report, proposal sort order/relevance is a bit of a different matter.

**Comment by ADTC** [comment]
@fbricon Done with #424

**Comment by fbricon** [comment]
New `java.completion.favoriteStaticMembers` preference allows you to define your favorite imports. Default values are:
```json
	"java.completion.favoriteStaticMembers": [
		"org.junit.Assert.*",
		"org.junit.Assume.*",
		"org.junit.jupiter.api.Assertions.*",
		"org.junit.jupiter.api.Assumptions.*",
		"org.junit.jupiter.api.DynamicContainer.*",
		"org.junit.jupiter.api.DynamicTest.*"		
	]
```
