### ISSUE TITLE
Quick fix - "Create field..." breaks code v1.35.0

### ISSUE THREAD

**Issue by UnnamedXAer** [redhat-developer/vscode-java#3790]
When using Quick fix to create field/local variable part of an existing code is being removed.

##### Environment
- Operating System: win 11
- JDK version: 22.0.1
- Visual Studio Code version: 1.93.1 (user setup) and 1.94.0-indiser
- Java extension version: 1.35.0

##### Steps To Reproduce
1. inside method in a class "assign" value to non-existing field, then use Quick fix... to create that field.

```java
public class Test {
    void set() {
      xx = new String(); // use quick fix -> create field.
    }
  }
```

![20240930-101558_7](https://github.com/user-attachments/assets/7c4c366f-f0c8-404e-bd69-662c1664fb5c)

##### Current Result
Field is not created. Part of the existing  code is removed.

##### Expected Result
Class field is created.

##### Additional Informations
Works with version: 1.34.0

**Comment by UnnamedXAer** [comment]
[already reported](https://github.com/redhat-developer/vscode-java/issues/3781)

**Comment by rgrunber** [comment]
I found the root cause on Windows. It's our code :

https://github.com/redhat-developer/vscode-java/blob/0149fc7323f1a9202dab94fa10eda020d883b459/src/extension.ts#L334

URI from the language server is : `file:///C:/Users/user/projects/foo/Test.java`
URI after converting lsp.codeaction to a vscode.codeaction is : `file:///C%3A/Users/user/projects/foo/Test.java`

The conversion seems to be done by the `asCodeAction` conversion call that occurs higher up.

We can probably fix this by calling `Uri.parse(..)` on the initial Uri we retrieve from the language server.
