### ISSUE TITLE
implementationsCodeLens support for method implementations

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#3813]
implementationsCodeLens support impl of method.

##### Environment
- Operating System:WSL2 - Ubuntu24.04
- JDK version:17
- Visual Studio Code version:1.92
- Java extension version:1.35.1
 

##### Steps To Reproduce
![image](https://github.com/user-attachments/assets/92aef8ec-18e5-406f-beff-42652eea5b79)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
method of interface don't have impl when enable implementationsCodeLens 
##### Expected Result
find impl of method  when enable implementationsCodeLens

**Comment by iwangbowen** [comment]
从你的配置文件里面学到了一些Java插件的一些特性👍

**Comment by mozhuanzuojing** [comment]
I would like to ask how feasible this implementation is, and if it can be implemented, it can reduce the psychological burden of developing a lot of code

**Comment by rgrunber** [comment]
It can definitely be done.
![image](https://github.com/user-attachments/assets/8d78ad58-5a3b-4d10-a12a-971201a94983)

See https://github.com/redhat-developer/vscode-java/issues/416 for the history. We would have to have it guarded by a setting since I would see it affecting performance. Something like :

![image](https://github.com/user-attachments/assets/00de26ea-ac9c-4560-8058-9b9862aef3cd)
