### ISSUE TITLE
Non-java file changes are not processed

### ISSUE THREAD

**Issue by whmmm** [redhat-developer/vscode-java#400]
a spring boot project,only the  .java file can be compiled,when I modify the  file which in /src/main/resources floder that the target/classes file is not  changed.How can I change?

**Comment by gorkem** [comment]
It depends on your build configuration. Are you using maven and hot swapping?

**Comment by fbricon** [comment]
Actually, this is caused by vscode-java ignoring non-java file changes. 

If we were to send all workspace file changes to the server, then m2e will detect process those resources and they'd be copied to target/classes.

But I'm not sure we want the server to take that responsibility. I'd rather encourage users to perform manual builds when non-java changes are involved.

**Comment by gorkem** [comment]
Can we dynamically register locations to watch to the client?

**Comment by fbricon** [comment]
@gorkem I've been thinking about letting 3rd party extensions contribute files patterns for vscode-java to watch, when I started looking at polyglot maven support (so that pom.groovy changes would be picked up for instance). I think I have a good idea on how to proceed, but I have not implemented anything yet.

**Comment by fbricon** [comment]
So maybe we can expose a vscode-java preference for users to add custom watched patterns. @gorkem wdyt?

**Comment by fbricon** [comment]
Since fileevents are used to [configure the client](https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L46-L51), changing the list of watched files would require restarting the extension.

**Comment by gorkem** [comment]
We probably can hack our dynamic solution by using `vscode.createFileSystemWatcher()` API. 

I do not like the custom watch preference because it is not an obvious solution to this issue.

**Comment by fbricon** [comment]
A dynamic solution is irrelevant to end-users.

The immediate problem is not specific to spring boot. So either we add */src/main/resources/* as default watched pattern in vscode-java, or we let users add their own.

**Comment by sant123** [comment]
Any advance on this topic? Just asking 😄

**Comment by fbricon** [comment]
@snjeza can you check how everything behaves with a file watcher on src/main/resources and src/test/resources?

**Comment by snjeza** [comment]
> @snjeza can you check how everything behaves with a file watcher on src/main/resources and src/test/resources?

They are ignored. Java LS builds a workspace only when *.java file, pom.xml for Maven projects or *.gradle for Gradle projects is changed.

We could do the following:

- register all the source folders of all projects as file watchers using the client/registerFeature(workspace/didChangeWatchedFiles) 
See https://github.com/Microsoft/vscode-languageserver-node/blob/c0446d0f878d148f11a1e3d6a3478baacf3a57ff/client/src/client.ts#L1113
In this way, we will watch all the source folders no matter how a project is configured.

- build the workspace incrementally when a watched resource is changed

**Comment by fbricon** [comment]
@snjeza I just tested adding a filewatcher  as workspace.createFileSystemWatcher('**/src/**'). The goal is to have the file changes being seen by server, where a refresh is performed in https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java#L187

This is enough for the m2e builder to trigger mvn resource processing on those changed resources. Tested on the springboot-petclinic project, by changing the files in src/resources/templates

**Comment by nhays89** [comment]
is there a fix for this?

**Comment by fbricon** [comment]
@nhays89 this is supposed to work. Which client are you using?

**Comment by nhays89** [comment]
Yea my bad false alarm. Its picking up the change. I was trying to set a timeout on the embedded tomcat server provided by spring boot via server.servlet.session.timeout=1 in the application properties file ( for testing ) but it was not applying. Turns out a minimum of 60 seconds is required.

**Comment by uy-rrodriguez** [comment]
Dear all,
This issue is linked to some issues with the LiveReload feature of SpringBoot not reloading when templates or assets are modified. Now that this fix has been applied, is LiveReload supposed to work for resources out-of-the-box?

It's not working in my case. I'm using Java 14, pom.xml includes only the dependencies spring-boot-starter-web, spring-boot-starter-oauth2-client, spring-boot-starter-test and spring-boot-devtools. 

I think there could be an issue with VSCode adding the following lines in the .classpath:
`<classpathentry excluding="**" kind="src" output="target/classes" path="src/main/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>`

The file was created automatically and so I guess is any of the Java plugins affecting the LiveReload. I have currently only installed the extensions Language Support for Java(TM) by Red Hat and Java Extension Pack.

**Comment by uy-rrodriguez** [comment]
My bad. Between try and retry, my last configuration (when I decided to comment here) was missing two things:

1. **Activate the plugin**. I somehow deactivated it. The plugin fro Chrome has a little dot in the middle that, when it's white, it means the reloading is deactivated, when it's black is listening for changes.
2. **Add resources to classpath during build time with:**
```
<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <configuration>
                <addResources>true</addResources>
            </configuration>
        </plugin>
    </plugins>
</build>
```

**Comment by FortinFred** [comment]
Any reason why this wouldn't work in a gradle project?

Java configs picks up my resources folder but templates (html) are not "published" to the bin folder automatically.  Have to "rebuild all".
