### ISSUE TITLE
Interface methods missing the “implementation” code lens

### ISSUE THREAD

**Issue by whmmm** [redhat-developer/vscode-java#416]
only the interface has “implementation”
![image](https://user-images.githubusercontent.com/22763406/35311342-009af714-00f1-11e8-88cf-65ad5d44e226.png)

**Comment by fbricon** [comment]
So this is done [by design](https://github.com/eclipse/eclipse.jdt.ls/issues/99#issuecomment-273651025).

There's not *much* added value in adding code lenses for method implementations when the class implementations are already referenced. Computing implementation links for individual methods would also have a negative impact on performances.

**Comment by rgrunber** [comment]
Even for abstract/default methods where a base class need not force implementation on those subclassing ?

What I really like about an "Implementation" codelens on the method is it should be more convenient to jump immediately to the implementation you care about than to first scroll back up to the type declaration, then click jump to the type implementation you care about and then search again for the method.
