### ISSUE TITLE
Resolves incorrect version of dependencies from build.gradle

### ISSUE THREAD

**Issue by mrjones2014** [redhat-developer/vscode-java#559]
In `build.gradle` I have `spring-test` version `4.1.6.RELEASE` as a dependency. When I CMD+Click on a symbol from this dependency to view source, it opens an incorrect version. Hovering over the file name under "open editors" shows `jdt://contents/spring-test-2.5.6.jar`. Updating project configuration does not fix it. Running `gradle build --refresh-dependencies` or even `gradle clean build --refresh-dependencies` does not fix it either.

##### Environment
- Operating System: Mac OS High Sierra 10.13.4
- JDK version: OpenJDK 8u152-zulu
- Visual Studio Code version: 1.24.0
- Java extension version: 0.26.0

##### Steps To Reproduce
1. Create a Gradle project and include `spring-test` version `4.1.6.RELEASE` as a dependency.
2. Write a test using `org.springframework.mock.web.MockHttpServletRequest` like so:
```java
MockHttpServletRequest request = new MockHttpServletRequest();
request.setCookies(new Cookie("timezoneoffset", "0"));
```
If the issue presents itself, the linter should present an error on the `setCookies` method about invalid parameter type.
3. CMD+Click to view source (or CTRL+Click on Windows/Linux) to see that it is the wrong version.

**Comment by fbricon** [comment]
can you please attach a sample project?
Does it work in Eclipse?

**Comment by CsCherrYY** [comment]
If there are multiple restriction of a dependency, Gradle will use its [dependency resolution strategy](https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:resolution-strategy) to handle the conflicts, that's why the source file version of your dependency is different from you expected.

if you want to restrict the dependency, you can use the similar code here:
```
configurations.all {
  resolutionStrategy {
    force group: 'org.springframework', name: 'spring-test', version: '4.1.6.RELEASE'
  }
}
```
or if you want to list all conflicts:
```
configurations.all {
  resolutionStrategy {
    failOnVersionConflict()
  }
}
```
