### ISSUE TITLE
New setting entry to let user choose project type

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#600]
We have projects that have multiple project info inside. Like this one:
https://github.com/spring-guides/gs-spring-boot

Both Gradle and Maven project info exists. In this case, Gradle wins by default.

The project configurations come from the source repo, but when users actually work on it, it's better to have an option to let users choose their preferred project type.

The new setting could look like:
preferredProjectType: "Gradle" // or "Maven"

And the setting could be global or per project.

**Comment by fbricon** [comment]
You can use `java.import.gradle.enabled:false` or `java.import.maven.enabled:false`, for similar results

**Comment by Eskibear** [comment]
@fbricon I tried the both settings, they work in most cases. For some reason I such a repository, in the `Utils` folder, there are Maven based utils, and the main project is Gradle based. I want to import all Maven and Gradle projects, but only Gradle projects are recognized.

**Comment by Eskibear** [comment]
I think the root cause is [Here](https://github.com/eclipse/eclipse.jdt.ls/blob/b49b83a2c30928578fd3085b0a36d918b3bcf20e/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java#L323-L333), When gradle importer applies, it stops checking for other importers. So whenever there is a `build.gradle` file in the workspace, there would be no maven projects recognized I think. 


```java
	private IProjectImporter getImporter(File rootFolder, IProgressMonitor monitor) throws OperationCanceledException, CoreException {
		Collection<IProjectImporter> importers = importers();
		SubMonitor subMonitor = SubMonitor.convert(monitor, importers.size());
		for (IProjectImporter importer : importers) {
			importer.initialize(rootFolder);
			if (importer.applies(subMonitor.split(1))) {
				return importer;
			}
		}
		return null;
	}
```
