### ISSUE TITLE
Standalone Java files are not linked to default project unless being opened. Need to scaffold a project without Maven/Gradle

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#620]
As far as I know, currently whenever a [standalone Java file](https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning) is **opened** in VS Code, it is linked into "src" folder under the default project "jdt.ls-java-project". So it allows users to start from scratch without importing a project. 

But the feature doesn't work for some scenarios. If I open a folder with some existing Java files, the files will not be linked to the default project unless I open each of one by one. Mentioned by @cjbailey in https://github.com/Microsoft/vscode-java-debug/issues/344#issuecomment-416157868

### A simplified example: 
There is a "Hello.java" file existing in my file system, and its' content is:
```java
/**
 * Hello
 */
public class Hello {
    public static void sayHello() {
        System.out.println("hello");
    }
}
```
I wanted to write simple Java code from scratch to test this Hello.java, so I created a "new folder" as my project root and a "src" folder to put java files, and copy "Hello.java" to the folder. Then I open this "new folder" with VSCode. **Without opening "Hello.java"** (this is important), I created a "Main.java", referencing a method in Hello and press F5 to run, error occurred:
![image](https://user-images.githubusercontent.com/2351748/44707342-d6e73500-aad6-11e8-9b51-6dc1ab35912a.png)

### Some thoughts
* If it supports to create a project from current workspace root folder, it would be a better experience for users to start from scratch. For a well-structured folder, I think it also makes more sense to create a project for it instead of link all the Java files into an invisible default project. In Eclipse, the "Import Projects from File System" just works fine for the case, I'm not sure if it is possible to have this feature here. 

* Moreover, a potential feature (https://github.com/redhat-developer/vscode-java/issues/619) enables user to set the source folder, in case language server fails to recognize source folder correctly.

**Comment by testforstephen** [comment]
One idea is when the user opens a standalone java file, prompt the user whether to add the parent directory as Java Source Folder, this will make all standalone java files under the same directory to be added to the default project classpath.
![image](https://user-images.githubusercontent.com/14052197/47278041-43267680-d5f8-11e8-8d02-fb1ff3fbb541.png)

When the user wants to cancel the parent directory as Java Source Folder, he/she can do that through the context menu `Unmark as Java Source Folder`.
![image](https://user-images.githubusercontent.com/14052197/47278144-29d1fa00-d5f9-11e8-96ef-1bdd9c934654.png)

In this approach, the user doesn't need create a new eclipse project and get bothered by the generated .classpath and .project files, but directly leverage the default project to manage the standalone java files.

**Comment by michael-hawker** [comment]
@testforstephen why would it be the parent folder instead of the current folder?  Most basic Java editors (e.g. jGrasp) will just take the current folder for the open file as the classpath.

**Comment by testforstephen** [comment]
@michael-hawker The parent folder represents the direct folder containing the open file. Is this same as the current folder you mentioned? right?

**Comment by michael-hawker** [comment]
@testforstephen yup, think 'containing folder' is the clearer term to avoid my former confusion. :)

**Comment by andxu** [comment]
@testforstephen @fbricon I suggest to use a folder based standalone file strategy,  connect different java files under different folder to default project will make the default project difficult to compile (due to naming conflicts) and  bring in the performance issue(in case of a lot of java files). I suggest to look into the parent folder when opening standalone java file, decided by the folder structure to import the projects under that folder or create a special project related to that folder takes the folder as the project root and source root if no projects are found. 

Whenever a standalone Java file is opened  in vscode, we try to follow some rules to find the right folder for that file:

1. If the file lays under any one of the opened workspace root, open it as common text file if it doesn't belong to any source folder of the projects, or open it as common java file if it belongs to any source folder.
2. If the file has package directive inside, search for the actual project it belongs to according to package declaration.
3. f the file does not have any package directive, its parent folder is the folder we want to work with. Try to open that folder and import the existing projects or create a new project( with the hash of that directory as the project name), and add each of the project root to vscode workspace.

The logic to detect the java project system in a folder: 	

1.	if the folder does not have any projects
a.	Check whether there is an invisible project related to that folder (using the hash of the folder as the project name) already created, use the existing one if there is one
b.	Create an invisible project related to that folder if no existing project was created before
2.	if the folder already have a project inside
a.	Help update project setting to make the standalone file compile
b.	If 2.a is not possible, tell the user why
The invisible project is associate with a folder by using a hash value from the folder’s absolute path.

**Comment by fbricon** [comment]
Standalone file support has been reworked. Opening a folder should now reference all java files in it, via the "invisible project" concept.
