### ISSUE TITLE
Are Eclipse Projects Supported in Visual Studio Code? 

### ISSUE THREAD

**Issue by kevinhpinkerton** [redhat-developer/vscode-java#643]
I'n new to Java in Visual Studio Code. I installed the Java Extension Pack and set the location of my JDK, but I'm having issues with Eclipse Projects in VS Code. Whenever I run my code, .class files are created in my src folder instead of the .bin file. Is there any way to support Eclipse projects in Visual Studio Code to the extent that files go in the appropriate sub-folders? I have .classpath and .project included in my project folder. Isn't that supposed to sort the files? Because right now it isn't working.

**Comment by fbricon** [comment]
We have limited support for stock eclipse projects. Can you please attach your project (stripped down if needed) so we can check what is wrong?

**Comment by kevinhpinkerton** [comment]
I'm sorry I am also new to GitHub. How would I attach the folder?

**Comment by kevinhpinkerton** [comment]
Right now my "project" is a folder with .src and .bin subfolders. It also contains a .project and a .classpath file. My .class files are in the bin folder and my java files are in the src folder. How would I send the entire project.

**Comment by fbricon** [comment]
Zip your project and drag'n drop in the comment section of this ticket

**Comment by kevinhpinkerton** [comment]
[Homework 2.zip](https://github.com/redhat-developer/vscode-java/files/2390286/Homework.2.zip)

**Comment by fbricon** [comment]
So your project imports properly in vscode-java, everythis enabled as expected, references, completion...
I'm not sure what you mean by "Whenever I run my code". How do you run it? There's no main method to run anywhere, no test classes. What exact steps are you following?

**Comment by kevinhpinkerton** [comment]
I have the code runner app. When I hit run it duplicates the .class files into my .src folder. The files are a template for a school project I have so it doesn't actually compile let alone run, but the duplicate files are created nonetheless.

**Comment by fbricon** [comment]
Ok so this is entirely out of scope of vscode-java.

The code runner extension, AFAIK, lets you define the compilation command. If you really really want to use that, then you need to make sure [javac is called with the -d flag](https://stackoverflow.com/a/36682497/753170), and a destination directory, so that class files don't end up in the source directory.

But, you don't even need to compile the files, since vscode-java already did that for you under the bin/ directory

As an alternative to the code runner extension, I strongly recommend using https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug, it'll better integrate with your project, but requires you have a main class.

**Comment by kevinhpinkerton** [comment]
Thank you so much for the help. I'm not too familiar with extensions. Appreciate it.
