### ISSUE TITLE
Language service status is always '`100% Starting Java Language Server - Importing Maven Projects'

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-java#670]
##### Environment
- Operating System: Windows 10
- JDK version:  
```>java -version
openjdk version "1.8.0_161-1-redhat"
OpenJDK Runtime Environment (build 1.8.0_161-1-redhat-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
- Visual Studio Code version: 1.28.0 (user setup)
- Java extension version: 0.32.0

##### Steps To Reproduce
1. [step 1] Add two the same maven projects located in different folders into workspace
2. [step 2] Check Lang Tools status 

##### Current Result
Status is thumb up but message is always `100% Starting Java Language Server - Importing Maven Projects'
##### Expected Result
Status is thumb up and message is 'Ready'
##### Additional Information
I am using [Fabric8 Launcher](https://marketplace.visualstudio.com/items?itemName=jeffmaury.fabric8-launcher-vscode-extension) extension to generate springboot java application using http-rest as a mission and spring-community as a runtime.

**Comment by RobertDeRose** [comment]
Is this a bug? I have the same thing

**Comment by yaohaizh** [comment]
@RobertDeRose  @dgolovin Do the language features such as auto completion and diagnostics working or not?

**Comment by RobertDeRose** [comment]
yes.... just really, really slowly.  Seems like every time I type, the status bar says "Building workspace 0%" then "Validating Document 25%"... "Validating Document 50%"... 2 more times until 100%, then finally intellisense kicks in.  Takes on average about 10 seconds before intellisense kicks in and the entire file stops show red swiggles for everything.

I asked this question because I found this issue when trying to figure out why the Language Server seems to be so slow.

I've tried all the trouble shooting step multiple times, but nothing seems to work.  I've even increased the amount of memory the plugin starts up with to 4G, but it still just takes forever.

**Comment by yaohaizh** [comment]
What's the size of your project?

**Comment by RobertDeRose** [comment]
```bash
du -hd1 src
106M    src/main
```

**Comment by abdullahsaleem93** [comment]
same here...takes forever

**Comment by dmarrazzo** [comment]
Any progress here?
@RobertDeRose how do you change the memory?

**Comment by fbricon** [comment]
You can try the [latest CI build](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D), see if you notice any improvements in code completion (notably thanks to the fix for https://github.com/eclipse/eclipse.jdt.ls/issues/847).

You can increase the memory by setting a higher Xmx value in your `java.jdt.ls.vmargs` preference

**Comment by fbricon** [comment]
Also in case the server seems unresponsive, you can take a heap dump using jstack.
- find the running jdt.ls process (org.eclipse.equinox.launcher*.jar) with `jps`, eg.:
```
 > jps
73156 Jps
68313 org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
```
- execute `jstack processId`, in this case, that'd be `jstack 68313`

**Comment by dmarrazzo** [comment]
I solved giving more memory, but it's still slow (maybe it depends on project dimensions):
```
    "java.jdt.ls.vmargs": "-noverify -Xmx3G -Xss128M -XX:+UseG1GC -XX:+UseStringDeduplication",
```

**Comment by yaohaizh** [comment]
@dmarrazzo Could you try your project with the latest language server? And in which case the VSCode Java is slow? During initialization or editing?

**Comment by dmarrazzo** [comment]
@yaohaizh Yes, it seems much better. It's just a feeling because I haven't an exact measure.

**Comment by RobertDeRose** [comment]
@dmarrazzo Sorry for not replying, been off GH for a while and It's been so long since I've tried to used this extension, I honestly forgot. But @fbricon's comments rang my memory bell.  Hope this project continues to get better, but for me, sadly, for now, I had to drop back to using Eclipse. Not happy about it. I'll give it another try in a few months.

**Comment by brunnooliver7** [comment]
I was having the same issue. After a lot of uninstalling e installing things, sets and configures, I think I found the problem, as it folows:

I properly setted the JAVA_HOME path in Environment Variable, and it was solved. The problem is that I was setting the JAVA_HOME in the the "user variables" and not in the "system variables". After I fixed that, the VS Code recognized the JAVA_HOME path.

![image](https://user-images.githubusercontent.com/39685296/83952787-c4ed0700-a811-11ea-8e6e-0bb64439c8fd.png)

![image](https://user-images.githubusercontent.com/39685296/83952748-4728fb80-a811-11ea-87e0-04faa94a3066.png)

After that, I made a test running, and it was just fine.

>public class App {
>   public static void main(String[] args) throws Exception {
>        System.out.println("Hello, World!");
>    }
>}

> $ "Hello, World!"

**Comment by apupier** [comment]
I tried with latest version 0.76.0

I have the "thumbs up" in bottom status bar after few seconds and everything is working fine.

![Screenshot from 2021-04-01 14-45-22](https://user-images.githubusercontent.com/1105127/113295811-f4b55000-92f8-11eb-8e50-0076bc605460.png)
