### ISSUE TITLE
Getter Setter not generated properly when using complex data types

### ISSUE THREAD

**Issue by shankarramr** [redhat-developer/vscode-java#677]
Getter Setter not generated properly when using complex data types, ex: **Map<String, Map<String, String>>**

Note: Skipping the issue template and other details as I feel this should be reproducible anywhere

**Comment by fbricon** [comment]
Looks good to me:
![getter](https://user-images.githubusercontent.com/148698/47160893-e3aa2d00-d2be-11e8-8619-3ce56748ef4b.gif)

We're gonna need more details to reproduce the issue. Do you see any issues in the [server log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs)?

**Comment by rgrunber** [comment]
I tried the example above using the ways I'm aware of for generating getters/setters :

- through source action
- quick-assist on type declaration
- quick-assist on the field
- method completion for the non-existent methods (getFoo/setFoo)

I also tried having multiple fields in order to go through the quick-pick menu (wizard). None of them produce improperly generated method declarations from what I can see.

Closing this out as we need some example to at least narrow this down. If you're still able to reproduce, feel free to re-open and provide some example.
