### ISSUE TITLE
Code snippet should be working before LS done resolving Maven dependencies

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#684]
Maven dependencies take lots of time to resolve.
![image](https://user-images.githubusercontent.com/16755094/47280661-124f3d00-d60a-11e8-9c19-5c5a99bc5d2c.png)

At that moment, LS is not responding to user key strokes. But some of the features like code snippet can acutally work. The idea is to enable some language servers before the project is completely loaded. Code snippet can be a good start because it require less project context. For example, the `public_method` does not require project context but only the surrounding class.

**Comment by yaohaizh** [comment]
@akaroml For vscode java, there are two types of code snipeets: Client snippet such as **main** and server snippet. For client snippet, it will always work no matter the language server is ready or not.  public_method should be client snippet and should be ready before LS ready.

**Comment by jdneo** [comment]
As for now the client snippet will always work and the server snippet will update to the list once server is ready. This issue can be closed. @testforstephen @rgrunber

**Comment by rgrunber** [comment]
The client side snippets don't always work for me. For a Maven project (eg. spring-petclinic), the snippets resolve initially, but as soon as the project import begins (standard LS), the completion no longer responds until after the build is completed, which can take a bit of time. Seems like this is still an issue.

**Comment by jdneo** [comment]
Yes I can also repro it. Put a breakpoint at https://github.com/redhat-developer/vscode-java/blob/b4f8b07d774acb17bee19f3b06f4d0364a72c682/src/snippetCompletionProvider.ts#L33. It actually returns the snippets but for some unknown reason, VS Code does not display them. Let me investigate what's happening.

**Comment by rgrunber** [comment]
I'm not sure if something has changed since trying out this PR, but the behaviour is a bit different for me now. This is without the PR attached.

- When I load spring-petclinic (no existing workspace for it), I see only the snippets immediately. There's a brief period where I only see dictionary/spelling suggestions but I suspect as soon as the extension starts the snippets take over
- After a certain point I also see completions like `args : String []`, `main(String [] args) : void`, `PetClinicApplcation`. I'm guessing this is when the syntax server starts
- Some time later I see `!MESSAGE Workspace initialized in ...ms` in the logs and the standard language server's `Started` notification is received by the client
- If I trigger completion here, there's a brief moment for which there is no response. After this, I begin seeing a duplicate completion items. I'm guessing the extra one is from the newly started standard language server
- Beyond this point, once the standard server sends "ServiceReady" to the client (after the build jobs finishes), the syntax server shuts down, and I begin seeing only one set of completions

**Comment by jdneo** [comment]
@rgrunber The PR #2240 should solve the issue you mentioned here.

If I remember correctly, we only have `Started` as the end of initialization previously. `ServiceReady` is been added later. Previously the client side snippet will be deactivated when `Started` notification is received.

> I begin seeing a duplicate completion items. I'm guessing the extra one is from the newly started standard language server
Previously, we just let the snippet provider return an empty array to make it deactivated. So all the completion items that provided by it are still visible in the list. Now in #2240, the provider will be disposed, and VS Code will remove them from the list so #2240 should fix this issue as well.
