### ISSUE TITLE
Smart semicolon autocorrect?

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#703]
Intellij has this nice semicolon autocorrect, that when typed within parenthesis instead of end of the line, will automatically insert the semicolon at the end of the line. 
![smart-semicolon](https://user-images.githubusercontent.com/148698/47892291-435f1700-de2d-11e8-97fc-3329996c5f02.gif)

The VS Code marketplace has at [least one](https://marketplace.visualstudio.com/items?itemName=thousandtyone.autoend) extension, which automatically moves the semicolon at the end, but I find it very buggy and causing more harm than it helps (stops inserting all semicolons!). Others require a keyboard shortcut to activate (meh).

I'm opening this issue for consideration

**Comment by fbricon** [comment]
Netbeans has this turned on by default too, although I haven't figured out if there's a preference to control it.
Eclipse supports this too, but needs to be enabled explicitly via: 
Preferences -> Java -> Editor -> Typing -> Automatically insert at correct position -> [x] Semicolons.

@snjeza can you investigate what it'd take to make it happen in vscode too? Automatic insertion of textedits while typing will likely require custom calls to the LS.

**Comment by rgrunber** [comment]
In case anyone is curious, the 2nd gif I mentioned in https://github.com/redhat-developer/vscode-java/pull/3159#issuecomment-1597570913 is actually https://bugs.eclipse.org/bugs/show_bug.cgi?id=506148 . Fun fact. It's the [final bug that was needed (and still is)](https://bugs.eclipse.org/bugs/show_bug.cgi?id=505816#c1) to be resolved in order to enable the feature by default in Eclipse.

Currently we work around that bug by not attempting to the smart insertion at all https://github.com/eclipse/eclipse.jdt.ls/commit/e49a751cdcee4fb2505fbe75e689fec46301973d#diff-a317a5feec9771fbb07fe7c68f9cec2720c03d0977f47e1a9ce31cc82792c9cfR90-R95 .

However, if we have the `MethodInvocation` object, why can't we use that to get the statement in which it resides, and properly insert the semicolon ?
