### ISSUE TITLE
Support for Eclipse .launch files?

### ISSUE THREAD

**Issue by rogersachan** [redhat-developer/vscode-java#706]
This would allow for easy use and compile/launch of projects

**Comment by fbricon** [comment]
This is out of scope of vscode-java. Launch configurations are covered by the [vscode-java-debug](https://github.com/Microsoft/vscode-java-debug) project. 
I honestly don't think this will be a viable solution anyway, since it would require porting some more Eclipse code or dragging more dependencies to support that use case, which can already be achieved with vscode's launch.json files.
