### ISSUE TITLE
Support opening eclipse projects in the workspace depending on each other.

### ISSUE THREAD

**Issue by hannni** [redhat-developer/vscode-java#75]
I have two projects in my eclipse workspace, A and B. They are based in different repositories. B depends on A. I can open the folder of A directly with everything working. However when I open the folder of B directly the stuff B needs from A isn't found ("The import [...] cannot be resolved"). If I open the workspace folder directly everything is found.

The dependencies in B of stuff from A are as absolute paths relative to the workspace in `.classpath`. E.g. `<classpathentry combineaccessrules="false" kind="src" path="/A"/>` or  `<classpathentry kind="lib" path="/A/lib/C.jar"/>`. So I guess the error is somewhere making absolute paths relative to the folder that is opened and not to the eclipse workspace folder, which should be the parent folder.

**Comment by gorkem** [comment]
Our current eclipse support is limited to basic projects. I am reluctant to support this case because this will cause more Eclipse workspace concepts creep into the extension than I would like to see. 

Perhaps for this particular case linked folders could work?

**Comment by mojo2012** [comment]
Well, you could handle support multi-project "solutions"  like described here: http://stufftoddknows.com/2016/07/20/handling-multiple-projects-with-visual-studio-code/
At the end, an eclipse workspace is just a very unflexible way of providing support what MS calls solutions.
I would in fact prefer the way VS or intellij handles multi-project environments, as it is way superior to the eclipse way.

My suggestion is:
* global project definition that just references the sub-projects
* sub project definition, classpath, libs, src folders, target folders

It should not rely on something like maven or ant! I'm working with a huge SAP Hybris code base (several 10k classes, +40 projects, etc) and it is all ant based ... :-\
It's simply not possible to convert this to maven. But that's ok, because It build on the command line anyway.

**Comment by fbricon** [comment]
This is now supported via [multi-root support](https://github.com/redhat-developer/vscode-java/issues/281)
