### ISSUE TITLE
Use VScode for non-maven web project

### ISSUE THREAD

**Issue by TobitakaaSaans** [redhat-developer/vscode-java#754]
Hi, i've been using VSCode with this extension for Maven Spring Boot Projects and it worked well, but now i have to work with an java web project, but not maven based, in which all my libraries are contained in WEB-INF/lib folder. The Problem is that after i open the project in VSCode it dows not recognize these libraries and it gives tons of import errors. 
Is there a way to make java web projects work without maven?
Opening the project in eclipse runs just fine.

Here is the .classpath content of the project:
`<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry kind="con" path="org.eclipse.jst.server.core.container/org.eclipse.jst.server.tomcat.runtimeTarget/Apache Tomcat v8.5"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="src" path="WebContent/WEB-INF/lib"/>
	<classpathentry excluding="lib/" kind="src" path="WebContent/WEB-INF"/>
	<classpathentry kind="output" path="build/classes"/>
</classpath>
`
##### Environment
- Operating System: Windows 10 Pro 
- JDK version: 1.8.0.181
- Visual Studio Code version: 1.30.0 user setup
- Java extension version: v0.36.0

**Comment by fbricon** [comment]
> Is there a way to make java web projects work without maven?
No, unless you can use Gradle as an alternative.

Eclipse project support is limited. To get it to work in your case, we'd need to bring Eclipse WTP into jdt.ls, the java language server, and provide some mechanisms to configure tomcat's location. We decided to focus on the most commonly used build tools instead. 

If the libraries in your WEB-INF/lib folder have been built with Maven, then converting the whole project to Maven would be the best solution. I encourage you to look into the [Maven conversion mechanism]((http://docs.jboss.org/tools/whatsnew/maven/maven-news-4.0.0.Alpha1.html) we built into [JBoss Tools/Red Hat Dev Studio](https://tools.jboss.org/downloads/) a few years ago.
If you're interested, just install the JBoss Tools' Maven bits for its update site into Eclipse, then right click on your project, Convert to Maven. Select the dependencies you want to add to your project, change their scope if needed, then finish the conversion. Hopefully, you should get something that works in both CLI, Eclipse and VS Code.

**Comment by TobitakaaSaans** [comment]
I see. Thanks for the reply, i will take a look on those links to convert it to maven. Thanks.

**Comment by pingu8007** [comment]
I'm new to vscode-java and encountering similar problems. While I can solve it by add EVERY jar as a "lib" classpathentry, it seems vscode don't understand those "con" classpathentry (those build path configuration in eclipse).
Is it the same issue? Is it scheduled to be fixed (at the moment)?

**Comment by tarekahf** [comment]
I need to make some improvements to a JavaBean that is used within a Java Web Application. I cannot have a local copy of the Web Application due to complexity issues. I can open the JavaBean project locally, but I cannot test it unless it is deployed. I am facing a catch-22 situation. I need to find a way to test the improvements locally before deploying the compiled JavaBean. I am thinking to build a simple web application similar to the method used in Eclipse to create Java Web Project without a build tool. This method allows me to test the changes and have it as close as possible to the real web application.

For example, I need to add a function that will load a JSON file from the resource folder or form a data folder under the web application context folder. I need to test that by building a simple web application on my local that simulates the real web application.

Is it possible to create the sample web application in Eclipse and open it in vs code?

Can we create a Simple Java Web Project in vs code without using a build tool?

Any other recommendations?

I appreciate your help.

Tarek

**Comment by Eskibear** [comment]
> Is it possible to create the sample web application in Eclipse and open it in vs code?

AFIAK it should work. /cc @jdneo

**Comment by tarekahf** [comment]
> > Is it possible to create the sample web application in Eclipse and open it in vs code?
> 
> AFIAK it should work. /cc @jdneo

I tried creating a simple dynamic web application and it worked in vscode, but, when I tried adding a Java Bean, it is not working. Check this post for details:
https://stackoverflow.com/q/72159637/4180447
