### ISSUE TITLE
Diamond infer alert for anonymous inner classes

### ISSUE THREAD

**Issue by gavinfish** [redhat-developer/vscode-java#849]
No alert for code like below which is illegal, should provide error message like 'Cannot use ''<>'' with anonymous inner classes'.

```
        List<String> list = new ArrayList<>() {
            {
                add("one");
                add("two");
                add("three");
            }
        }
```

##### Environment
No specific environment

##### Steps To Reproduce
Copy the code in vscode, no alert.

##### Expected Result

alert message with red underline.

**Comment by fbricon** [comment]
''<>'' are authorized in anonymous inner classes since Java 9. If you're running a standalone with a Java 9+ and open a standalone Java class, it'll target that Java version.
If your class is in a project that explicitly targets Java 8 or less, you'll get an `'<>' cannot be used with anonymous classes` error
