### ISSUE TITLE
Java Debugging

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#9]

**Comment by scgm11** [comment]
are you planning on support debug and remote debug for java?

**Comment by fbricon** [comment]
Yes, eventually.  But our resources are pretty strained. Contributions are welcome :-)

**Comment by ntt2k** [comment]
I am junior developer and want to contribute my time to make this feature happen:
+ debug and remote debug for java
+ possible support for popular web framework like Spring / Spring MVC / Spring Boot

Can any Senior developer here point me to the resource that I can learn and start to 'bootstrap' to implement these features into plugin 'redhat-developer/vscode-java' ?

**Comment by gorkem** [comment]
I do not think we should host the tooling for *all* Java frameworks on this extension. I would rather concentrate on enablers such as  #111 (#5) for other extensions to implement framework specific tooling. Perhaps you can contribute to this [repository](https://github.com/ecmel/vscode-spring-boot) or have your own extension that utilizes APIs from this one for Spring boot.

For debugging we will be using [debug protocol ](https://github.com/Microsoft/vscode-debugadapter-node) directly from our Java server. I think the first step is to create the bindings for the debug protocol. Protocol is defined as a [json schema](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json), perhaps you can get started with creating binding from the schema. You can see an[ example of ](https://github.com/gorkem/java-language-server/blob/master/lang-protocol-generator/pom.xml#L19) POJO generation from JSON schemas on the server repository. If you decide to tackle the POJO generation, please file an issue specific for that to discuss details.

**Comment by fbricon** [comment]
Matching issue on the server side: https://github.com/eclipse/eclipse.jdt.ls/issues/157

**Comment by bmingles** [comment]
Curious if any work has been done on the debugging feature?

**Comment by fbricon** [comment]
Current work on the debugger can be found under : 
- https://github.com/vscjavaci/vscode-java : for the vscode extension
- https://github.com/vscjavaci/eclipse.jdt.ls : for the jdt.ls+debugger server

As I go over the code and test stuff out, I'll post/update remarks here:

With the current state of the WIP, I was able to:
- start a Main class in debug
- add breakpoints, that are respected by the debugger
- advance step by step

However, some critical things are missing from an [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) standpoint
- variables are not displayed
- hence they can't be modified
- no standard or error output for the program being run

Other critical aspects, that'll have to be dealt with sooner rather than later. I have no doubt they'll be adressed eventually, just listing them here for track keeping:
- classpath doesn't respect Maven (or Gradle) scopes. For now all classpath from the current project is used for runtime execution
- Java 9's modulepath is not covered yet, as expected


[more to come]

**Comment by fbricon** [comment]
@akaroml I still can't see variables with the latest code from vscjavaci master branches

**Comment by akaroml** [comment]
@fbricon Sorry for feeding inaccurate info during the sync meeting. The pull request for working with variables was actually rejected by me for design issues and we are reworking it.
It's good that you provide this check list for MVP. We'll run through it and share more info later.

**Comment by ansyral** [comment]
hi, @fbricon  about this one:
> classpath doesn't respect Maven (or Gradle) scopes. For now all classpath from the current project is used for runtime execution

do you mean that we should expose compile classpath? i tested a simple Maven project, and it could debug well, could you give me more hints how it doesn't work? Thanks~

**Comment by fbricon** [comment]
@ansyral if you add junit to your project with the `test` scope, then when executing a main class, it should not be available at runtime. Try running this:

```java
    public static void main(String[] args) {
        try {
            Class.forName("org.junit.Test");
            System.err.println("Junit is on the classpath");//SHOULD NOT HAPPEN AT RUNTIME
        } catch (ClassNotFoundException expected) {
            System.err.println("Junit is NOT on the classpath");
        }
    }
```
If you run that in Eclipse, it'll work as expected, because m2e [adjusts the available classpath of the launch configuration](https://github.com/eclipse/m2e-core/blob/11922879173b8516103e935c574be289bc1cbe9c/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/launch/MavenRuntimeClasspathProvider.java#L119).

**Comment by akaroml** [comment]
We just released the Java Debug Extension for Visual Studio Code. This extension adds debugging support to the language server. You can find the new extension here:
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug

@fbricon @gorkem please see if we can close this issue.

**Comment by fbricon** [comment]
Closing as the debugger is available from https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug
